// Generated by scripts/port.ts. Hand edits are expected from here on.
export function AboutJoshuattio() {
  return (
    <section className="grid grid-cols-24 bg-primary-background pt-20 pb-15 last:pb-30">
      <h3 className="col-[3/-3] font-semibold text-2xl">
        {"About Joshuattio"}
      </h3>
      <div className="col-[3/12] mt-10 flex flex-col gap-3 text-pretty max-lg:col-[3/-3]">
        <div className="font-normal leading-6.5">
          <div>
            <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
              {"Joshuattio is the agentic CRM that meets you where you work, compounds every signal into context, then acts on it across your pipeline so you move at unmatched speed and scale. Teams use it to get ahead, know their next move, and raise the ceiling on what's possible."}
            </p>
            <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
              {"Founded in London by "}
              <a href="#" className="-mx-px rounded-sm px-px underline transition-colors duration-400 hover:duration-150 active:duration-50 text-link-foreground decoration-transparent hover:text-link-strong-foreground hover:decoration-link-strong-foreground active:text-link-strong-foreground">
                {"Robin Carlson"}
              </a>
              {" and "}
              <a href="#" className="-mx-px rounded-sm px-px underline transition-colors duration-400 hover:duration-150 active:duration-50 text-link-foreground decoration-transparent hover:text-link-strong-foreground hover:decoration-link-strong-foreground active:text-link-strong-foreground">
                {"Maximilian Hartley"}
              </a>
              {" in 2019."}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
