// Generated by scripts/port.ts. Hand edits are expected from here on.
export function Naming() {
  return (
    <section className="grid grid-cols-24 bg-primary-background pt-20 pb-15 last:pb-30">
      <h3 className="col-[3/-3] font-semibold text-2xl">
        {"Naming"}
      </h3>
      <div className="col-[3/12] mt-10 flex flex-col gap-3 text-pretty max-lg:col-[3/-3]">
        <div className="font-normal leading-6.5">
          <div>
            <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
              {"Joshuattio is spelled as one word with an uppercase J. It names our company and product. Joshuattio is pronounced \"JOSH-ee-oh\" with emphasis on the first syllable and a strong “t” sound. Softer “t” sounds and broader vowels from regional accents are acceptable."}
              <br />
              <br />
              {"Capitalize Joshuattio product names, such as Call Intelligence, Workflows, and Ask Joshuattio. Keep product features lowercase, such as custom objects, people object, and permissions."}
              <br />
            </p>
            <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
              {"Read "}
              <a target="_self" className="-mx-px rounded-sm px-px underline transition-colors duration-400 hover:duration-150 active:duration-50 text-link-foreground decoration-transparent hover:text-link-strong-foreground hover:decoration-link-strong-foreground active:text-link-strong-foreground" href="/blog/how-we-chose-the-name-joshuattio">
                {"how we chose the name Joshuattio"}
              </a>
              {" on our blog."}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
