// Generated by scripts/port.ts. Hand edits are expected from here on.
export function Photos() {
  return (
    <section className="grid grid-cols-24 bg-primary-background pt-20 pb-15 last:pb-30">
      <h3 className="col-[3/-3] font-semibold text-2xl">
        {"Photos"}
      </h3>
      <div className="col-[3/12] mt-10 flex flex-col gap-3 text-pretty max-lg:col-[3/-3]">
        <div className="font-normal leading-6.5">
          <div>
            <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
              {"Images of our team and out-of-home campaigns, ready for editorial use."}
            </p>
          </div>
        </div>
      </div>
      <div className="col-[3/-3] mt-10">
        <div className="grid grid-cols-2 gap-5 max-lg:grid-cols-1">
          <div className="flex flex-col gap-4 rounded-lg border border-subtle-stroke p-4">
            <div className="aspect-[3/2] overflow-hidden rounded-md bg-white-200">
              <img alt="Maximilian Hartley" loading="lazy" width="5333" height="8000" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} sizes="(max-width: 992px) 100vw, 50vw" srcSet="/img/img-741d02cc82.avif 384w, /img/img-741d02cc82.avif 640w, /img/img-741d02cc82.avif 750w, /img/img-741d02cc82.avif 828w, /img/img-741d02cc82.avif 1080w, /img/img-741d02cc82.avif 1200w, /img/img-741d02cc82.avif 1920w, /img/img-741d02cc82.avif 2048w, /img/img-741d02cc82.avif 3840w" src="/img/img-741d02cc82.avif" />
            </div>
            <div className="flex items-center justify-between gap-5">
              <div className="flex min-w-0 flex-col gap-0.5">
                <p className="truncate font-medium text-sm">
                  {"Maximilian Hartley"}
                </p>
                <p className="text-accent-foreground text-xs tabular-nums">
                  {"["}
                  {"JPG"}
                  {"] "}
                  {"5333"}
                  {" × "}
                  {"8000"}
                </p>
              </div>
              <a href="/img/img-741d02cc82.avif" rel="noopener noreferrer" target="_blank" className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline">
                <span>
                  {"Download"}
                </span>
              </a>
            </div>
          </div>
          <div className="flex flex-col gap-4 rounded-lg border border-subtle-stroke p-4">
            <div className="aspect-[3/2] overflow-hidden rounded-md bg-white-200">
              <img alt="Robin Carlson" loading="lazy" width="1778" height="2667" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} sizes="(max-width: 992px) 100vw, 50vw" srcSet="/img/img-ee359acccf.avif 384w, /img/img-ee359acccf.avif 640w, /img/img-ee359acccf.avif 750w, /img/img-ee359acccf.avif 828w, /img/img-ee359acccf.avif 1080w, /img/img-ee359acccf.avif 1200w, /img/img-ee359acccf.avif 1920w, /img/img-ee359acccf.avif 2048w, /img/img-ee359acccf.avif 3840w" src="/img/img-ee359acccf.avif" />
            </div>
            <div className="flex items-center justify-between gap-5">
              <div className="flex min-w-0 flex-col gap-0.5">
                <p className="truncate font-medium text-sm">
                  {"Robin Carlson"}
                </p>
                <p className="text-accent-foreground text-xs tabular-nums">
                  {"["}
                  {"PNG"}
                  {"] "}
                  {"1778"}
                  {" × "}
                  {"2667"}
                </p>
              </div>
              <a href="/img/img-ee359acccf.avif" rel="noopener noreferrer" target="_blank" className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline">
                <span>
                  {"Download"}
                </span>
              </a>
            </div>
          </div>
          <div className="flex flex-col gap-4 rounded-lg border border-subtle-stroke p-4">
            <div className="aspect-[3/2] overflow-hidden rounded-md bg-white-200">
              <img alt="Robin Carlson and Maxim Hartley" loading="lazy" width="4000" height="2667" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} sizes="(max-width: 992px) 100vw, 50vw" srcSet="/img/img-543b0631ea.avif 384w, /img/img-543b0631ea.avif 640w, /img/img-543b0631ea.avif 750w, /img/img-543b0631ea.avif 828w, /img/img-543b0631ea.avif 1080w, /img/img-543b0631ea.avif 1200w, /img/img-543b0631ea.avif 1920w, /img/img-543b0631ea.avif 2048w, /img/img-543b0631ea.avif 3840w" src="/img/img-543b0631ea.avif" />
            </div>
            <div className="flex items-center justify-between gap-5">
              <div className="flex min-w-0 flex-col gap-0.5">
                <p className="truncate font-medium text-sm">
                  {"Robin Carlson and Maxim Hartley"}
                </p>
                <p className="text-accent-foreground text-xs tabular-nums">
                  {"["}
                  {"JPG"}
                  {"] "}
                  {"4000"}
                  {" × "}
                  {"2667"}
                </p>
              </div>
              <a href="/img/img-543b0631ea.avif" rel="noopener noreferrer" target="_blank" className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline">
                <span>
                  {"Download"}
                </span>
              </a>
            </div>
          </div>
          <div className="flex flex-col gap-4 rounded-lg border border-subtle-stroke p-4">
            <div className="aspect-[3/2] overflow-hidden rounded-md bg-white-200">
              <img alt="Sales is changing" loading="lazy" width="2700" height="2160" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} sizes="(max-width: 992px) 100vw, 50vw" srcSet="/img/img-76b9e4c6c5.jpg 384w, /img/img-76b9e4c6c5.jpg 640w, /img/img-76b9e4c6c5.jpg 750w, /img/img-76b9e4c6c5.jpg 828w, /img/img-76b9e4c6c5.jpg 1080w, /img/img-76b9e4c6c5.jpg 1200w, /img/img-76b9e4c6c5.jpg 1920w, /img/img-76b9e4c6c5.jpg 2048w, /img/img-76b9e4c6c5.jpg 3840w" src="/img/img-76b9e4c6c5.jpg" />
            </div>
            <div className="flex items-center justify-between gap-5">
              <div className="flex min-w-0 flex-col gap-0.5">
                <p className="truncate font-medium text-sm">
                  {"Sales is changing"}
                </p>
                <p className="text-accent-foreground text-xs tabular-nums">
                  {"["}
                  {"JPG"}
                  {"] "}
                  {"2700"}
                  {" × "}
                  {"2160"}
                </p>
              </div>
              <a href="/img/img-76b9e4c6c5.jpg" rel="noopener noreferrer" target="_blank" className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline">
                <span>
                  {"Download"}
                </span>
              </a>
            </div>
          </div>
          <div className="flex flex-col gap-4 rounded-lg border border-subtle-stroke p-4">
            <div className="aspect-[3/2] overflow-hidden rounded-md bg-white-200">
              <img alt="Customer relationship magic" loading="lazy" width="3456" height="2234" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} sizes="(max-width: 992px) 100vw, 50vw" srcSet="/img/img-7f47ad71a4.jpg 384w, /img/img-7f47ad71a4.jpg 640w, /img/img-7f47ad71a4.jpg 750w, /img/img-7f47ad71a4.jpg 828w, /img/img-7f47ad71a4.jpg 1080w, /img/img-7f47ad71a4.jpg 1200w, /img/img-7f47ad71a4.jpg 1920w, /img/img-7f47ad71a4.jpg 2048w, /img/img-7f47ad71a4.jpg 3840w" src="/img/img-7f47ad71a4.jpg" />
            </div>
            <div className="flex items-center justify-between gap-5">
              <div className="flex min-w-0 flex-col gap-0.5">
                <p className="truncate font-medium text-sm">
                  {"Customer relationship magic"}
                </p>
                <p className="text-accent-foreground text-xs tabular-nums">
                  {"["}
                  {"JPG"}
                  {"] "}
                  {"3456"}
                  {" × "}
                  {"2234"}
                </p>
              </div>
              <a href="/img/img-7f47ad71a4.jpg" rel="noopener noreferrer" target="_blank" className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline">
                <span>
                  {"Download"}
                </span>
              </a>
            </div>
          </div>
          <div className="flex flex-col gap-4 rounded-lg border border-subtle-stroke p-4">
            <div className="aspect-[3/2] overflow-hidden rounded-md bg-white-200">
              <img alt="Customer relationship magic" loading="lazy" width="3456" height="2234" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} sizes="(max-width: 992px) 100vw, 50vw" srcSet="/img/img-a648adcd0f.jpg 384w, /img/img-a648adcd0f.jpg 640w, /img/img-a648adcd0f.jpg 750w, /img/img-a648adcd0f.jpg 828w, /img/img-a648adcd0f.jpg 1080w, /img/img-a648adcd0f.jpg 1200w, /img/img-a648adcd0f.jpg 1920w, /img/img-a648adcd0f.jpg 2048w, /img/img-a648adcd0f.jpg 3840w" src="/img/img-a648adcd0f.jpg" />
            </div>
            <div className="flex items-center justify-between gap-5">
              <div className="flex min-w-0 flex-col gap-0.5">
                <p className="truncate font-medium text-sm">
                  {"Customer relationship magic"}
                </p>
                <p className="text-accent-foreground text-xs tabular-nums">
                  {"["}
                  {"JPG"}
                  {"] "}
                  {"3456"}
                  {" × "}
                  {"2234"}
                </p>
              </div>
              <a href="/img/img-a648adcd0f.jpg" rel="noopener noreferrer" target="_blank" className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline">
                <span>
                  {"Download"}
                </span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
