// Generated by scripts/port.ts. Hand edits are expected from here on.
import { AppsHeroGrid } from "@/components/pages/apps/hero-grid";
import { ButtonToScroll } from "@/components/pages/apps/button-to-scroll";
export function AppsIntegrations() {
  return (
    <section className="container relative w-full">
      <div className="overflow-hidden border-subtle border-x">
        <div className="pb-24 max-md:pb-16 max-xl:pb-20">
          <div className="grid grid-cols-12">
            <div className="col-[2/-2]">
              <header className="flex w-full flex-col pt-30 pb-15 max-xl:pt-25 max-lg:pt-20 items-center" style={{"--animate-delay":"0ms","--animate-delay-mobile":"0ms"}}>
                <div className="inline-block w-fit rounded-[13px] border border-weak-stroke bg-primary-background px-3 py-1.5 font-medium text-[13px]/[1.4em] text-secondary-foreground mb-6">
                  <h1>
                    {"Apps & integrations"}
                  </h1>
                </div>
                <h2 className="max-w-[15em] text-balance text-heading-responsive-lg text-center">
                  {"One platform, endless possibilities."}
                </h2>
                <p className="mt-4 max-w-xl text-balance text-lg text-secondary-foreground lg:text-xl text-center">
                  {"The tools you already love and new ideas to scale your business."}
                </p>
                <div className="mt-8 flex gap-2 max-md:flex-col">
                  <ButtonToScroll scrollTargetId="apps" className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-primary">
                    {"Browse apps"}
                  </ButtonToScroll>
                  <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline max-md:hidden" href="/partners/app-partners">
                    {"Become an App Partner"}
                  </a>
                  <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-ghost group md:hidden" href="/partners/app-partners">
                    <span>
                      {"Become an App Partner"}
                    </span>
                    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="transition-[translate] duration-400 ease-in-out group-hover:translate-x-px group-hover:duration-150 group-active:translate-x-px group-active:duration-50">
                      <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                    </svg>
                  </a>
                </div>
              </header>
            </div>
          </div>
          <AppsHeroGrid />
        </div>
      </div>
    </section>
  );
}
