// Generated by scripts/port.ts. Hand edits are expected from here on.
import { CtaGrid } from "@/components/pages/apps/cta-grid";
export function BuildWithUs() {
  return (
    <section className="relative w-full overflow-hidden bg-white-200">
      <div className="container">
        <div className="overflow-hidden border-subtle-stroke border-x">
          <div className="py-20">
            <div className="relative grid grid-cols-12">
              <svg width="100%" height="1" className="text-subtle-stroke absolute top-0 -translate-y-1/2">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <svg width="100%" height="1" className="text-subtle-stroke absolute bottom-0 translate-y-1/2">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <div className="col-[2/7] flex flex-col justify-center pr-8 max-lg:col-[2/-2] max-lg:pt-14 max-lg:pb-16">
                <div className="col-[2/-2] text-balance text-heading-responsive-sm">
                  <h2 className="inline">
                    {"Build with us."}
                  </h2>
                  {" "}
                  <p className="inline font-medium text-black-800 text-heading-responsive-sm">
                    {"Develop your own integration for our ecosystem."}
                  </p>
                </div>
                <div className="mt-6 flex gap-2">
                  <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-primary" href="/partners/app-partners">
                    {"Become an App Partner"}
                  </a>
                </div>
              </div>
              <CtaGrid />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
