// Generated by scripts/port.ts. Hand edits are expected from here on.
import { ContextIntro } from "@/components/context/intro";
import { ContextStack } from "@/components/context/stack";
import { ContextReveal } from "@/components/context/reveal";

export function UniversalContext() {
  return (
    <div className="relative isolate">
      <div className="relative z-10">
        <ContextIntro />
        <ContextStack />
      </div>
      <ContextReveal />
    </div>
  );
}
