// Generated by scripts/port.ts. Hand edits are expected from here on.
import { CustomersTabs } from "@/components/customers/customers-tabs";

export function Customers() {
  return (
    <section className="border-subtle-stroke border-t bg-primary-background">
      <div className="container flex flex-1 flex-col max-lg:contents">
        <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none">
          <div className="border-subtle-stroke border-b">
            <div className="grid grid-cols-24 pt-38 max-xl:pt-28 max-lg:pt-22 pb-20 max-xl:pb-18 max-lg:pb-16">
              <div className="col-[3/-3] flex flex-col items-start gap-6 lg:col-[2/-2]">
                <div className="flex flex-col items-start gap-6">
                  <p className="inline-flex h-6 items-center rounded-lg bg-blue-100 px-1.5 font-medium text-[14px] text-blue-600 leading-5 tracking-[-0.14px] dark:bg-blue-800 dark:text-blue-200">
                    {"Customer stories"}
                  </p>
                  <div className="flex flex-col gap-4">
                    <h2 className="max-w-[22em] font-medium text-heading-responsive-md text-primary-foreground text-balance">
                      <span>
                        {"Trusted by 30,000+ customers."}
                        {" "}
                      </span>
                      <br className="hidden md:block" />
                      <span className="text-accent-foreground">
                        {"From first agent to enterprise scale."}
                      </span>
                    </h2>
                  </div>
                </div>
                <div className="shrink-0">
                  <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-8 gap-x-1.5 rounded-[10px] px-2.5 text-xs has-[>svg:last-child,>img:last-child]:pr-1.5 has-[>svg:first-child,>img:first-child]:pl-1.5 button-outline" href="/customers">
                    <span>
                      {"Read more"}
                    </span>
                    <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                      <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                    </svg>
                  </a>
                </div>
              </div>
            </div>
          </div>
          <CustomersTabs />
          <svg width="100%" height="1" className="text-subtle-stroke w-full max-lg:hidden">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
          </svg>
        </div>
      </div>
    </section>
  );
}
