// Generated by scripts/port.ts. Hand edits are expected from here on.
export function Spacer() {
  return (
    <div className="bg-primary-background max-lg:hidden">
      <div className="container flex flex-1 flex-col">
        <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x">
          <div aria-hidden="true" className="grid w-full grid-cols-12 overflow-hidden max-lg:h-25 h-32 max-xl:h-32">
            <div className="col-[2/-2] flex justify-between" />
          </div>
        </div>
      </div>
    </div>
  );
}
