// Generated by scripts/port.ts. Hand edits are expected from here on.
export function PartnerPrograms() {
  return (
    <div className="container">
      <div className="relative isolate border-subtle-stroke border-x">
        <svg width="100%" height="100%" className="text-muted-strong-background mask-t-to-50% absolute inset-0">
          <defs>
            <pattern id="_S_1_" width="10" height="10" patternUnits="userSpaceOnUse">
              <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#_S_1_)" />
        </svg>
        <div className="relative z-20 grid grid-cols-12">
          <div className="relative col-[2/-2]">
            <header className="flex w-full flex-col pt-30 max-xl:pt-25 max-lg:pt-20 items-center pb-24 lg:pb-28 xl:pb-32" style={{"--animate-delay":"0ms","--animate-delay-mobile":"0ms"}}>
              <div className="inline-block w-fit rounded-[13px] border border-weak-stroke bg-primary-background px-3 py-1.5 font-medium text-[13px]/[1.4em] text-secondary-foreground mb-6">
                <h1>
                  {"Partner programs"}
                </h1>
              </div>
              <h2 className="max-w-[15em] text-balance text-heading-responsive-lg text-center">
                {"Partner with us to build the next generation of CRM."}
              </h2>
              <p className="mt-4 max-w-xl text-balance text-lg text-secondary-foreground lg:text-xl text-center">
                {"We work with the best developers, creators, and consultants to power the next era of companies."}
              </p>
            </header>
          </div>
        </div>
      </div>
    </div>
  );
}
