// Generated by scripts/port.ts. Hand edits are expected from here on.
import { AccordionClient, type AccordionClientItem } from "@/components/pages/solutions/shared/accordion-client";

const ITEMS: AccordionClientItem[] = [
  {
    question: "Real-time data for real-time relationships.",
    answer: "Joshuattio’s real-time data sync means you’ll always have the info you need, whenever you need it.",
    image: { src: "/img/img-8c94a383f8.avif", width: 4528, height: 4160 },
    triggerId: "radix-_R_5l2npfiv9f9k7ivb_",
    contentId: "radix-_R_ll2npfiv9f9k7ivb_",
  },
  {
    question: "Custom data tracking.",
    answer: "No deal flow portfolio is alike. Track the data that matters the most to your team.",
    image: { src: "/img/img-37ff3186f0.png", width: 4528, height: 4160 },
    triggerId: "radix-_R_9l2npfiv9f9k7ivb_",
    contentId: "radix-_R_pl2npfiv9f9k7ivb_",
  },
  {
    question: "Tweak to your heart's content.",
    answer: "Intuitive building blocks make it easy to customize every aspect of your pipeline.",
    image: { src: "/img/img-04938fa385.png", width: 4528, height: 4160 },
    triggerId: "radix-_R_dl2npfiv9f9k7ivb_",
    contentId: "radix-_R_tl2npfiv9f9k7ivb_",
  },
];

export function PipelineManagement() {
  return (
    <section className="">
      <div className="container">
        <div className="border-subtle-stroke grid grid-cols-12 gap-x-6 pt-10 lg:pt-16 xl:pt-24 pb-16 lg:pb-24 xl:pb-32">
          <div className="col-span-12 xl:col-start-2 xl:col-end-12">
            <div className="flex flex-col pb-10 lg:pb-16 xl:pb-24">
              <div className="flex flex-col items-start max-w-xl">
                <div className="inline-block w-fit rounded-[13px] border border-weak-stroke bg-primary-background px-3 py-1.5 font-medium text-[13px]/[1.4em] text-secondary-foreground">
                  <h2>
                    {"Pipeline management"}
                  </h2>
                </div>
                <div className="grid grid-cols-10 gap-x-6 gap-y-4 mt-6">
                  <div className="col-span-full">
                    <div>
                      <h2>
                        <strong>
                          {"Easily build the "}
                        </strong>
                      </h2>
                      <h3 className="text-pretty text-heading-responsive-md" />
                      <h2>
                        <strong>
                          {"perfect pipeline."}
                        </strong>
                      </h2>
                    </div>
                  </div>
                  <p className="col-span-full text-pretty text-lg lg:text-xl">
                    {"Craft custom workflows that keep your team agile enough to strike while the iron is hot, every time."}
                  </p>
                </div>
              </div>
            </div>
            <div>
              <AccordionClient items={ITEMS} />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
