// Generated by scripts/port.ts. Hand edits are expected from here on.
export function StartupProgram() {
  return (
    <div className="container">
      <div className="relative isolate border-subtle-stroke border-x">
        <svg width="100%" height="100%" className="text-muted-strong-background mask-t-to-50% absolute inset-0">
          <defs>
            <pattern id="_S_1_" width="10" height="10" patternUnits="userSpaceOnUse">
              <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#_S_1_)" />
        </svg>
        <div className="relative z-20 grid grid-cols-12">
          <div className="relative col-[2/-2]">
            <header className="flex w-full flex-col pt-30 max-xl:pt-25 max-lg:pt-20 items-center pb-24 lg:pb-28 xl:pb-32" style={{"--animate-delay":"0ms","--animate-delay-mobile":"0ms"}}>
              <div className="inline-block w-fit rounded-[13px] border border-weak-stroke bg-primary-background px-3 py-1.5 font-medium text-[13px]/[1.4em] text-secondary-foreground mb-6">
                <h1>
                  {"Startup program"}
                </h1>
              </div>
              <h2 className="max-w-[15em] text-balance text-heading-responsive-lg text-center">
                {"Joshuattio for startups."}
              </h2>
              <p className="mt-4 max-w-xl text-balance text-lg text-secondary-foreground lg:text-xl text-center">
                {"Build on the CRM for the next generation. Get 80% off Joshuattio and benefits to help your startup grow."}
              </p>
              <div className="contents max-xl:hidden">
                <div className="flex w-full max-w-xl mt-12 xl:mt-15 justify-between gap-5">
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="172" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-338673b814.svg" />
                  </div>
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="172" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-f24c7aed92.svg" />
                  </div>
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="172" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-cdccc1683f.svg" />
                  </div>
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-085455e13c.svg" />
                  </div>
                </div>
                <div className="flex w-full max-w-xl mt-2.5 justify-between gap-5">
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-5b71add25e.svg" />
                  </div>
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-e19ee7aa7e.svg" />
                  </div>
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-68ebdf05c6.svg" />
                  </div>
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-5c70227ca2.svg" />
                  </div>
                </div>
              </div>
              <div className="contents xl:hidden">
                <div className="flex w-full max-w-xl mt-12 xl:mt-15 justify-between gap-5">
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="172" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-338673b814.svg" />
                  </div>
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="172" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-f24c7aed92.svg" />
                  </div>
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="172" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-cdccc1683f.svg" />
                  </div>
                </div>
                <div className="flex w-full max-w-xl mt-2.5 justify-between gap-5">
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-085455e13c.svg" />
                  </div>
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-5b71add25e.svg" />
                  </div>
                  <div className="flex h-10 items-center justify-center">
                    <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full object-fit" style={{"color":"transparent"}} src="/img/img-e19ee7aa7e.svg" />
                  </div>
                </div>
              </div>
            </header>
          </div>
        </div>
      </div>
    </div>
  );
}
