// Generated by scripts/port.ts. Hand edits are expected from here on.
import "./startups.css";

export function TheCrmThatGrows() {
  return (
    <section className="container">
      <div className="border-subtle-stroke border-x">
        <header className="grid grid-cols-12 pt-40 pb-20 max-xl:pt-30 max-xl:pb-16 max-lg:pt-25 max-lg:pb-15 justify-items-start">
          <div className="max-w-[20em] text-pretty text-heading-responsive-sm text-start col-[2/-2] mix-blend-multiply dark:mix-blend-screen">
            <h2 className="text-pretty inline">
              {"The CRM that grows as fast as you do."}
            </h2>
            {" "}
            <p className="inline text-pretty font-medium text-black-800">
              {"Joshuattio is the agentic CRM built for how startups actually work: flexible enough to fit your motion today, powerful enough to scale with you tomorrow."}
            </p>
          </div>
        </header>
        <div className="relative grid grid-cols-12">
          <div aria-hidden="true" className="grid w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25 absolute -top-5 h-5">
            <div className="col-[2/-2] flex justify-between">
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
          </div>
          <svg width="100%" height="1" className="text-subtle-stroke absolute top-0">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
          </svg>
          <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
            <defs>
              <pattern id="_S_2_" width="10" height="10" patternUnits="userSpaceOnUse">
                <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#_S_2_)" />
          </svg>
          <div className="relative col-[2/-2]">
            <div className="grid grid-cols-2 gap-px bg-subtle-stroke p-px max-lg:grid-cols-1">
              <div className="grid grid-cols-12 bg-primary-background" style={{"order":"1"}}>
                <div className="col-[2/-2] py-10">
                  <div className="text-overline">
                    {"[0"}
                    {"1"}
                    {"]"}
                  </div>
                  <div className="relative mt-8 mb-9 aspect-[5/3] w-full">
                    <img alt="" loading="eager" width="1883" height="536" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-09cc47589c.avif 1x, /img/img-09cc47589c.avif 2x" src="/img/img-09cc47589c.avif" />
                  </div>
                  <h3 className="font-semibold text-lg text-secondary-foreground lg:max-xl:text-base max-md:text-base">
                    {"Ask Joshuattio. Get answers."}
                  </h3>
                  <p className="mt-1 max-w-[24em] text-balance text-accent-foreground lg:max-xl:text-sm max-md:text-sm">
                    {"Search, update, and create with AI."}
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-12 bg-primary-background" style={{"order":"2"}}>
                <div className="col-[2/-2] py-10">
                  <div className="text-overline">
                    {"[0"}
                    {"2"}
                    {"]"}
                  </div>
                  <div className="relative mt-8 mb-9 aspect-[5/3] w-full">
                    <img alt="" loading="eager" width="1856" height="956" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-510cb29082.avif 1x, /img/img-510cb29082.avif 2x" src="/img/img-510cb29082.avif" />
                  </div>
                  <h3 className="font-semibold text-lg text-secondary-foreground lg:max-xl:text-base max-md:text-base">
                    {"Built around your business."}
                  </h3>
                  <p className="mt-1 max-w-[24em] text-balance text-accent-foreground lg:max-xl:text-sm max-md:text-sm">
                    {"No rigid templates. No workarounds."}
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-12 bg-primary-background" style={{"order":"4"}}>
                <div className="col-[2/-2] py-10">
                  <div className="text-overline">
                    {"[0"}
                    {"3"}
                    {"]"}
                  </div>
                  <div className="relative mt-8 mb-9 aspect-[5/3] w-full">
                    <img alt="" loading="eager" width="1776" height="1136" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-b6af0924b0.avif 1x, /img/img-b6af0924b0.avif 2x" src="/img/img-b6af0924b0.avif" />
                  </div>
                  <h3 className="font-semibold text-lg text-secondary-foreground lg:max-xl:text-base max-md:text-base">
                    {"Up and running in minutes."}
                  </h3>
                  <p className="mt-1 max-w-[24em] text-balance text-accent-foreground lg:max-xl:text-sm max-md:text-sm">
                    {"Sync your email and calendar immediately. "}
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-12 bg-primary-background" style={{"order":"5"}}>
                <div className="col-[2/-2] py-10">
                  <div className="text-overline">
                    {"[0"}
                    {"4"}
                    {"]"}
                  </div>
                  <div className="relative mt-8 mb-9 aspect-[5/3] w-full">
                    <img alt="" loading="eager" width="2096" height="988" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-9c0cfb3ef3.avif 1x" src="/img/img-9c0cfb3ef3.avif" />
                  </div>
                  <h3 className="font-semibold text-lg text-secondary-foreground lg:max-xl:text-base max-md:text-base">
                    {"From zero to IPO."}
                  </h3>
                  <p className="mt-1 max-w-[24em] text-balance text-accent-foreground lg:max-xl:text-sm max-md:text-sm">
                    {"Built to scale with you."}
                  </p>
                </div>
              </div>
              <div className="relative order-3 col-[1/-1] grid grid-cols-12 bg-primary-background max-lg:order-6">
                <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
                  <defs>
                    <pattern id="_S_3_" width="10" height="10" patternUnits="userSpaceOnUse">
                      <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
                    </pattern>
                  </defs>
                  <rect width="100%" height="100%" fill="url(#_S_3_)" />
                </svg>
                <div className="relative col-[2/-2] flex flex-col items-center py-32 text-center">
                  <p className="max-w-[20em] text-pretty text-quote-responsive">
                    {"When I first opened Joshuattio, I "}
                    <span className="startups-quote-trim">{"instantly "}</span>
                    {"got the feeling that this was the start of the next generation of CRM."}
                  </p>
                  <p className="mt-10 font-semibold text-secondary-foreground text-sm">
                    {"Margaret Shen"}
                  </p>
                  <p className="mt-1 text-secondary-foreground text-sm">
                    {"Head of Business Operations · Modal"}
                  </p>
                </div>
              </div>
            </div>
          </div>
          <svg width="100%" height="1" className="text-subtle-stroke absolute bottom-0">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
          </svg>
        </div>
        <div aria-hidden="true" className="grid h-40 w-full overflow-hidden max-xl:h-30 max-lg:h-25 grid-cols-12">
          <div className="col-[2/-2] flex justify-between">
            <svg width="1" height="100%" className="text-subtle-stroke">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
            <svg width="1" height="100%" className="text-subtle-stroke">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
          </div>
        </div>
      </div>
    </section>
  );
}
