// Generated by scripts/port.ts. Hand edits are expected from here on.
import { ToolsOrbit } from "./tools-orbit";

export function TheToolsYouRe() {
  return (
    <div className="container flex flex-1 flex-col">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x">
        <div className="relative overflow-hidden bg-secondary-background">
          <header className="grid grid-cols-12">
            <div className="relative col-[2/-2] flex flex-col items-center">
              <header className="grid grid-cols-12 pt-40 pb-20 max-xl:pt-30 max-xl:pb-16 max-lg:pt-25 max-lg:pb-15 justify-items-center text-center text-xl lg:pt-20 lg:pb-12">
                <div className="col-[2/-2]">
                  <h2 className="text-balance font-semibold">
                    {"The tools you’re already building with. At a fraction of the cost."}
                  </h2>
                  <p className="mt-1 text-balance text-accent-foreground">
                    {"Approved startups get access to perks from the products powering the best teams, including Linear, Notion, Intercom, and more."}
                  </p>
                </div>
              </header>
            </div>
          </header>
          <ToolsOrbit />
        </div>
      </div>
    </div>
  );
}
