// Generated by scripts/port.ts. Hand edits are expected from here on.
import { FaqItem, FaqRoot } from "@/components/pages/pricing/faq-accordion";

const FAQ_IDS = ["is-joshuattio-the-right-fit-if-we-dont-have-a-sales-team-yet","can-i-switch-to-joshuattio-if-im-already-on-hubspot-or-salesforce","what-perks-do-startup-program-members-get-access-to","who-is-eligible-for-the-joshuattio-startup-program","what-happens-when-i-apply","ive-already-created-an-joshuattio-workspace-can-i-still-apply","does-joshuattio-have-an-api-or-mcp-server","does-joshuattio-integrate-with-the-tools-were-already-using","what-is-an-agentic-crm"];

export function FrequentlyAskedQuestions() {
  return (
    <div className="container flex flex-1 flex-col">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x">
        <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
          <div className="col-[2/-2] flex justify-between" />
        </div>
        <div className="grid grid-cols-12">
          <div className="space-y-4 lg:space-y-6 col-[2/-2] lg:col-[3/-3] xl:col-[4/-4]">
            <h2 id="faq" className="pr-6 text-heading-responsive-md text-secondary-foreground">
              {"Frequently asked questions"}
            </h2>
            <div>
              <FaqRoot questions={FAQ_IDS}>
                <FaqItem id="is-joshuattio-the-right-fit-if-we-dont-have-a-sales-team-yet" index={0} triggerId="base-ui-_R_2mllfiv9f9k7ivbH2_" panelId="base-ui-_R_2mllfiv9f9k7ivbH1_" question={"Is Joshuattio right if we don't have a sales team yet?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"A lot of early-stage founders are using CRM as a founder-led sales tool. Joshuattio works just as well for a founder managing relationships solo as it does for a full GTM team. Many of our startup customers start with one or two users and scale up as they grow."}
                      </p>
                    </div>
                  </div>
                </FaqItem>
                <FaqItem id="can-i-switch-to-joshuattio-if-im-already-on-hubspot-or-salesforce" index={1} triggerId="base-ui-_R_4mllfiv9f9k7ivbH2_" panelId="base-ui-_R_4mllfiv9f9k7ivbH1_" question={"Can I switch to Joshuattio if I'm already on HubSpot or Salesforce?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"Yes. Joshuattio makes it straightforward to migrate your data from HubSpot, Salesforce, Pipedrive, "}
                        <a href="/help/reference/imports-exports/migrate-data-from-another-crm" className="-mx-px rounded-sm px-px underline transition-colors duration-400 hover:duration-150 active:duration-50 text-link-foreground decoration-transparent hover:text-link-strong-foreground hover:decoration-link-strong-foreground active:text-link-strong-foreground">
                          {"and more"}
                        </a>
                        {". Most teams are up and running in a matter of hours, not weeks."}
                      </p>
                    </div>
                  </div>
                </FaqItem>
                <FaqItem id="what-perks-do-startup-program-members-get-access-to" index={2} triggerId="base-ui-_R_6mllfiv9f9k7ivbH2_" panelId="base-ui-_R_6mllfiv9f9k7ivbH1_" question={"What perks do Startup Program members get access to?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"Members get exclusive deals on tools built for high-growth startups. That includes discounts on products like Mercury, Linear, Notion, Intercom, Sentry, Apollo, Miro, and more. You can browse the full catalogue once you're in the program."}
                      </p>
                    </div>
                  </div>
                </FaqItem>
                <FaqItem id="who-is-eligible-for-the-joshuattio-startup-program" index={3} triggerId="base-ui-_R_8mllfiv9f9k7ivbH2_" panelId="base-ui-_R_8mllfiv9f9k7ivbH1_" question={"Who is eligible for the Joshuattio startup program?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"Startups that meet all the following criteria: VC-backed, signed up within the last 90 days, and incorporated less than 10 years ago."}
                      </p>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"This discount is valid for workspaces of up to 10 seats."}
                      </p>
                    </div>
                  </div>
                </FaqItem>
                <FaqItem id="what-happens-when-i-apply" index={4} triggerId="base-ui-_R_amllfiv9f9k7ivbH2_" panelId="base-ui-_R_amllfiv9f9k7ivbH1_" question={"What happens when I apply?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"A member of our team will be in touch to confirm your eligibility and get you started. "}
                      </p>
                    </div>
                  </div>
                </FaqItem>
                <FaqItem id="ive-already-created-an-joshuattio-workspace-can-i-still-apply" index={5} triggerId="base-ui-_R_cmllfiv9f9k7ivbH2_" panelId="base-ui-_R_cmllfiv9f9k7ivbH1_" question={"I already created a Joshuattio workspace, can I still apply?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"Yes, you can apply within your first 90 days of creating a workspace."}
                      </p>
                    </div>
                  </div>
                </FaqItem>
                <FaqItem id="does-joshuattio-have-an-api-or-mcp-server" index={6} triggerId="base-ui-_R_emllfiv9f9k7ivbH2_" panelId="base-ui-_R_emllfiv9f9k7ivbH1_" question={"Does Joshuattio have an API or MCP server?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"Yes to both. Joshuattio has a REST API, an App SDK, and an MCP server, so you can connect your GTM stack, build custom automations, or plug Joshuattio directly into AI coding agents and automation tools. It's all documented at "}
                        <a href="/platform/developers" className="-mx-px rounded-sm px-px underline transition-colors duration-400 hover:duration-150 active:duration-50 text-link-foreground decoration-transparent hover:text-link-strong-foreground hover:decoration-link-strong-foreground active:text-link-strong-foreground">
                          {"joshuattio.com/platform/developers"}
                        </a>
                        {"."}
                      </p>
                    </div>
                  </div>
                </FaqItem>
                <FaqItem id="does-joshuattio-integrate-with-the-tools-were-already-using" index={7} triggerId="base-ui-_R_gmllfiv9f9k7ivbH2_" panelId="base-ui-_R_gmllfiv9f9k7ivbH1_" question={"Does Joshuattio work with the tools we're already using?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"Yes, Joshuattio connects with the tools most early-stage teams already run on. That includes Clay, Slack, Granola, Zapier, Gmail, Google Calendar, and more. You can browse the full app store at "}
                        <a href="/apps" className="-mx-px rounded-sm px-px underline transition-colors duration-400 hover:duration-150 active:duration-50 text-link-foreground decoration-transparent hover:text-link-strong-foreground hover:decoration-link-strong-foreground active:text-link-strong-foreground">
                          {"joshuattio.com/apps"}
                        </a>
                        {". If you need something custom, the "}
                        <a href="/platform/developers" className="-mx-px rounded-sm px-px underline transition-colors duration-400 hover:duration-150 active:duration-50 text-link-foreground decoration-transparent hover:text-link-strong-foreground hover:decoration-link-strong-foreground active:text-link-strong-foreground">
                          {"API and SDK"}
                        </a>
                        {" are there too."}
                      </p>
                    </div>
                  </div>
                </FaqItem>
                <FaqItem id="what-is-an-agentic-crm" index={8} triggerId="base-ui-_R_imllfiv9f9k7ivbH2_" panelId="base-ui-_R_imllfiv9f9k7ivbH1_" question={"What is an agentic CRM?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"An agentic CRM is a CRM that uses AI natively, not as a bolt-on. Joshuattio is built this way from the ground up: AI that researches and enriches records, surfaces signals, automates outreach, and lets you search and update your CRM in plain language."}
                      </p>
                    </div>
                  </div>
                </FaqItem>
              </FaqRoot>
            </div>
          </div>
        </div>
        <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
          <div className="col-[2/-2] flex justify-between" />
        </div>
      </div>
    </div>
  );
}
