// Generated by scripts/port.ts. Hand edits are expected from here on.
export function PrivacyPolicy() {
  return (
    <h1 className="max-w-5xl text-heading-lg [text-wrap:balance]">
      {"Privacy Policy"}
    </h1>
  );
}
