// Generated by scripts/port.ts. Hand edits are expected from here on.
export function Block() {
  return (
    <p className="mt-5 max-w-2xl text-secondary-foreground text-xl [text-wrap:balance]">
      {"Joshuattio takes data privacy seriously. We are committed to handling data privacy transparently and in line with data protection principles and relevant regulations. Find out more in our Privacy Policy below."}
    </p>
  );
}
