// Generated by scripts/port.ts. Hand edits are expected from here on.
import { AppGallery } from "@/components/pages/apps/detail/app-gallery";
export function Slack() {
  return (
    <div className="container">
      <div className="border-subtle-stroke border-x">
        <article>
          <aside className="relative grid h-28 grid-cols-12 items-end pb-5">
            <svg width="1" height="100%" className="text-subtle-stroke absolute col-[-2] max-lg:hidden">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
            <p className="col-2 whitespace-nowrap text-overline">
              <a className="transition-colors hover:text-accent-foreground active:text-tertiary-foreground active:duration-0" href="/apps">
                {"Apps"}
              </a>
              {" "}
              {"/ "}
              <span className="text-black-800">
                {"Slack"}
              </span>
            </p>
            <p className="col-[-2] justify-self-center whitespace-nowrap text-overline max-lg:col-[-3] max-lg:justify-self-end">
              {"[V"}
              {"1.22"}
              {"]"}
            </p>
          </aside>
          <svg width="100%" height="1" className="text-subtle-stroke">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
          </svg>
          <header className="relative grid grid-cols-12 py-12">
            <svg width="1" height="100%" className="text-subtle-stroke absolute col-[-2] max-lg:hidden">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
            <svg width="100%" height="100%" className="text-muted-strong-background absolute col-[-2] max-lg:hidden">
              <defs>
                <pattern id="_S_1_" width="10" height="10" patternUnits="userSpaceOnUse">
                  <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
                </pattern>
              </defs>
              <rect width="100%" height="100%" fill="url(#_S_1_)" />
            </svg>
            <div className="col-[2/-2] flex gap-6">
              <div className="grid grid-cols-[auto_1fr] items-center gap-x-5 max-lg:gap-x-4">
                <div className="relative size-21 overflow-hidden rounded-[30%] max-lg:size-16" style={{"boxShadow":"0px 1px 1px -0.5px rgba(28, 40, 64, 0.06),0px 2px 2px -1px rgba(28, 40, 64, 0.08),0px 4px 4px -2px rgba(28, 40, 64, 0.06),0px 8px 8px -4px rgba(28, 40, 64, 0.06)"}}>
                  <img alt="Slack" width="92" height="92" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-ff043b2ce9.avif 1x, /img/img-ff043b2ce9.avif 2x" src="/img/img-ff043b2ce9.avif" />
                  <div className="absolute inset-0 rounded-[inherit] shadow-[inset_0_0_0_1px] shadow-black-100/10" />
                </div>
                <h1 className="font-semibold text-heading-responsive-lg max-xs:col-span-full max-xs:mt-4">
                  {"Slack"}
                </h1>
                <p className="col-2 max-w-[28em] text-balance pt-3 pb-7 text-xl max-lg:col-span-full max-lg:max-w-full max-lg:pt-7 max-lg:pb-8 max-lg:text-base max-md:pt-6 max-md:pb-7">
                  {"Ask anything and trigger workflows from Slack"}
                </p>
                <div className="col-2 flex flex-col gap-2 lg:col-[2/6] max-lg:col-span-full">
                  <a href="/_/settings/apps/slack" target="_blank" rel="noopener noreferrer" className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-primary lg:w-fit">
                    {"Install app"}
                  </a>
                </div>
              </div>
            </div>
          </header>
          <svg width="100%" height="1" className="text-subtle-stroke max-xl:hidden">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
          </svg>
          <div className="relative grid h-12 grid-cols-12 max-xl:hidden">
            <svg width="1" height="100%" className="text-subtle-stroke col-4">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
            <svg width="1" height="100%" className="text-subtle-stroke col-[-2]">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
          </div>
          <svg width="100%" height="1" className="text-subtle-stroke">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
          </svg>
          <div className="relative flex flex-col lg:grid lg:grid-cols-12">
            <svg width="1" height="100%" className="text-subtle-stroke absolute col-4 max-lg:hidden">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
            </svg>
            <aside className="relative bg-secondary-background lg:col-[1/4]">
              <div className="sticky top-[calc(var(--site-header-height))] grid grid-cols-12 py-16 lg:py-22">
                <div className="col-[3/-3] flex flex-col items-start gap-x-4 gap-y-6 sm:max-lg:grid sm:max-lg:grid-cols-2 max-lg:col-[2/-2]">
                  <div className="-ml-2 flex w-fit items-center gap-2 rounded-[10px] border border-subtle-stroke py-1 pr-2.5 pl-2 text-tertiary-foreground max-lg:col-span-full">
                    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="size-3.5 shrink-0 text-green-500">
                      <path d="M6.20801 1.34399C6.63641 0.885598 7.36357 0.885598 7.79199 1.34399L8.53027 2.13403C8.74384 2.36249 9.04585 2.48724 9.3584 2.47681L10.4395 2.44067C11.0663 2.4197 11.5798 2.93384 11.5586 3.56079L11.5234 4.64087C11.5129 4.95363 11.6376 5.25631 11.8662 5.46997L12.6562 6.20825C13.1143 6.63654 13.1141 7.36281 12.6562 7.79126L11.8662 8.53052C11.6377 8.7441 11.5129 9.04605 11.5234 9.35864L11.5586 10.4397C11.5797 11.0666 11.0663 11.5807 10.4395 11.5598L9.3584 11.5227C9.04582 11.5123 8.74383 11.638 8.53027 11.8665L7.79199 12.6565C7.36359 13.1148 6.63639 13.1148 6.20801 12.6565L5.46973 11.8665C5.25615 11.638 4.95418 11.5123 4.6416 11.5227L3.56152 11.5598C2.93452 11.581 2.42031 11.0668 2.44141 10.4397L2.47754 9.35864C2.48797 9.04605 2.36228 8.74409 2.13379 8.53052L1.34375 7.79126C0.885964 7.36284 0.885757 6.63655 1.34375 6.20825L2.13379 5.46997C2.3624 5.25629 2.4881 4.95363 2.47754 4.64087L2.44141 3.56079C2.42022 2.93371 2.93446 2.41948 3.56152 2.44067L4.6416 2.47681C4.95412 2.48725 5.25615 2.36245 5.46973 2.13403L6.20801 1.34399ZM9.29102 5.09302C9.06634 4.93254 8.7533 4.9846 8.59277 5.20923L6.68848 7.87622C6.59009 8.01335 6.38652 8.01519 6.28516 7.88013L5.40039 6.70044C5.23478 6.47963 4.92109 6.43444 4.7002 6.59985C4.47948 6.76548 4.43423 7.07919 4.59961 7.30005L5.48535 8.48071C5.99258 9.15672 7.01046 9.14475 7.50195 8.45728L9.40723 5.79126C9.5677 5.5666 9.51561 5.25355 9.29102 5.09302Z" fill="currentColor" />
                    </svg>
                    <span className="text-sm">
                      {"Official app"}
                    </span>
                  </div>
                  <div className="flex flex-col gap-1.5">
                    <h3 className="truncate font-semibold text-secondary-foreground">
                      {"Built by"}
                    </h3>
                    <div className="-ml-0.5 flex items-center gap-1.5">
                      <div className="relative size-4.5 overflow-hidden rounded-[30%]">
                        <img alt="Joshuattio" loading="lazy" width="512" height="512" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} src="/img/img-0ff25a1b03.png" />
                        <div className="absolute inset-0 rounded-[inherit] shadow-[inset_0_0_0_1px] shadow-black-100/10" />
                      </div>
                      <p className="truncate text-sm text-tertiary-foreground">
                        {"Joshuattio"}
                      </p>
                    </div>
                  </div>
                  <div className="flex flex-col gap-1.5">
                    <h3 className="truncate font-semibold text-secondary-foreground">
                      {"Category"}
                    </h3>
                    <a className="group flex items-center text-tertiary-foreground" href="/apps#automations">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="size-3.5 shrink-0">
                        <path d="M3.80469 1.13867C4.18661 1.10126 4.55892 1.2251 4.93945 1.40527C5.32254 1.58669 5.79059 1.86365 6.375 2.20898L10.2578 4.50293C10.8248 4.83799 11.2802 5.10682 11.6152 5.34863C11.9487 5.5893 12.23 5.8495 12.3818 6.19434C12.6078 6.7077 12.6078 7.2923 12.3818 7.80566C12.23 8.15046 11.9487 8.41071 11.6152 8.65137C11.2802 8.89318 10.8248 9.16201 10.2578 9.49707L6.375 11.791C5.79059 12.1363 5.32253 12.4133 4.93945 12.5947C4.55894 12.7749 4.1866 12.8987 3.80469 12.8613C3.23797 12.8057 2.72189 12.5114 2.38574 12.0518C2.15925 11.742 2.07656 11.3587 2.03809 10.9395C1.99936 10.5173 2 9.97299 2 9.29395V4.70605C2 4.02701 1.99937 3.48274 2.03809 3.06055C2.07655 2.64131 2.15927 2.25801 2.38574 1.94824C2.72189 1.48856 3.23795 1.1943 3.80469 1.13867ZM3.90234 2.13379C3.61899 2.16161 3.36045 2.30826 3.19238 2.53809C3.12978 2.62375 3.068 2.78315 3.03418 3.15137C3.00064 3.51703 3 4.00721 3 4.70605V9.29395C3 9.9928 3.00063 10.483 3.03418 10.8486C3.06801 11.2169 3.12976 11.3763 3.19238 11.4619C3.36045 11.6917 3.619 11.8384 3.90234 11.8662C4.00798 11.8766 4.17718 11.8498 4.51172 11.6914C4.84353 11.5343 5.26478 11.2851 5.86621 10.9297L9.74902 8.63574C10.3329 8.29071 10.7412 8.04942 11.0303 7.84082C11.3206 7.63129 11.4242 7.49987 11.4668 7.40332C11.5799 7.14655 11.5799 6.85345 11.4668 6.59668C11.4242 6.50013 11.3206 6.36874 11.0303 6.15918C10.7412 5.95057 10.3329 5.7093 9.74902 5.36426L5.86621 3.07031C5.26477 2.71492 4.84353 2.46573 4.51172 2.30859C4.17715 2.15018 4.00798 2.12344 3.90234 2.13379Z" fill="currentColor" />
                      </svg>
                      <p className="mr-1.5 ml-2 truncate text-sm">
                        {"Automations"}
                      </p>
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="shrink-0 -translate-x-0.25 opacity-0 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                        <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                      </svg>
                    </a>
                  </div>
                  <div className="flex flex-col gap-1.5 max-lg:col-span-full">
                    <h3 className="font-semibold text-secondary-foreground">
                      {"Resources"}
                    </h3>
                    <div className="flex flex-col gap-2 text-tertiary-foreground">
                      <a className="group relative flex w-full items-center text-sm text-tertiary-foreground" href="https://slack.com/" rel="noreferrer" target="_blank">
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="size-3.5 shrink-0">
                          <path d="M7.33496 0.508789C10.7691 0.68312 13.5 3.52253 13.5 7C13.5 10.5899 10.5899 13.5 7 13.5C3.41015 13.5 0.5 10.5899 0.5 7C0.50004 3.41018 3.41017 0.5 7 0.5L7.33496 0.508789ZM5.01074 7.5C5.06064 8.90329 5.31622 10.1457 5.69336 11.0508C5.90445 11.5573 6.14339 11.9347 6.38281 12.1777C6.62056 12.4191 6.829 12.5 7 12.5C7.171 12.5 7.37944 12.4191 7.61719 12.1777C7.85661 11.9347 8.09555 11.5573 8.30664 11.0508C8.68378 10.1457 8.93936 8.90329 8.98926 7.5H5.01074ZM1.52344 7.5C1.71859 9.6655 3.16823 11.4682 5.14062 12.1768C5.00501 11.9495 4.88126 11.7004 4.77051 11.4346C4.33478 10.3886 4.06096 9.01117 4.01074 7.5H1.52344ZM9.98926 7.5C9.93904 9.01117 9.66522 10.3886 9.22949 11.4346C9.11867 11.7005 8.99412 11.9494 8.8584 12.1768C10.8312 11.4684 12.2814 9.66582 12.4766 7.5H9.98926ZM5.14062 1.82227C3.1681 2.53071 1.71865 4.33443 1.52344 6.5H4.01074C4.06096 4.98883 4.33478 3.61136 4.77051 2.56543C4.88137 2.29935 5.00484 2.04974 5.14062 1.82227ZM7 1.5C6.829 1.5 6.62056 1.58092 6.38281 1.82227C6.14339 2.06534 5.90445 2.44265 5.69336 2.94922C5.31622 3.85435 5.06064 5.09671 5.01074 6.5H8.98926C8.93936 5.09671 8.68378 3.85435 8.30664 2.94922C8.09555 2.44265 7.85661 2.06534 7.61719 1.82227C7.37944 1.58092 7.171 1.5 7 1.5ZM8.8584 1.82227C8.99429 2.04986 9.11856 2.29918 9.22949 2.56543C9.66522 3.61136 9.93904 4.98883 9.98926 6.5H12.4766C12.2813 4.33411 10.8314 2.53049 8.8584 1.82227Z" fill="currentColor" />
                        </svg>
                        <p className="mr-1.5 ml-2 truncate">
                          {"Website"}
                        </p>
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="shrink-0 -translate-x-0.25 opacity-0 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50 -rotate-45">
                          <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                        </svg>
                      </a>
                      <a className="group relative flex w-full items-center text-sm text-tertiary-foreground" href="/help/apps/automations-apps/slack-app">
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="size-3.5 shrink-0">
                          <path d="M4.54883 1.5C5.50772 1.5 6.39919 1.92803 7 2.63965C7.60084 1.92804 8.49228 1.50005 9.45117 1.5H12.5C13.3284 1.50008 14 2.17162 14 3V10.5C14 11.3284 13.3284 11.9999 12.5 12H9.40137C8.57118 12 7.81335 12.4737 7.44922 13.2197L7.44727 13.2188C7.36593 13.3847 7.19731 13.5 7 13.5C6.80254 13.5 6.63302 13.3849 6.55176 13.2188L6.55078 13.2197C6.18674 12.4737 5.42875 12 4.59863 12H1.5C0.671573 12 0 11.3284 0 10.5V3C0 2.17157 0.671573 1.5 1.5 1.5H4.54883ZM1.5 2.5C1.22386 2.5 1 2.72386 1 3V10.5C1 10.7761 1.22386 11 1.5 11H4.59863C5.29776 11 5.9615 11.23 6.5 11.6338V3.67578C6.11862 2.9554 5.36958 2.5 4.54883 2.5H1.5ZM9.45117 2.5C8.63042 2.50006 7.88143 2.95542 7.5 3.67578V11.6338C8.0385 11.23 8.70218 11 9.40137 11H12.5C12.7761 10.9999 13 10.7761 13 10.5V3C13 2.72391 12.7761 2.50008 12.5 2.5H9.45117ZM10.5 8C10.7761 8 11 8.22386 11 8.5C11 8.77614 10.7761 9 10.5 9H9C8.72386 9 8.5 8.77614 8.5 8.5C8.5 8.22386 8.72386 8 9 8H10.5ZM11.5 6C11.7761 6 12 6.22386 12 6.5C12 6.77614 11.7761 7 11.5 7H9C8.72386 7 8.5 6.77614 8.5 6.5C8.5 6.22386 8.72386 6 9 6H11.5Z" fill="currentColor" />
                        </svg>
                        <p className="mr-1.5 ml-2 truncate">
                          {"Documentation"}
                        </p>
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="shrink-0 -translate-x-0.25 opacity-0 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                          <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                        </svg>
                      </a>
                      <a className="group relative flex w-full items-center text-sm text-tertiary-foreground" href="mailto:support@joshuattio.com">
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="size-3.5 shrink-0">
                          <path d="M5.73096 0.624512C6.99163 0.373748 8.29925 0.502854 9.48682 0.994629C10.6743 1.48648 11.6896 2.31962 12.4038 3.38818C13.1158 4.45372 13.4961 5.70646 13.4985 6.98779C13.4986 6.9917 13.5005 6.99558 13.5005 6.99951V8.49951C13.5005 9.60393 12.6048 10.4993 11.5005 10.4995C10.6713 10.4995 9.95893 9.99568 9.65576 9.27686C9.01386 10.0249 8.0625 10.4995 6.99951 10.4995C5.06673 10.4993 3.49951 8.93235 3.49951 6.99951C3.49977 5.06689 5.06689 3.49977 6.99951 3.49951C7.97918 3.49951 8.86518 3.90261 9.50049 4.55127V4.49951C9.50074 4.22358 9.7245 3.99951 10.0005 3.99951C10.2763 3.99976 10.5002 4.22373 10.5005 4.49951V8.49951C10.5005 9.0518 10.9482 9.49951 11.5005 9.49951C12.0526 9.49926 12.5005 9.05164 12.5005 8.49951L12.4995 6.99951C12.4994 5.9119 12.177 4.84818 11.5728 3.94385C10.9684 3.03964 10.1088 2.33466 9.104 1.91846C8.0992 1.50241 6.99292 1.39281 5.92627 1.60498C4.85959 1.81727 3.87989 2.34179 3.11084 3.11084C2.34179 3.87989 1.81727 4.85959 1.60498 5.92627C1.39281 6.99292 1.50241 8.0992 1.91846 9.104C2.33466 10.1088 3.03964 10.9684 3.94385 11.5728C4.84818 12.177 5.9119 12.4994 6.99951 12.4995C7.2755 12.4995 7.49926 12.7236 7.49951 12.9995C7.49951 13.2757 7.27565 13.4995 6.99951 13.4995C5.7141 13.4994 4.45697 13.118 3.38818 12.4038C2.31962 11.6896 1.48648 10.6743 0.994629 9.48682C0.502854 8.29925 0.373748 6.99163 0.624512 5.73096C0.875423 4.4704 1.49399 3.31167 2.40283 2.40283C3.31167 1.49399 4.4704 0.875423 5.73096 0.624512ZM6.99951 4.49951C5.61917 4.49977 4.49977 5.61917 4.49951 6.99951C4.49951 8.38007 5.61902 9.49926 6.99951 9.49951C8.38022 9.49951 9.49951 8.38022 9.49951 6.99951C9.49926 5.61902 8.38007 4.49951 6.99951 4.49951Z" fill="currentColor" />
                        </svg>
                        <p className="mr-1.5 ml-2 truncate">
                          {"Support"}
                        </p>
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="shrink-0 -translate-x-0.25 opacity-0 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                          <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                        </svg>
                      </a>
                    </div>
                  </div>
                  <a href="/_/settings/apps/slack" target="_blank" rel="noreferrer" className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 button-outline max-lg:hidden">
                    {"Install app"}
                  </a>
                </div>
              </div>
              <svg width="100%" height="1" className="text-subtle-stroke absolute bottom-0 col-span-12 lg:hidden">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
              </svg>
            </aside>
            <div className="col-start-4 col-end-13 overflow-x-hidden py-20">
              <div className="relative grid grid-cols-12 items-center">
                <div className="relative col-[2/-2] flex flex-col gap-y-18">
                  <AppGallery images={[{ src: "/img/img-3931b16824.avif", thumb: "/img/img-3931b16824.avif" }, { src: "/img/img-3586c6dbbe.avif", thumb: "/img/img-2d411727a3.avif" }, { src: "/img/img-9891e50581.avif", thumb: "/img/img-8d2f792c2e.avif" }]} />
                  <div>
                    <h2 className="relative not-first:mt-10 not-last:mb-5 font-semibold text-2xl text-primary-foreground lg:not-first:mt-12">
                      {"Overview"}
                    </h2>
                    <div className="max-w-prose font-normal">
                      <p className="not-first:mt-[13px] text-pretty text-secondary-foreground leading-[26px]">
                        {"Connect Joshuattio to Slack and bring your AI CRM wherever your team works. Ask Joshuattio anything (research accounts, review pipeline, surface customer insights) directly from a DM or channel mention. Set up automated notifications for updates like closed deals or new signups, and post interactive actions so your team can trigger follow-up workflows in Slack."}
                      </p>
                    </div>
                    <h2 className="relative not-first:mt-10 not-last:mb-5 font-semibold text-2xl text-primary-foreground lg:not-first:mt-12">
                      {"How it works"}
                    </h2>
                    <div className="max-w-prose font-normal">
                      <p className="not-first:mt-[13px] text-pretty text-secondary-foreground leading-[26px]">
                        <strong className="font-semibold">
                          {"Ask Joshuattio in Slack"}
                        </strong>
                      </p>
                      <ul className="not-first:mt-1.5 list-[square] pl-3.5 marker:text-caption-foreground">
                        <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                          {"Ask Joshuattio via DM or mention @joshuattio in a channel."}
                        </li>
                        <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                          {"Run account research across your records, emails, notes, and connected tools, so you can find exactly what you need in seconds."}
                        </li>
                        <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                          {"Ask Joshuattio to update records with context from Slack."}
                        </li>
                        <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                          {"Review deals and check pipeline health, so you know where things stand and where to act."}
                        </li>
                        <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                          {"Surface customer insights from calls, emails, and past conversations."}
                        </li>
                      </ul>
                      <p className="not-first:mt-[13px] text-pretty text-secondary-foreground leading-[26px]">
                        <strong className="font-semibold">
                          {"Automate workflows"}
                        </strong>
                      </p>
                      <ul className="not-first:mt-1.5 list-[square] pl-3.5 marker:text-caption-foreground">
                        <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                          {"Send notifications for updates, like deals closing or new signups, to Slack channels."}
                        </li>
                        <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                          {"Post interactive actions so teammates can kick off follow-up workflows from Slack."}
                        </li>
                      </ul>
                    </div>
                    <h2 className="relative not-first:mt-10 not-last:mb-5 font-semibold text-2xl text-primary-foreground lg:not-first:mt-12">
                      {"Configure"}
                    </h2>
                    <div className="max-w-prose font-normal">
                      <p className="not-first:mt-[13px] text-pretty text-secondary-foreground leading-[26px]">
                        {"In Joshuattio, open Workspace settings, select Apps and integrations from the sidebar, then search for and connect Slack. Choose your Slack workspace and click Allow to finish."}
                      </p>
                      <p className="not-first:mt-[13px] text-pretty text-secondary-foreground leading-[26px]">
                        {"Once connected, tag @joshuattio in any channel or DM to Ask Joshuattio. The app for Slack can only view basic information for channels it's invited to and cannot read existing messages."}
                      </p>
                      <p className="not-first:mt-[13px] text-pretty text-secondary-foreground leading-[26px]">
                        {"Learn more about using the app for Slack "}
                        <a href="/help/apps/automations-apps/slack-app" className="-mx-px rounded-sm px-px underline transition-colors duration-400 hover:duration-150 active:duration-50 text-link-foreground decoration-transparent hover:text-link-strong-foreground hover:decoration-link-strong-foreground active:text-link-strong-foreground font-medium">
                          {"here"}
                        </a>
                        {"."}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </article>
        <aside className="relative border-subtle-stroke border-t py-20 max-lg:py-16">
          <div className="relative grid grid-cols-12 gap-y-10 bg-primary-background">
            <div className="col-[2/-2] flex gap-1">
              <h3 className="text-overline">
                {"Other apps in Automations"}
              </h3>
            </div>
            <div className="col-[2/-2] grid gap-3 md:grid-cols-2 lg:grid-cols-3 lg:gap-4">
              <a className="group relative flex flex-col overflow-hidden rounded-2xl border border-subtle-stroke transition-colors duration-400 ease-in-out hover:border-white-800 hover:duration-150 active:border-white-800 active:duration-50 gap-3.5 p-5 max-lg:p-4 max-xl:gap-3" href="/apps/composio">
                <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
                <div className="relative flex items-center justify-between">
                  <div className="flex h-full w-full flex-col">
                    <div className="flex items-center gap-2.5 max-xl:gap-2">
                      <div className="relative size-10 overflow-hidden rounded-[30%] bg-primary-background">
                        <img alt="Composio" loading="lazy" width="100" height="100" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-ea63af183c.avif 1x, /img/img-ea63af183c.avif 2x" src="/img/img-ea63af183c.avif" />
                        <div className="absolute inset-0 rounded-[inherit] shadow-[inset_0_0_0_1px] shadow-black-100/10" />
                      </div>
                      <div className="flex flex-col">
                        <div className="flex items-center gap-0.5">
                          <h4 className="relative font-semibold text-secondary-foreground font-semibold! max-xl:text-sm">
                            {"Composio"}
                          </h4>
                        </div>
                        <p className="shrink truncate text-accent-foreground text-sm">
                          {"By "}
                          {"Composio Development"}
                        </p>
                      </div>
                    </div>
                  </div>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative order-last shrink-0 text-secondary-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                  </svg>
                </div>
                <p className="relative text-sm line-clamp-2 text-pretty pr-2 text-accent-foreground">
                  {"Skip the specs: seamlessly integrate any tool you need"}
                </p>
              </a>
              <a className="group relative flex flex-col overflow-hidden rounded-2xl border border-subtle-stroke transition-colors duration-400 ease-in-out hover:border-white-800 hover:duration-150 active:border-white-800 active:duration-50 gap-3.5 p-5 max-lg:p-4 max-xl:gap-3" href="/apps/cotera">
                <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
                <div className="relative flex items-center justify-between">
                  <div className="flex h-full w-full flex-col">
                    <div className="flex items-center gap-2.5 max-xl:gap-2">
                      <div className="relative size-10 overflow-hidden rounded-[30%] bg-primary-background">
                        <img alt="Cotera Pre Meeting Research" loading="lazy" width="100" height="100" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-6718270286.avif 1x, /img/img-6718270286.avif 2x" src="/img/img-6718270286.avif" />
                        <div className="absolute inset-0 rounded-[inherit] shadow-[inset_0_0_0_1px] shadow-black-100/10" />
                      </div>
                      <div className="flex flex-col">
                        <div className="flex items-center gap-0.5">
                          <h4 className="relative font-semibold text-secondary-foreground font-semibold! max-xl:text-sm">
                            {"Cotera Pre Meeting Research"}
                          </h4>
                        </div>
                        <p className="shrink truncate text-accent-foreground text-sm">
                          {"By "}
                          {"Cotera"}
                        </p>
                      </div>
                    </div>
                  </div>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative order-last shrink-0 text-secondary-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                  </svg>
                </div>
                <p className="relative text-sm line-clamp-2 text-pretty pr-2 text-accent-foreground">
                  {"Get a dossier on the person you're meeting with."}
                </p>
              </a>
              <a className="group relative flex flex-col overflow-hidden rounded-2xl border border-subtle-stroke transition-colors duration-400 ease-in-out hover:border-white-800 hover:duration-150 active:border-white-800 active:duration-50 gap-3.5 p-5 max-lg:p-4 max-xl:gap-3" href="/apps/helios">
                <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
                <div className="relative flex items-center justify-between">
                  <div className="flex h-full w-full flex-col">
                    <div className="flex items-center gap-2.5 max-xl:gap-2">
                      <div className="relative size-10 overflow-hidden rounded-[30%] bg-primary-background">
                        <img alt="Helios" loading="lazy" width="100" height="100" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-5a2e85d358.avif 1x, /img/img-5a2e85d358.avif 2x" src="/img/img-5a2e85d358.avif" />
                        <div className="absolute inset-0 rounded-[inherit] shadow-[inset_0_0_0_1px] shadow-black-100/10" />
                      </div>
                      <div className="flex flex-col">
                        <div className="flex items-center gap-0.5">
                          <h4 className="relative font-semibold text-secondary-foreground font-semibold! max-xl:text-sm">
                            {"Helios"}
                          </h4>
                        </div>
                        <p className="shrink truncate text-accent-foreground text-sm">
                          {"By "}
                          {"WarpBuild"}
                        </p>
                      </div>
                    </div>
                  </div>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative order-last shrink-0 text-secondary-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                  </svg>
                </div>
                <p className="relative text-sm line-clamp-2 text-pretty pr-2 text-accent-foreground">
                  {"The AI-native workflow automation platform"}
                </p>
              </a>
              <a className="group relative flex flex-col overflow-hidden rounded-2xl border border-subtle-stroke transition-colors duration-400 ease-in-out hover:border-white-800 hover:duration-150 active:border-white-800 active:duration-50 gap-3.5 p-5 max-lg:p-4 max-xl:gap-3" href="/apps/okta">
                <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
                <div className="relative flex items-center justify-between">
                  <div className="flex h-full w-full flex-col">
                    <div className="flex items-center gap-2.5 max-xl:gap-2">
                      <div className="relative size-10 overflow-hidden rounded-[30%] bg-primary-background">
                        <img alt="Okta" loading="lazy" width="100" height="100" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-82ba68e3c6.avif 1x, /img/img-82ba68e3c6.avif 2x" src="/img/img-82ba68e3c6.avif" />
                        <div className="absolute inset-0 rounded-[inherit] shadow-[inset_0_0_0_1px] shadow-black-100/10" />
                      </div>
                      <div className="flex flex-col">
                        <div className="flex items-center gap-0.5">
                          <h4 className="relative font-semibold text-secondary-foreground font-semibold! max-xl:text-sm">
                            {"Okta"}
                          </h4>
                          <button type="button" id="base-ui-_R_7piqaav5tiv9f9k7ivb_" data-base-ui-tooltip-trigger="" aria-label="Official app" className="group/badge flex cursor-pointer items-center justify-center">
                            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="shrink-0 text-green-600 opacity-80 transition-opacity duration-150 ease-in-out group-hover/badge:opacity-100 size-3 xl:size-3.5">
                              <path d="M6.20801 1.34399C6.63641 0.885598 7.36357 0.885598 7.79199 1.34399L8.53027 2.13403C8.74384 2.36249 9.04585 2.48724 9.3584 2.47681L10.4395 2.44067C11.0663 2.4197 11.5798 2.93384 11.5586 3.56079L11.5234 4.64087C11.5129 4.95363 11.6376 5.25631 11.8662 5.46997L12.6562 6.20825C13.1143 6.63654 13.1141 7.36281 12.6562 7.79126L11.8662 8.53052C11.6377 8.7441 11.5129 9.04605 11.5234 9.35864L11.5586 10.4397C11.5797 11.0666 11.0663 11.5807 10.4395 11.5598L9.3584 11.5227C9.04582 11.5123 8.74383 11.638 8.53027 11.8665L7.79199 12.6565C7.36359 13.1148 6.63639 13.1148 6.20801 12.6565L5.46973 11.8665C5.25615 11.638 4.95418 11.5123 4.6416 11.5227L3.56152 11.5598C2.93452 11.581 2.42031 11.0668 2.44141 10.4397L2.47754 9.35864C2.48797 9.04605 2.36228 8.74409 2.13379 8.53052L1.34375 7.79126C0.885964 7.36284 0.885757 6.63655 1.34375 6.20825L2.13379 5.46997C2.3624 5.25629 2.4881 4.95363 2.47754 4.64087L2.44141 3.56079C2.42022 2.93371 2.93446 2.41948 3.56152 2.44067L4.6416 2.47681C4.95412 2.48725 5.25615 2.36245 5.46973 2.13403L6.20801 1.34399ZM9.29102 5.09302C9.06634 4.93254 8.7533 4.9846 8.59277 5.20923L6.68848 7.87622C6.59009 8.01335 6.38652 8.01519 6.28516 7.88013L5.40039 6.70044C5.23478 6.47963 4.92109 6.43444 4.7002 6.59985C4.47948 6.76548 4.43423 7.07919 4.59961 7.30005L5.48535 8.48071C5.99258 9.15672 7.01046 9.14475 7.50195 8.45728L9.40723 5.79126C9.5677 5.5666 9.51561 5.25355 9.29102 5.09302Z" fill="currentColor" />
                            </svg>
                          </button>
                        </div>
                        <p className="shrink truncate text-accent-foreground text-sm">
                          {"By "}
                          {"Joshuattio"}
                        </p>
                      </div>
                    </div>
                  </div>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative order-last shrink-0 text-secondary-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                  </svg>
                </div>
                <p className="relative text-sm line-clamp-2 text-pretty pr-2 text-accent-foreground">
                  {"Provides Oauth2 configuration for SCIM in Okta"}
                </p>
              </a>
              <a className="group relative flex flex-col overflow-hidden rounded-2xl border border-subtle-stroke transition-colors duration-400 ease-in-out hover:border-white-800 hover:duration-150 active:border-white-800 active:duration-50 gap-3.5 p-5 max-lg:p-4 max-xl:gap-3" href="/apps/onecli">
                <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
                <div className="relative flex items-center justify-between">
                  <div className="flex h-full w-full flex-col">
                    <div className="flex items-center gap-2.5 max-xl:gap-2">
                      <div className="relative size-10 overflow-hidden rounded-[30%] bg-primary-background">
                        <img alt="OneCLI" loading="lazy" width="100" height="100" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-028c67935e.avif 1x, /img/img-028c67935e.avif 2x" src="/img/img-028c67935e.avif" />
                        <div className="absolute inset-0 rounded-[inherit] shadow-[inset_0_0_0_1px] shadow-black-100/10" />
                      </div>
                      <div className="flex flex-col">
                        <div className="flex items-center gap-0.5">
                          <h4 className="relative font-semibold text-secondary-foreground font-semibold! max-xl:text-sm">
                            {"OneCLI"}
                          </h4>
                          <button type="button" id="base-ui-_R_7piqqav5tiv9f9k7ivb_" data-base-ui-tooltip-trigger="" aria-label="Official app" className="group/badge flex cursor-pointer items-center justify-center">
                            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="shrink-0 text-green-600 opacity-80 transition-opacity duration-150 ease-in-out group-hover/badge:opacity-100 size-3 xl:size-3.5">
                              <path d="M6.20801 1.34399C6.63641 0.885598 7.36357 0.885598 7.79199 1.34399L8.53027 2.13403C8.74384 2.36249 9.04585 2.48724 9.3584 2.47681L10.4395 2.44067C11.0663 2.4197 11.5798 2.93384 11.5586 3.56079L11.5234 4.64087C11.5129 4.95363 11.6376 5.25631 11.8662 5.46997L12.6562 6.20825C13.1143 6.63654 13.1141 7.36281 12.6562 7.79126L11.8662 8.53052C11.6377 8.7441 11.5129 9.04605 11.5234 9.35864L11.5586 10.4397C11.5797 11.0666 11.0663 11.5807 10.4395 11.5598L9.3584 11.5227C9.04582 11.5123 8.74383 11.638 8.53027 11.8665L7.79199 12.6565C7.36359 13.1148 6.63639 13.1148 6.20801 12.6565L5.46973 11.8665C5.25615 11.638 4.95418 11.5123 4.6416 11.5227L3.56152 11.5598C2.93452 11.581 2.42031 11.0668 2.44141 10.4397L2.47754 9.35864C2.48797 9.04605 2.36228 8.74409 2.13379 8.53052L1.34375 7.79126C0.885964 7.36284 0.885757 6.63655 1.34375 6.20825L2.13379 5.46997C2.3624 5.25629 2.4881 4.95363 2.47754 4.64087L2.44141 3.56079C2.42022 2.93371 2.93446 2.41948 3.56152 2.44067L4.6416 2.47681C4.95412 2.48725 5.25615 2.36245 5.46973 2.13403L6.20801 1.34399ZM9.29102 5.09302C9.06634 4.93254 8.7533 4.9846 8.59277 5.20923L6.68848 7.87622C6.59009 8.01335 6.38652 8.01519 6.28516 7.88013L5.40039 6.70044C5.23478 6.47963 4.92109 6.43444 4.7002 6.59985C4.47948 6.76548 4.43423 7.07919 4.59961 7.30005L5.48535 8.48071C5.99258 9.15672 7.01046 9.14475 7.50195 8.45728L9.40723 5.79126C9.5677 5.5666 9.51561 5.25355 9.29102 5.09302Z" fill="currentColor" />
                            </svg>
                          </button>
                        </div>
                        <p className="shrink truncate text-accent-foreground text-sm">
                          {"By "}
                          {"OneCLI"}
                        </p>
                      </div>
                    </div>
                  </div>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative order-last shrink-0 text-secondary-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                  </svg>
                </div>
                <p className="relative text-sm line-clamp-2 text-pretty pr-2 text-accent-foreground">
                  {"AI agent gateway for secure, scoped API access to Joshuattio"}
                </p>
              </a>
              <a className="group relative flex flex-col overflow-hidden rounded-2xl border border-subtle-stroke transition-colors duration-400 ease-in-out hover:border-white-800 hover:duration-150 active:border-white-800 active:duration-50 gap-3.5 p-5 max-lg:p-4 max-xl:gap-3" href="/apps/round-robin-pro">
                <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
                <div className="relative flex items-center justify-between">
                  <div className="flex h-full w-full flex-col">
                    <div className="flex items-center gap-2.5 max-xl:gap-2">
                      <div className="relative size-10 overflow-hidden rounded-[30%] bg-primary-background">
                        <img alt="Round Robin Pro" loading="lazy" width="100" height="100" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-faf9bb902d.avif 1x, /img/img-faf9bb902d.avif 2x" src="/img/img-faf9bb902d.avif" />
                        <div className="absolute inset-0 rounded-[inherit] shadow-[inset_0_0_0_1px] shadow-black-100/10" />
                      </div>
                      <div className="flex flex-col">
                        <div className="flex items-center gap-0.5">
                          <h4 className="relative font-semibold text-secondary-foreground font-semibold! max-xl:text-sm">
                            {"Round Robin Pro"}
                          </h4>
                        </div>
                        <p className="shrink truncate text-accent-foreground text-sm">
                          {"By "}
                          {"Kolaai"}
                        </p>
                      </div>
                    </div>
                  </div>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative order-last shrink-0 text-secondary-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                  </svg>
                </div>
                <p className="relative text-sm line-clamp-2 text-pretty pr-2 text-accent-foreground">
                  {"Automatically assign users to records and list items"}
                </p>
              </a>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
