// Generated by scripts/port.ts. Hand edits are expected from here on.
import { QuoteWordReveal } from "./quote-reveal";

const QUOTE = "Joshuattio is the best CRM you will ever use, and likely the last CRM you will ever need.";

export function Block6() {
  return (
    <section className="container">
      <div className="border-subtle-stroke border-x">
        <div className="relative grid grid-cols-12 overflow-hidden">
          <div className="col-[2/-2] border-subtle-stroke border-x py-12 max-lg:hidden">
            <div className="relative grid grid-cols-10 grid-rows-[auto_auto] items-center gap-y-10 py-15">
              <svg width="100%" height="1" className="text-subtle-stroke absolute top-0 left-1/2 w-screen -translate-x-1/2">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <p className="col-[4/-1] text-overline" />
              <img alt="Jamie Marshall" loading="lazy" width="880" height="972" decoding="async" data-nimg="1" className="col-[1/4] row-2 size-60 max-w-none justify-self-center object-contain max-xl:size-50" style={{"color":"transparent"}} srcSet="/img/img-dd7b327be4.avif 1x, /img/img-dd7b327be4.avif 2x" src="/img/img-dd7b327be4.avif" />
              <div className="col-[4/-2] row-2 flex flex-col gap-7">
                <QuoteWordReveal quote={QUOTE} />
                <p className="font-medium text-secondary-foreground text-sm">
                  <span className="font-bold">
                    {"Jamie Marshall"}
                  </span>
                  {" ·"}
                  {" "}
                  {"Co-founder and COO at Snackpass"}
                </p>
              </div>
              <svg width="100%" height="1" className="text-subtle-stroke absolute bottom-0 left-1/2 w-screen -translate-x-1/2">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
          </div>
          <div className="col-[2/-2] lg:hidden">
            <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
              <div className="col-[2/-2] flex justify-between" />
            </div>
            <div className="flex flex-col">
              <img alt="Jamie Marshall" loading="lazy" width="880" height="972" decoding="async" data-nimg="1" className="mb-7 h-auto w-30 object-contain" style={{"color":"transparent"}} srcSet="/img/img-dd7b327be4.avif 1x, /img/img-dd7b327be4.avif 2x" src="/img/img-dd7b327be4.avif" />
              <QuoteWordReveal quote={QUOTE} mdHide={[17]} />
              <p className="mt-6 font-medium text-secondary-foreground text-sm">
                <span className="font-bold">
                  {"Jamie Marshall"}
                </span>
                {" ·"}
                {" "}
                {"Co-founder and COO at Snackpass"}
              </p>
            </div>
            <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
              <div className="col-[2/-2] flex justify-between" />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
