// Generated by scripts/port.ts. Hand edits are expected from here on.
import { InViewSwap, MentionsGrid, MentionsSection } from "./mentions";
export function TheCrmBehindThousands() {
  return (
    <div className="container w-full">
      <MentionsSection className="relative z-1 flex flex-col gap-10 py-15 lg:gap-0 border-subtle-stroke lg:border-x lg:pb-40 lg:pt-0">
        <svg width="100%" height="100%" className="text-muted-strong-background h-40 max-lg:hidden mask-b-from-30%">
          <defs>
            <pattern id="_R_clfiv9f9k7ivb_" width="10" height="10" patternUnits="userSpaceOnUse">
              <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#_R_clfiv9f9k7ivb_)" />
        </svg>
        <div data-visual-test="blackout" className="relative flex w-full flex-col justify-center overflow-x-clip">
          <div className="min-h-[463px] w-full lg:min-h-[249px]">
            <MentionsGrid />
          </div>
          <div className="bg-[linear-gradient(to_right,white,transparent_20%,transparent_80%,white_100%)] pointer-events-none absolute inset-0 z-0 max-lg:hidden" />
        </div>
        <div className="flex flex-col items-center justify-center">
          <h2 className="text-center text-heading-md">
            <span className="block overflow-hidden">
              <InViewSwap className="block transition-transform delay-600 duration-600 ease-[cubic-bezier(0.22,1,0.36,1)]" hidden="translate-y-full">
                {"The CRM behind"}
              </InViewSwap>
            </span>
            <span className="block overflow-hidden text-heading-md-serif">
              <InViewSwap className="block pb-0.5 transition-transform delay-750 duration-600 ease-[cubic-bezier(0.22,1,0.36,1)]" hidden="translate-y-full">
                {"thousands of companies."}
              </InViewSwap>
            </span>
          </h2>
          <InViewSwap as="div" className="flex items-center justify-center gap-y-2 max-md:flex-col max-md:items-center mt-6 w-full gap-x-2 transition-opacity delay-1000 duration-700 ease-[cubic-bezier(0.22,1,0.36,1)]" hidden="opacity-0" shown="opacity-100">
            <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-primary max-md:hidden" href="#">
              {"Start for free"}
            </a>
            <form className="relative flex w-full max-w-xs flex-col gap-2 md:hidden" toolname="subscribe_newsletter" tooldescription="Subscribe to Joshuattio product updates and newsletters with a work email address">
              <div className="flex flex-col gap-y-1.5">
                <div>
                  <input className="block w-full rounded-[10px] bg-primary-background p-[10px_13px] outline-hidden transition-all duration-300 ease-out text-secondary-foreground placeholder:text-accent-foreground border border-default-stroke hover:border-greyscale-light-08 hover:shadow-[0px_1px_4px_rgba(56,_62,_71,_0.1)] focus-visible:border-blue-500 focus-visible:ring-[3px] focus-visible:ring-blue-300 placeholder:max-w-full placeholder-shown:truncate placeholder:text-base" type="text" placeholder="Your email address" id="_R_mcslfiv9f9k7ivb_" aria-invalid="false" name="email" defaultValue="" suppressHydrationWarning />
                </div>
              </div>
              <button className="inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-11.5 gap-x-2 rounded-xl px-3.5 text-base has-[>svg:last-child,>img:last-child]:pr-3 has-[>svg:first-child,>img:first-child]:pl-3 button-primary relative" type="submit">
                <div className="absolute inset-0 flex items-center justify-center">
                  <svg width="18" height="18" viewBox="0 0 18 18" fill="none" className="animate-spin opacity-0 transition-opacity duration-150">
                    <circle cx="9" cy="9" r="8" stroke="currentColor" strokeOpacity="0.1" strokeWidth="1.5" />
                    <path d="M17 9C17 10.0506 16.7931 11.0909 16.391 12.0615C15.989 13.0321 15.3997 13.914 14.6569 14.6569C13.914 15.3997 13.0321 15.989 12.0615 16.391C11.0909 16.7931 10.0506 17 9 17" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </div>
                <span className="transition-opacity duration-150">
                  {"Send me a demo"}
                </span>
              </button>
            </form>
            <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline max-md:hidden" href="/contact/sales">
              {"Talk to sales"}
            </a>
            <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-ghost group self-center md:hidden" href="/contact/sales">
              <span>
                {"Talk to sales"}
              </span>
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative transition-[translate] duration-400 ease-in-out group-hover:translate-x-0.25 group-hover:duration-150 group-active:translate-x-0.25 group-active:duration-50">
                <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
              </svg>
            </a>
          </InViewSwap>
        </div>
      </MentionsSection>
    </div>
  );
}
