// Generated by scripts/port.ts. Hand edits are expected from here on.
import { WfHorizontalScroll } from "./wf-horizontal-scroll";

export function HireTheBestRep() {
  return (
    <div className="container flex flex-1 flex-col">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x">
        <header className="grid grid-cols-12 pt-40 pb-20 max-xl:pt-30 max-xl:pb-16 max-lg:pt-25 max-lg:pb-15 justify-items-start">
          <div className="max-w-[20em] text-pretty text-heading-responsive-sm text-start col-[2/-2] mix-blend-multiply dark:mix-blend-screen">
            <h2 className="text-pretty inline">
              {"Hire the best rep. Again. Again. And again."}
            </h2>
            {" "}
            <p className="inline text-pretty font-medium text-black-800">
              {"Agents in concert on every deal, beside your team."}
            </p>
          </div>
        </header>
        <WfHorizontalScroll>
            <div className="grid min-h-64 grid-cols-12 min-w-[1340px]">
              <div className="col-[2/-2] grid [grid-template-columns:var(--cols-fill)]" style={{"--cols-base":"repeat(5, 20%)","--cols-fill":"repeat(5, minmax(0, 1fr))"}}>
                <div className="relative snap-start border-subtle-stroke border-l pr-6 pl-4">
                  <div className="absolute top-0 -left-px h-lh w-px bg-secondary-foreground" />
                  <h3 className="text-pretty font-semibold text-lg text-secondary-foreground">
                    {"Enrichment Agent"}
                  </h3>
                  <p className="mt-2 max-w-[22em] text-pretty text-accent-foreground text-sm">
                    {"Waterfall enrichment. Every source."}
                  </p>
                </div>
                <div className="relative snap-start border-subtle-stroke border-l pr-6 pl-4">
                  <div className="absolute top-0 -left-px h-lh w-px bg-secondary-foreground" />
                  <h3 className="text-pretty font-semibold text-lg text-secondary-foreground">
                    {"Web Agent"}
                  </h3>
                  <p className="mt-2 max-w-[22em] text-pretty text-accent-foreground text-sm">
                    {"Account research, decision makers, recent signals."}
                  </p>
                </div>
                <div className="relative snap-start border-subtle-stroke border-l pr-6 pl-4">
                  <div className="absolute top-0 -left-px h-lh w-px bg-secondary-foreground" />
                  <h3 className="text-pretty font-semibold text-lg text-secondary-foreground">
                    {"Scoring Agent"}
                  </h3>
                  <p className="mt-2 max-w-[22em] text-pretty text-accent-foreground text-sm">
                    {"Scores every lead for fit and priority."}
                  </p>
                </div>
                <div className="relative snap-start border-subtle-stroke border-l pr-6 pl-4">
                  <div className="absolute top-0 -left-px h-lh w-px bg-secondary-foreground" />
                  <h3 className="text-pretty font-semibold text-lg text-secondary-foreground">
                    {"Routing Agent"}
                  </h3>
                  <p className="mt-2 max-w-[22em] text-pretty text-accent-foreground text-sm">
                    {"Right lead, right rep, draft email attached."}
                  </p>
                </div>
                <div className="relative snap-start border-subtle-stroke border-l pr-6 pl-4">
                  <div className="absolute top-0 -left-px h-lh w-px bg-secondary-foreground" />
                  <h3 className="text-pretty font-semibold text-lg text-secondary-foreground">
                    {"Briefing Agent"}
                  </h3>
                  <p className="mt-2 max-w-[22em] text-pretty text-accent-foreground text-sm">
                    {"Full brief in hand before every call."}
                  </p>
                </div>
              </div>
            </div>
            <div aria-hidden="true" className="h-40 justify-evenly max-lg:h-25 max-xl:h-30 flex min-w-[1340px]">
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <div className="w-0 overflow-visible">
                <svg width="1" height="100%" className="text-subtle-stroke">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
            </div>
        </WfHorizontalScroll>
      </div>
    </div>
  );
}
