// Generated by scripts/port.ts. Hand edits are expected from here on.
import { DataModelHeroDesktop, DataModelHeroMobile } from "./data-model-hero";

export function DataModel() {
  return (
    <div className="relative flex flex-col items-center">
      <svg width="100%" height="100%" className="text-muted-strong-background mask-t-from-50% mask-b-from-80% absolute inset-0">
        <defs>
          <pattern id="_S_1_" width="10" height="10" patternUnits="userSpaceOnUse">
            <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
          </pattern>
        </defs>
        <rect width="100%" height="100%" fill="url(#_S_1_)" />
      </svg>
      <div className="perspective-[3000px] isolate w-full">
        <div className="grid grid-cols-12">
          <div className="col-[2/-2]">
            <header className="flex w-full flex-col pt-30 pb-15 max-xl:pt-25 max-lg:pt-20 items-center pb-0!" style={{"--animate-delay":"0ms","--animate-delay-mobile":"0ms"}}>
              <div className="inline-block w-fit rounded-[13px] border border-weak-stroke bg-primary-background px-3 py-1.5 font-medium text-[13px]/[1.4em] text-secondary-foreground mb-6">
                <h1>
                  {"Data model"}
                </h1>
              </div>
              <h2 className="max-w-[15em] text-balance text-heading-responsive-lg text-center">
                {"One context. Every team."}
              </h2>
              <p className="mt-4 max-w-xl text-balance text-lg text-secondary-foreground lg:text-xl text-center">
                {"The right call is always in front of you. Reps, agents, and reports run on one picture. "}
              </p>
              <div className="flex w-full items-center justify-center gap-x-2.5 gap-y-2 max-md:flex-col max-md:items-center mt-6">
                <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-primary max-md:hidden" href="#">
                  {"Start for free"}
                </a>
                <form className="relative flex w-full max-w-xs flex-col gap-2 md:hidden" toolname="subscribe_newsletter" tooldescription="Subscribe to Joshuattio product updates and newsletters with a work email address">
                  <div className="flex flex-col gap-y-1.5">
                    <div>
                      <input className="block w-full rounded-[10px] bg-primary-background p-[10px_13px] outline-hidden transition-all duration-300 ease-out text-secondary-foreground placeholder:text-accent-foreground border border-default-stroke hover:border-greyscale-light-08 hover:shadow-[0px_1px_4px_rgba(56,_62,_71,_0.1)] focus-visible:border-blue-500 focus-visible:ring-[3px] focus-visible:ring-blue-300 placeholder:max-w-full placeholder-shown:truncate placeholder:text-base" type="text" placeholder="Your email address" id="_R_2ph8anpfiv9f9k7ivb_" aria-invalid="false" name="email" defaultValue="" suppressHydrationWarning />
                    </div>
                  </div>
                  <button className="inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-11.5 gap-x-2 rounded-xl px-3.5 text-base has-[>svg:last-child,>img:last-child]:pr-3 has-[>svg:first-child,>img:first-child]:pl-3 button-primary relative" type="submit">
                    <div className="absolute inset-0 flex items-center justify-center">
                      <svg width="18" height="18" viewBox="0 0 18 18" fill="none" className="animate-spin opacity-0 transition-opacity duration-150">
                        <circle cx="9" cy="9" r="8" stroke="currentColor" strokeOpacity="0.1" strokeWidth="1.5" />
                        <path d="M17 9C17 10.0506 16.7931 11.0909 16.391 12.0615C15.989 13.0321 15.3997 13.914 14.6569 14.6569C13.914 15.3997 13.0321 15.989 12.0615 16.391C11.0909 16.7931 10.0506 17 9 17" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    </div>
                    <span className="transition-opacity duration-150">
                      {"Send me a demo"}
                    </span>
                  </button>
                </form>
                <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline max-md:hidden" href="/contact/sales">
                  {"Talk to sales"}
                </a>
                <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-ghost group self-center md:hidden" href="/contact/sales">
                  <span>
                    {"Talk to sales"}
                  </span>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative transition-[translate] duration-400 ease-in-out group-hover:translate-x-0.25 group-hover:duration-150 group-active:translate-x-0.25 group-active:duration-50">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                  </svg>
                </a>
              </div>
            </header>
          </div>
        </div>
        <DataModelHeroDesktop className="hidden lg:flex" />
      </div>
      <DataModelHeroMobile className="lg:hidden" />
      <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25 h-25!">
        <div className="col-[2/-2] flex justify-between" />
      </div>
    </div>
  );
}
