// Generated by scripts/port.ts. Hand edits are expected from here on.
export function BlazinglyFastAmazinglyFlexible() {
  return (
    <section className="container">
      <div className="border-subtle-stroke border-x">
        <header className="grid grid-cols-12 pt-40 pb-20 max-xl:pt-30 max-xl:pb-16 max-lg:pt-25 max-lg:pb-15 justify-items-start">
          <div className="max-w-[20em] text-pretty text-heading-responsive-sm text-start col-[2/-2] mix-blend-multiply dark:mix-blend-screen">
            <h2 className="text-pretty inline">
              {"Blazingly fast, amazingly flexible."}
            </h2>
            {" "}
            <p className="inline text-pretty font-medium text-black-800">
              {"Create the exact data model your business needs with custom objects. "}
            </p>
          </div>
        </header>
        <div className="relative grid grid-cols-12">
          <div aria-hidden="true" className="grid w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25 absolute -top-5 h-5">
            <div className="col-[2/-2] flex justify-between">
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
          </div>
          <svg width="100%" height="1" className="text-subtle-stroke absolute top-0">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
          </svg>
          <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
            <defs>
              <pattern id="_S_2_" width="10" height="10" patternUnits="userSpaceOnUse">
                <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#_S_2_)" />
          </svg>
          <div className="relative col-[2/-2]">
            <div className="grid grid-cols-2 gap-px bg-subtle-stroke p-px max-lg:grid-cols-1">
              <div className="grid grid-cols-12 bg-primary-background" style={{"order":"1"}}>
                <div className="col-[2/-2] py-10">
                  <div className="text-overline">
                    {"[0"}
                    {"1"}
                    {"]"}
                  </div>
                  <div className="relative mt-8 mb-9 aspect-[5/3] w-full">
                    <img alt="" loading="eager" width="2416" height="1008" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-cc216fdd3c.avif 1x" src="/img/img-cc216fdd3c.avif" />
                  </div>
                  <h3 className="font-semibold text-lg text-secondary-foreground lg:max-xl:text-base max-md:text-base">
                    {"Build for any business model."}
                  </h3>
                  <p className="mt-1 max-w-[24em] text-balance text-accent-foreground lg:max-xl:text-sm max-md:text-sm">
                    {"Track investors, partners, products, or anything else unique to how you operate."}
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-12 bg-primary-background" style={{"order":"2"}}>
                <div className="col-[2/-2] py-10">
                  <div className="text-overline">
                    {"[0"}
                    {"2"}
                    {"]"}
                  </div>
                  <div className="relative mt-8 mb-9 aspect-[5/3] w-full">
                    <img alt="" loading="eager" width="2000" height="2000" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-e7d81e2eb0.avif 1x, /img/img-e7d81e2eb0.avif 2x" src="/img/img-e7d81e2eb0.avif" />
                  </div>
                  <h3 className="font-semibold text-lg text-secondary-foreground lg:max-xl:text-base max-md:text-base">
                    {"Iterate faster than ever."}
                  </h3>
                  <p className="mt-1 max-w-[24em] text-balance text-accent-foreground lg:max-xl:text-sm max-md:text-sm">
                    {"Sort, filter, and utilize millions of records in milliseconds."}
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-12 bg-primary-background" style={{"order":"4"}}>
                <div className="col-[2/-2] py-10">
                  <div className="text-overline">
                    {"[0"}
                    {"3"}
                    {"]"}
                  </div>
                  <div className="relative mt-8 mb-9 aspect-[5/3] w-full">
                    <img alt="" loading="eager" width="2200" height="1320" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-96933b9aaa.avif 1x" src="/img/img-96933b9aaa.avif" />
                  </div>
                  <h3 className="font-semibold text-lg text-secondary-foreground lg:max-xl:text-base max-md:text-base">
                    {"Fine-tune to your data structure."}
                  </h3>
                  <p className="mt-1 max-w-[24em] text-balance text-accent-foreground lg:max-xl:text-sm max-md:text-sm">
                    {"Customize fields to capture exactly what you need to track.\n"}
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-12 bg-primary-background" style={{"order":"5"}}>
                <div className="col-[2/-2] py-10">
                  <div className="text-overline">
                    {"[0"}
                    {"4"}
                    {"]"}
                  </div>
                  <div className="relative mt-8 mb-9 aspect-[5/3] w-full">
                    <img alt="" loading="eager" width="2416" height="1008" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-c5476abf47.avif 1x" src="/img/img-c5476abf47.avif" />
                  </div>
                  <h3 className="font-semibold text-lg text-secondary-foreground lg:max-xl:text-base max-md:text-base">
                    {"Create associations."}
                  </h3>
                  <p className="mt-1 max-w-[24em] text-balance text-accent-foreground lg:max-xl:text-sm max-md:text-sm">
                    {"Link objects to make your data actionable and insightful with our powerful graph model.\n"}
                  </p>
                </div>
              </div>
              <div className="relative order-3 col-[1/-1] grid grid-cols-12 bg-primary-background max-lg:order-6">
                <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
                  <defs>
                    <pattern id="_S_6_" width="10" height="10" patternUnits="userSpaceOnUse">
                      <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
                    </pattern>
                  </defs>
                  <rect width="100%" height="100%" fill="url(#_S_6_)" />
                </svg>
                <div className="relative col-[2/-2] flex flex-col items-center py-32 text-center">
                  <p className="max-w-[20em] text-pretty text-quote-responsive">
                    {"\"It finally felt like I could configure our CRM to fit our business needs, rather than the other way around.\""}
                  </p>
                  <p className="mt-10 font-semibold text-secondary-foreground text-sm">
                    {"Margaret Shen"}
                  </p>
                  <p className="mt-1 text-secondary-foreground text-sm">
                    {"Head of Business Operations · Modal"}
                  </p>
                </div>
              </div>
            </div>
          </div>
          <svg width="100%" height="1" className="text-subtle-stroke absolute bottom-0">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
          </svg>
        </div>
        <div aria-hidden="true" className="grid h-40 w-full overflow-hidden max-xl:h-30 max-lg:h-25 grid-cols-12">
          <div className="col-[2/-2] flex justify-between">
            <svg width="1" height="100%" className="text-subtle-stroke">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
            <svg width="1" height="100%" className="text-subtle-stroke">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
          </div>
        </div>
      </div>
    </section>
  );
}
