// Generated by scripts/port.ts. Hand edits are expected from here on.
export function AutomaticEnrichmentAutomaticAdvantage() {
  return (
    <div className="container flex flex-1 flex-col">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x">
        <header className="grid grid-cols-12 pt-40 pb-20 max-xl:pt-30 max-xl:pb-16 max-lg:pt-25 max-lg:pb-15 justify-items-start">
          <div className="max-w-[20em] text-pretty text-heading-responsive-sm text-start col-[2/-2] mix-blend-multiply dark:mix-blend-screen">
            <h2 className="text-pretty inline">
              {"Automatic enrichment, automatic advantage."}
            </h2>
            {" "}
            <p className="inline text-pretty font-medium text-black-800">
              {"Get the context you need for every prospect, automatically drawn from 100s of sources and pre-analyzed by AI."}
            </p>
          </div>
        </header>
        <div className="relative grid grid-cols-12">
          <div aria-hidden="true" className="grid w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25 absolute -top-5 h-5">
            <div className="col-[2/-2] flex justify-between">
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
          </div>
          <svg width="100%" height="1" className="text-subtle-stroke absolute top-0">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
          </svg>
          <div className="size-full text-surface-subtle absolute inset-0" style={{"backgroundImage":"repeating-linear-gradient(125deg, transparent, transparent 6px, currentColor 6px, currentColor 7px)"}} />
          <div className="relative col-[2/-2]">
            <div className="grid grid-cols-3 gap-px bg-subtle-stroke p-px max-lg:grid-cols-1">
              <div className="grid grid-cols-12 bg-primary-background">
                <div className="col-[2/-2] flex flex-col py-7">
                  <div className="relative mb-6 aspect-square w-full md:max-lg:aspect-golden">
                    <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
                      <defs>
                        <pattern id="_S_3_" width="10" height="10" patternUnits="userSpaceOnUse">
                          <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
                        </pattern>
                      </defs>
                      <rect width="100%" height="100%" fill="url(#_S_3_)" />
                    </svg>
                    <img alt="" loading="eager" width="1472" height="1008" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-6d74c5c33c.avif 1x, /img/img-6d74c5c33c.avif 2x" src="/img/img-6d74c5c33c.avif" />
                  </div>
                  <div className="flex flex-1 flex-col justify-between">
                    <h3 className="text-balance font-semibold text-lg text-secondary-foreground lg:max-xl:text-base max-md:text-base">
                      {"Every record, enriched."}
                    </h3>
                    <p className="mt-1.5 text-balance text-accent-foreground lg:max-xl:text-sm max-md:text-sm">
                      {"Revenue to location, employee count, company size, and more."}
                    </p>
                  </div>
                </div>
              </div>
              <div className="grid grid-cols-12 bg-primary-background">
                <div className="col-[2/-2] flex flex-col py-7">
                  <div className="relative mb-6 aspect-square w-full md:max-lg:aspect-golden">
                    <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
                      <defs>
                        <pattern id="_S_4_" width="10" height="10" patternUnits="userSpaceOnUse">
                          <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
                        </pattern>
                      </defs>
                      <rect width="100%" height="100%" fill="url(#_S_4_)" />
                    </svg>
                    <img alt="" loading="eager" width="1820" height="1820" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-76d654fe28.avif 1x, /img/img-76d654fe28.avif 2x" src="/img/img-76d654fe28.avif" />
                  </div>
                  <div className="flex flex-1 flex-col justify-between">
                    <h3 className="text-balance font-semibold text-lg text-secondary-foreground lg:max-xl:text-base max-md:text-base">
                      {"Customer conversations in context."}
                    </h3>
                    <p className="mt-1.5 text-balance text-accent-foreground lg:max-xl:text-sm max-md:text-sm">
                      {"Your team gets live customer context from every email, meeting, record, and more."}
                    </p>
                  </div>
                </div>
              </div>
              <div className="grid grid-cols-12 bg-primary-background">
                <div className="col-[2/-2] flex flex-col py-7">
                  <div className="relative mb-6 aspect-square w-full md:max-lg:aspect-golden">
                    <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
                      <defs>
                        <pattern id="_S_7_" width="10" height="10" patternUnits="userSpaceOnUse">
                          <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
                        </pattern>
                      </defs>
                      <rect width="100%" height="100%" fill="url(#_S_7_)" />
                    </svg>
                    <img alt="" loading="eager" width="2000" height="2000" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-c872bea858.avif 1x, /img/img-c872bea858.avif 2x" src="/img/img-c872bea858.avif" />
                  </div>
                  <div className="flex flex-1 flex-col justify-between">
                    <h3 className="text-balance font-semibold text-lg text-secondary-foreground lg:max-xl:text-base max-md:text-base">
                      {"Data-powered workflows."}
                    </h3>
                    <p className="mt-1.5 text-balance text-accent-foreground lg:max-xl:text-sm max-md:text-sm">
                      {"Automate your go-to-market decisions based on the most reliable dataset in the industry.\n\n"}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <svg width="100%" height="1" className="text-subtle-stroke absolute bottom-0">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
          </svg>
        </div>
        <div aria-hidden="true" className="grid h-40 w-full overflow-hidden max-xl:h-30 max-lg:h-25 grid-cols-12">
          <div className="col-[2/-2] flex justify-between">
            <svg width="1" height="100%" className="text-subtle-stroke">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
            <svg width="1" height="100%" className="text-subtle-stroke">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
          </div>
        </div>
      </div>
    </div>
  );
}
