// Generated by scripts/port.ts. Hand edits are expected from here on.
export function Divider6() {
  return (
    <svg width="100%" height="1" className="text-subtle-stroke">
      <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
    </svg>
  );
}
