// Generated by scripts/port.ts. Hand edits are expected from here on.
import { CareersSubscribeForm } from "./careers-subscribe";

export function RightRoleRightTime() {
  return (
    <section className="w-full bg-white-200">
      <div className="container">
        <div className="flex flex-col border-subtle-stroke border-x">
          <div className="relative grid grid-cols-12 overflow-hidden border-subtle-stroke border-b max-lg:hidden">
            <svg width="1" height="100%" className="text-subtle-stroke relative col-2 h-8 max-xl:hidden">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
            <div className="col-[8/-2] flex h-8 justify-between max-lg:*:hidden">
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
          </div>
          <div className="grid grid-cols-12">
            <div className="col-[2/8] grid grid-cols-6 flex-col justify-center gap-y-7 py-24 max-lg:col-[2/-2]">
              <div className="max-w-[20em] text-pretty text-heading-responsive-sm text-start col-[1/-2]">
                <h2 className="text-pretty inline">
                  {"Right role, right time."}
                </h2>
                {" "}
                <p className="inline text-pretty font-medium text-black-800">
                  {"We'll share relevant opportunities when they open up."}
                </p>
              </div>
              <CareersSubscribeForm className="col-span-full" />
            </div>
            <svg width="100%" height="1" className="text-subtle-stroke col-span-full lg:hidden">
              <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
            </svg>
            <div className="grid grid-rows-[repeat(11,24px)] gap-px lg:hidden">
              <svg width="100%" height="1" className="text-subtle-stroke row-4 -translate-y-px">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <svg width="100%" height="1" className="text-subtle-stroke row-9 -translate-y-px">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
            <div className="relative col-[8/-2] border-subtle-stroke border-x max-lg:col-[2/-2]">
              <div className="relative grid grid-cols-5 grid-rows-11 gap-px bg-white-400 md:grid-cols-7 lg:grid-cols-5">
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <div className="h-8 w-full bg-white-200 max-lg:h-6 hidden md:block lg:hidden" />
                <svg width="100%" height="1" className="text-subtle-stroke absolute col-span-full row-4 -translate-y-px">
                  <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
                </svg>
                <svg width="100%" height="1" className="text-subtle-stroke absolute col-span-full row-9 -translate-y-px">
                  <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
                </svg>
              </div>
              <svg width="247" height="177" viewBox="0 0 247 177" fill="none" xmlns="http://www.w3.org/2000/svg" className="absolute top-1/2 left-1/2 size-1/2 -translate-x-1/2 -translate-y-1/2 object-contain md:left-1/2 lg:left-1/2">
                <path d="M68.9141 176.069L246.217 0.929688L81.2501 104.513L68.9141 176.069Z" fill="white" stroke="#505967" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" />
                <path d="M1.5 66.578L54.8065 89.7543L68.9039 176.069L81.2399 104.513L193.856 158.654L246.206 0.929688L1.5 66.578Z" fill="white" stroke="#505967" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" />
                <path d="M55.5 90L69 172L80.5 104.5L244.5 2L55.5 90Z" fill="#FAFAFB" />
                <path d="M81.246 104.513L246.212 0.929688L54.8125 89.7543" stroke="#505967" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="3 4" />
              </svg>
            </div>
            <div className="grid grid-rows-[repeat(11,32px)] gap-px max-lg:grid-rows-[repeat(11,24px)]">
              <svg width="100%" height="1" className="text-subtle-stroke row-4 -translate-y-px">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <svg width="100%" height="1" className="text-subtle-stroke row-9 -translate-y-px">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
          </div>
          <div className="relative grid grid-cols-12 overflow-hidden border-subtle-stroke border-t max-lg:hidden">
            <svg width="1" height="100%" className="text-subtle-stroke relative col-2 h-8 max-xl:hidden">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
            <div className="col-[8/-2] flex h-8 justify-between max-lg:*:hidden">
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
