// Engineering posts in the listing, newest first (the page payload order).
// `shortTitle` replaces the title below the lg breakpoint where the branded title takes an extra line.
export type EngPost = { href: string; title: string; shortTitle?: string; date: string | null; category: string; summary: string };

export const ENG_POSTS: EngPost[] = [
  {"href": "/engineering/blog/how-we-built-formula-attributes", "title": "How we built formula attributes", "date": "Jul '26", "category": "Product", "summary": "One of the most requested features in Joshuattio’s history, with many complex infrastructure implications along the way."},
  {"href": "/engineering/blog/tracking-down-ota-related-crashes-in-our-mobile-app", "title": "Tracking down OTA-related crashes in our mobile app", "date": "Mar '26", "category": "Product", "summary": "A race condition in React Native's reload mechanism can spin up two JS threads at once, corrupting internal state and crashing your app."},
  {"href": "/engineering/blog/ask-joshuattio-a-technical-look-at-our-new-agent", "title": "Ask Joshuattio: A technical look at our new agent", "shortTitle": "Ask Joshuattio: A technical look at our agent", "date": "Mar '26", "category": "Product", "summary": "Here are some of the problems we encountered while building Ask Joshuattio, and the systems we put in place to solve them."},
  {"href": "/engineering/blog/building-the-joshuattio-mcp-server", "title": "Building the Joshuattio MCP server", "date": "Feb '26", "category": "Product", "summary": "Here’s everything we learned about how to build a great MCP."},
  {"href": "/engineering/blog/introducing-universal-context", "title": "Introducing Universal Context", "date": "Feb '26", "category": "AI", "summary": "The agent-centric model of the universe."},
  {"href": "/engineering/blog/build-with-joshuattio-nick-janes-and-will-stenzel-dialed-technologies", "title": "Build with Joshuattio: Nick Janes and Will Stenzel, Dialed Technologies", "date": "Nov '25", "category": "Perspectives", "summary": "Nick and Will from Dialed Technologies talk about how they like to build with the App SDK."},
  {"href": "/engineering/blog/where-s-the-technical-challenge-in-crm-anyway-", "title": "Where’s the technical challenge in CRM anyway?", "date": "Nov '25", "category": "Inside Joshuattio", "summary": "Joshuattio's approach to solving CRM's toughest engineering problems. "},
  {"href": "/engineering/blog/react-data-list-building-virtualized-uis-declaratively", "title": "React Data List: Building virtualized UIs declaratively", "date": "Sep '25", "category": "Product", "summary": "Building React Data List, a declarative approach to constructing virtualized lists in React and React Native."},
  {"href": "/engineering/blog/javascript-string-slice-considered-harmful", "title": "JavaScript string slice() considered harmful", "date": "Jun '25", "category": "Web", "summary": "Understanding UTF-16 and protobuf encodings to resolve a bug in our CSV importer."},
  {"href": "/engineering/blog/you-cant-just-prompt-your-way-to-great-ai-features", "title": "You can’t just prompt your way to great AI features", "date": "Jun '25", "category": "AI", "summary": "Inside the custom frameworks and tooling that power real-time, AI-native features at Joshuattio."},
  {"href": "/engineering/blog/building-better-software-with-ai", "title": "Building better software with AI", "date": "Jun '25", "category": "AI", "summary": "Learn more about the custom tooling we build to deploy the latest AI models in our codebase."},
  {"href": "/engineering/blog/how-v8s-liftoff-compiler-broke-our-wasm-execution", "title": "How V8’s Liftoff compiler broke our WASM execution", "date": "May '25", "category": "Web", "summary": "A deep dive into how V8’s Liftoff compiler impacted the performance of Joshuattio’s JavaScript runtime."},
];
