// Generated by scripts/port.ts. Hand edits are expected from here on.
export function HowThousandsOfTeams() {
  return (
    <div className="container flex flex-1 flex-col max-lg:contents">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none">
        <div className="h-16 lg:h-32" />
        <svg width="100%" height="1" className="text-subtle-stroke">
          <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
        </svg>
        <div className="grid grid-cols-24">
          <div className="col-[3/-3] flex items-center py-16 lg:col-[2/15] lg:py-20">
            <div className="text-pretty text-start max-w-131 font-medium text-heading-responsive-md [&>p]:text-black-700">
              <h2 className="text-pretty inline">
                {"How thousands of teams work."}
              </h2>
              {" "}
              <p className="inline text-pretty font-medium text-black-800">
                {"MCP is in daily use"}
                <span className="max-md:hidden">{" across Joshuattio"}</span>
                {"."}
              </p>
            </div>
          </div>
          <div className="@container col-span-full border-subtle-stroke border-t lg:col-[16/-1] lg:border-t-0 lg:border-l">
            <div className="flex min-h-64 flex-col items-center justify-center gap-4 px-8 py-16 text-center lg:min-h-116">
              <p className="font-display font-medium text-[clamp(56px,19cqw,100px)] text-secondary-foreground leading-none -tracking-[0.01em]">
                {"583k+"}
              </p>
              <p className="text-accent-foreground text-lg">
                {"Daily average MCP calls from Joshuattio workspaces."}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
