// Generated by scripts/port.ts. Hand edits are expected from here on.
import { UcHorizontalScroll } from "@/components/pages/platform/universal-context/uc-horizontal-scroll";

export function ConnectedInAClick() {
  return (
    <div className="container flex flex-1 flex-col max-lg:contents">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none">
        <header className="grid pt-40 pb-20 max-xl:pt-30 max-xl:pb-16 max-lg:pt-25 max-lg:pb-15 justify-items-start grid-cols-24 [&>div]:col-[3/-3] lg:[&>div]:col-[2/-2]">
          <div className="col-[2/-2]">
            <div className="flex flex-col items-start gap-6">
              <div className="text-pretty text-start max-w-[22em] font-medium text-heading-responsive-md">
                <h2 className="text-pretty inline">
                  {"Connected in a click."}
                </h2>
                {" "}
                <p className="inline text-pretty font-medium text-black-800">
                  {"No setup, no code, no waiting on anyone else."}
                </p>
              </div>
              <div className="flex items-center justify-center gap-x-2.5 gap-y-2 max-md:flex-col max-md:items-center w-auto">
                <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-10 gap-x-2 rounded-xl px-3.25 text-base has-[>svg:last-child,>img:last-child]:pr-2.5 has-[>svg:first-child,>img:first-child]:pl-2.5 button-outline" href="#">
                  {"Read the docs"}
                </a>
              </div>
            </div>
          </div>
        </header>
        <UcHorizontalScroll>
          <ol className="grid w-max min-w-full auto-cols-[280px] grid-flow-col px-[8.333%] lg:w-full lg:auto-cols-fr lg:px-[4.167%]">
            <li className="flex snap-start flex-col border-subtle-stroke border-l">
              <div className="flex min-h-50 grow flex-col gap-4 px-6 pb-12">
                <p className="text-accent-foreground text-overline">
                  {"01"}
                </p>
                <div className="flex flex-col gap-1">
                  <h3 className="text-lg text-secondary-foreground">
                    {"Find Joshuattio."}
                  </h3>
                  <p className="text-accent-foreground text-base">
                    {"Select Joshuattio from the list of connectors in the tool you want to work from."}
                  </p>
                </div>
              </div>
              <div aria-hidden="true" className="flex h-14 justify-evenly max-lg:h-10 max-xl:h-12">
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
              </div>
            </li>
            <li className="flex snap-start flex-col border-subtle-stroke border-l">
              <div className="flex min-h-50 grow flex-col gap-4 px-6 pb-12">
                <p className="text-accent-foreground text-overline">
                  {"02"}
                </p>
                <div className="flex flex-col gap-1">
                  <h3 className="text-lg text-secondary-foreground">
                    {"Sign in."}
                  </h3>
                  <p className="text-accent-foreground text-base">
                    {"Authenticate with OAuth using the Joshuattio account you already have."}
                  </p>
                </div>
              </div>
              <div aria-hidden="true" className="flex h-14 justify-evenly max-lg:h-10 max-xl:h-12">
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
              </div>
            </li>
            <li className="flex snap-start flex-col border-subtle-stroke border-l">
              <div className="flex min-h-50 grow flex-col gap-4 px-6 pb-12">
                <p className="text-accent-foreground text-overline">
                  {"03"}
                </p>
                <div className="flex flex-col gap-1">
                  <h3 className="text-lg text-secondary-foreground">
                    {"Start working."}
                  </h3>
                  <p className="text-accent-foreground text-base">
                    {"Access follows what you can already see and do in Joshuattio."}
                  </p>
                </div>
              </div>
              <div aria-hidden="true" className="flex h-14 justify-evenly max-lg:h-10 max-xl:h-12">
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
                <div className="w-0 overflow-visible">
                  <svg width="1" height="100%" className="text-subtle-stroke">
                    <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                  </svg>
                </div>
              </div>
            </li>
          </ol>
        </UcHorizontalScroll>
      </div>
    </div>
  );
}
