// Generated by scripts/port.ts. Hand edits are expected from here on.
export function KeepUpToDate() {
  return (
    <div className="container flex flex-1 flex-col max-lg:contents">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none">
        <div className="flex flex-col gap-8 px-8 py-14 lg:flex-row lg:items-center lg:justify-between lg:px-[4.167%]">
          <div>
            <h2 className="font-display text-2xl">
              {"Keep up to date."}
            </h2>
            <p className="font-display text-2xl text-accent-foreground">
              {"Get the latest updates."}
            </p>
          </div>
          <form className="relative grid min-h-16 max-w-sm items-start gap-2 md:grid-cols-[1fr_min-content] [&_button]:h-10 [&_input]:h-10! w-full lg:max-w-100" toolname="subscribe_newsletter" tooldescription="Subscribe to Joshuattio product updates and newsletters with a work email address">
            <div className="flex flex-col gap-y-1.5 relative">
              <div>
                <input className="block w-full rounded-[10px] bg-primary-background p-[10px_13px] outline-hidden transition-all duration-300 ease-out text-secondary-foreground placeholder:text-accent-foreground border border-default-stroke hover:border-greyscale-light-08 hover:shadow-[0px_1px_4px_rgba(56,_62,_71,_0.1)] focus-visible:border-blue-500 focus-visible:ring-[3px] focus-visible:ring-blue-300 placeholder:max-w-full placeholder-shown:truncate text-sm placeholder:text-sm" type="text" placeholder="Your email address" id="_R_mcanpfiv9f9k7ivb_" aria-invalid="false" name="email" defaultValue="" suppressHydrationWarning />
              </div>
            </div>
            <button className="inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 button-primary relative" type="submit">
              <div className="absolute inset-0 flex items-center justify-center">
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none" className="animate-spin opacity-0 transition-opacity duration-150">
                  <circle cx="9" cy="9" r="8" stroke="currentColor" strokeOpacity="0.1" strokeWidth="1.5" />
                  <path d="M17 9C17 10.0506 16.7931 11.0909 16.391 12.0615C15.989 13.0321 15.3997 13.914 14.6569 14.6569C13.914 15.3997 13.0321 15.989 12.0615 16.391C11.0909 16.7931 10.0506 17 9 17" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </div>
              <span className="transition-opacity duration-150">
                {"Subscribe"}
              </span>
            </button>
          </form>
        </div>
        <svg width="100%" height="1" className="text-subtle-stroke">
          <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
        </svg>
        <div className="h-16 lg:h-32" />
      </div>
    </div>
  );
}
