// Generated by scripts/port.ts. Hand edits are expected from here on.
import { CardPriceAmount, PeriodSwitcher, PeriodValue, SaveBadge } from "./pricing-period";

export function FromZeroToIpo() {
  return (
    <div className="container">
      <div className="flex flex-col items-center pt-[116px]">
        <h1 className="text-center text-heading-responsive-lg">
          {"From zero to IPO."}
        </h1>
        <p className="mt-4 max-w-md text-balance text-center text-secondary-foreground text-xl">
          {"Designed for every stage of your journey. Start today, no credit card required."}
        </p>
      </div>
      <div className="mt-8">
        <div className="flex flex-col items-center">
          <PeriodSwitcher />
        </div>
        <div className="relative grid grid-cols-12 gap-x-6 mt-10 lg:mt-20">
          <div className="pricing-cards-grid-line bg-[linear-gradient(to_left,_rgba(237,_239,_243,_0.00)_0%,_#CAD0D9_6.52%,_#CAD0D9_93.22%,_rgba(237,_239,_243,_0.00)_100%)] absolute -top-3 left-0 hidden h-px w-full -translate-y-1/2 lg:block" />
          <div className="pricing-cards-grid-line bg-[linear-gradient(to_left,_rgba(237,_239,_243,_0.00)_0%,_#CAD0D9_6.52%,_#CAD0D9_93.22%,_rgba(237,_239,_243,_0.00)_100%)] absolute -bottom-3 left-0 hidden h-px w-full translate-y-1/2 [animation-delay:450ms]! lg:block" />
          <div className="relative isolate col-span-12 grid grid-cols-1 gap-6 lg:grid-cols-4 xl:col-span-10 xl:col-start-2">
            <div className="pricing-cards-grid-line-vertical bg-[linear-gradient(to_bottom,_rgba(237,_239,_243,_0.00)_0%,_#CAD0D9_10.87%,_#CAD0D9_89.55%,_rgba(237,_239,_243,_0.00)_100%)] absolute top-[-50px] -left-3 col-start-1 hidden h-[calc(100%+100px)] w-px -translate-x-1/2 lg:block" />
            <div className="pricing-cards-grid-line-vertical bg-[linear-gradient(to_bottom,_rgba(237,_239,_243,_0.00)_0%,_#CAD0D9_10.87%,_#CAD0D9_89.55%,_rgba(237,_239,_243,_0.00)_100%)] absolute top-[-50px] -left-3 col-start-2 hidden h-[calc(100%+100px)] w-px -translate-x-1/2 [animation-delay:150ms]! lg:block" />
            <div className="pricing-cards-grid-line-vertical bg-[linear-gradient(to_bottom,_rgba(237,_239,_243,_0.00)_0%,_#CAD0D9_10.87%,_#CAD0D9_89.55%,_rgba(237,_239,_243,_0.00)_100%)] absolute top-[-50px] -left-3 col-start-3 hidden h-[calc(100%+100px)] w-px -translate-x-1/2 [animation-delay:300ms]! lg:block" />
            <div className="pricing-cards-grid-line-vertical bg-[linear-gradient(to_bottom,_rgba(237,_239,_243,_0.00)_0%,_#CAD0D9_10.87%,_#CAD0D9_89.55%,_rgba(237,_239,_243,_0.00)_100%)] absolute top-[-50px] -left-3 col-start-4 hidden h-[calc(100%+100px)] w-px -translate-x-1/2 [animation-delay:450ms]! lg:block" />
            <div className="pricing-cards-grid-line-vertical bg-[linear-gradient(to_bottom,_rgba(237,_239,_243,_0.00)_0%,_#CAD0D9_10.87%,_#CAD0D9_89.55%,_rgba(237,_239,_243,_0.00)_100%)] absolute top-[-50px] -right-3 col-start-5 hidden h-[calc(100%+100px)] w-px translate-x-1/2 [animation-delay:600ms]! lg:block" />
            <div className="absolute -top-3 -left-3 hidden -translate-x-1/2 -translate-y-1/2 lg:block">
              <div className="relative h-[7px] w-[7px] fade-in animate-in fill-mode-both [animation-delay:1000ms] [animation-duration:1000ms]">
                <div className="absolute top-[3px] left-0 h-px w-full rounded-full bg-muted-strong-background" />
                <div className="absolute top-0 left-[3px] h-full w-px rounded-full bg-muted-strong-background" />
              </div>
            </div>
            <div className="absolute -top-3 -right-3 hidden translate-x-1/2 -translate-y-1/2 lg:block">
              <div className="relative h-[7px] w-[7px] fade-in animate-in fill-mode-both [animation-delay:1000ms] [animation-duration:1000ms]">
                <div className="absolute top-[3px] left-0 h-px w-full rounded-full bg-muted-strong-background" />
                <div className="absolute top-0 left-[3px] h-full w-px rounded-full bg-muted-strong-background" />
              </div>
            </div>
            <div className="absolute -right-3 -bottom-3 hidden translate-x-1/2 translate-y-1/2 lg:block">
              <div className="relative h-[7px] w-[7px] fade-in animate-in fill-mode-both [animation-delay:1000ms] [animation-duration:1000ms]">
                <div className="absolute top-[3px] left-0 h-px w-full rounded-full bg-muted-strong-background" />
                <div className="absolute top-0 left-[3px] h-full w-px rounded-full bg-muted-strong-background" />
              </div>
            </div>
            <div className="absolute -bottom-3 -left-3 hidden -translate-x-1/2 translate-y-1/2 lg:block">
              <div className="relative h-[7px] w-[7px] fade-in animate-in fill-mode-both [animation-delay:1000ms] [animation-duration:1000ms]">
                <div className="absolute top-[3px] left-0 h-px w-full rounded-full bg-muted-strong-background" />
                <div className="absolute top-0 left-[3px] h-full w-px rounded-full bg-muted-strong-background" />
              </div>
            </div>
            <div className="flex flex-col justify-between rounded-3xl border border-subtle-stroke border-solid px-[23px] pt-[21px] pb-[23px] shadow-[0px_1px_2px_-1px_rgba(28,_40,_64,_0.08),_0px_2px_4px_0px_rgba(28,_40,_64,_0.04)]">
              <div className="flex flex-col">
                <header className="text-secondary-foreground text-xl">
                  {"Free"}
                </header>
                <div className="mt-4 lg:mt-8">
                  <div className="flex items-start gap-2">
                    <div className="inline-block overflow-y-hidden text-heading-md">
                      <div className="inline-flex transition-[translate,opacity] duration-500 ease-out translate-y-0 opacity-100">
                        <span>
                          {"$"}
                        </span>
                        <CardPriceAmount monthly={"0"} annual={"0"} />
                      </div>
                    </div>
                  </div>
                  <div className="mt-0.5 text-accent-foreground text-xs">
                    <span>
                      {"Per user/month, billed"}
                      {" "}
                      <PeriodValue monthly={"monthly"} annual={"annually"} />
                    </span>
                  </div>
                </div>
                <div className="mt-5 text-pretty font-semibold text-secondary-foreground text-sm lg:mt-8">
                  <span className="max-md:hidden">{"For individuals to explore Joshuattio on their own."}</span>
                  <span className="md:hidden">{"For individuals to explore Joshuattio solo."}</span>
                </div>
                <ul className="mt-2.5 flex flex-col gap-y-2.5">
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Real-time contact syncing">
                      {"Real-time contact syncing"}
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Automatic data enrichment">
                      {"Automatic data enrichment"}
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Up to 3 seats">
                      {"Up to 3 seats"}
                    </div>
                  </li>
                </ul>
              </div>
              <div className="mt-5 flex flex-col items-stretch lg:mt-8">
                <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline" href="#">
                  {"Start for free"}
                </a>
              </div>
            </div>
            <div className="flex flex-col justify-between rounded-3xl border border-subtle-stroke border-solid px-[23px] pt-[21px] pb-[23px] shadow-[0px_1px_2px_-1px_rgba(28,_40,_64,_0.08),_0px_2px_4px_0px_rgba(28,_40,_64,_0.04)]">
              <div className="flex flex-col">
                <header className="text-secondary-foreground text-xl">
                  {"Plus"}
                </header>
                <div className="mt-4 lg:mt-8">
                  <div className="flex items-start gap-2">
                    <div className="inline-block overflow-y-hidden text-heading-md">
                      <div className="inline-flex transition-[translate,opacity] duration-500 ease-out translate-y-0 opacity-100">
                        <span>
                          {"$"}
                        </span>
                        <CardPriceAmount monthly={"44"} annual={"35"} />
                      </div>
                    </div>
                    <SaveBadge className="mt-[6px]">
                    {"Save "}
                    {"20"}
                    {"%"}
                    </SaveBadge>
                  </div>
                  <div className="mt-0.5 text-accent-foreground text-xs">
                    <span>
                      {"Per user/month, billed"}
                      {" "}
                      <PeriodValue monthly={"monthly"} annual={"annually"} />
                    </span>
                  </div>
                </div>
                <div className="mt-5 text-pretty font-semibold text-secondary-foreground text-sm lg:mt-8">
                  {"For small teams to get started together."}
                </div>
                <ul className="mt-2.5 flex flex-col gap-y-2.5">
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Private lists">
                      {"Private lists"}
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Enhanced email sending">
                      {"Enhanced email sending"}
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Up to 10 seats">
                      {"Up to 10 seats"}
                    </div>
                  </li>
                </ul>
              </div>
              <div className="mt-5 flex flex-col items-stretch lg:mt-8">
                <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline" href="#">
                  {"Continue with Plus"}
                </a>
              </div>
            </div>
            <div className="flex flex-col justify-between rounded-3xl border border-solid px-[23px] pt-[21px] pb-[23px] border-blue-300 shadow-[0px_0px_0px_4px_rgba(83,_139,_243,_0.10),_0px_1px_2px_-1px_rgba(28,_40,_64,_0.10),_0px_2px_4px_0px_rgba(28,_40,_64,_0.06)]">
              <div className="flex flex-col">
                <header className="text-secondary-foreground text-xl">
                  {"Pro"}
                </header>
                <div className="mt-4 lg:mt-8">
                  <div className="flex items-start gap-2">
                    <div className="inline-block overflow-y-hidden text-heading-md">
                      <div className="inline-flex transition-[translate,opacity] duration-500 ease-out translate-y-0 opacity-100">
                        <span>
                          {"$"}
                        </span>
                        <CardPriceAmount monthly={"99"} annual={"79"} />
                      </div>
                    </div>
                    <SaveBadge className="mt-[6px]">
                    {"Save "}
                    {"20"}
                    {"%"}
                    </SaveBadge>
                  </div>
                  <div className="mt-0.5 text-accent-foreground text-xs">
                    <span>
                      {"Per user/month, billed"}
                      {" "}
                      <PeriodValue monthly={"monthly"} annual={"annually"} />
                    </span>
                  </div>
                </div>
                <div className="mt-5 text-pretty font-semibold text-secondary-foreground text-sm lg:mt-8">
                  {"For growing teams to scale revenue with automation."}
                </div>
                <ul className="mt-2.5 flex flex-col gap-y-2.5">
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Call Intelligence & sequences">
                      {"Call Intelligence & sequences"}
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Permission controls">
                      {"Permission controls"}
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Advanced reporting">
                      {"Advanced reporting"}
                    </div>
                  </li>
                </ul>
              </div>
              <div className="mt-5 flex flex-col items-stretch lg:mt-8">
                <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-primary" href="#">
                  {"Continue with Pro"}
                </a>
              </div>
            </div>
            <div className="flex flex-col justify-between rounded-3xl border border-subtle-stroke border-solid px-[23px] pt-[21px] pb-[23px] shadow-[0px_1px_2px_-1px_rgba(28,_40,_64,_0.08),_0px_2px_4px_0px_rgba(28,_40,_64,_0.04)]">
              <div className="flex flex-col">
                <header className="text-secondary-foreground text-xl">
                  {"Enterprise"}
                </header>
                <div className="mt-4 lg:mt-8">
                  <div className="flex items-start gap-2">
                    <div className="inline-block overflow-y-hidden text-heading-md">
                      <div className="inline-flex transition-[translate,opacity] duration-500 ease-out translate-y-0 opacity-100">
                        <span className="inline-grid overflow-y-hidden text-heading-md">
                          <span className="col-1 row-1">
                            {"Custom"}
                          </span>
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="mt-0.5 text-accent-foreground text-xs">
                    <span>
                      {"Billed annually"}
                    </span>
                  </div>
                </div>
                <div className="mt-5 text-pretty font-semibold text-secondary-foreground text-sm lg:mt-8">
                  {"For organizations needing advanced security and control."}
                </div>
                <ul className="mt-2.5 flex flex-col gap-y-2.5">
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Unlimited objects">
                      {"Unlimited objects"}
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Unlimited teams">
                      {"Unlimited teams"}
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <div className="mt-px h-[18px] w-[18px] shrink-0 rounded-md bg-surface-subtle p-0.5 text-accent-foreground">
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2649 3.07601C11.4991 3.22236 11.5703 3.53084 11.4239 3.76501L8.27903 8.79686L8.26603 8.81766C7.96584 9.29798 7.72247 9.68737 7.50209 9.9779C7.27756 10.2739 7.03718 10.5228 6.72175 10.6676C6.24572 10.8861 5.70298 10.9091 5.21014 10.7318C4.88356 10.6142 4.62295 10.3867 4.37412 10.1108C4.1299 9.83997 3.85439 9.47262 3.51455 9.01949L3.49983 8.99986L2.59994 7.80001C2.43425 7.57909 2.47902 7.26569 2.69994 7.10001C2.92085 6.93432 3.23425 6.97909 3.39994 7.20001L4.29983 8.39986C4.65789 8.87728 4.90647 9.2079 5.11672 9.44102C5.32588 9.67294 5.45274 9.75629 5.54875 9.79084C5.79517 9.87952 6.06655 9.868 6.30456 9.75874C6.3973 9.71616 6.51663 9.62236 6.70538 9.37354C6.8951 9.12343 7.11474 8.77292 7.43103 8.26686L10.5759 3.23501C10.7223 3.00084 11.0308 2.92965 11.2649 3.07601Z" fill="currentColor" />
                      </svg>
                    </div>
                    <div className="text-pretty text-sm text-tertiary-foreground" aria-label="Security and admin controls">
                      {"Security and admin controls"}
                    </div>
                  </li>
                </ul>
              </div>
              <div className="mt-5 flex flex-col items-stretch lg:mt-8">
                <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-outline max-md:hidden" href="/contact/sales">
                  {"Talk to sales"}
                </a>
                <a className="relative inline-flex cursor-pointer items-center justify-center text-nowrap border transition-colors duration-300 ease-in-out hover:duration-50 active:duration-50 disabled:pointer-events-none disabled:cursor-default h-9 gap-x-1.5 rounded-[10px] px-3 text-sm has-[>svg:last-child,>img:last-child]:pr-2 has-[>svg:first-child,>img:first-child]:pl-2 max-lg:h-11.5 max-lg:gap-x-2 max-lg:rounded-xl max-lg:px-3.5 max-lg:text-base max-lg:has-[>svg:last-child,>img:last-child]:pr-3 max-lg:has-[>svg:first-child,>img:first-child]:pl-3 button-ghost group self-center md:hidden" href="/contact/sales">
                  <span>
                    {"Talk to sales"}
                  </span>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative transition-[translate] duration-400 ease-in-out group-hover:translate-x-0.25 group-hover:duration-150 group-active:translate-x-0.25 group-active:duration-50">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                  </svg>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
