// Generated by scripts/port.ts. Hand edits are expected from here on.
export function Block() {
  return (
    <div className="mt-16">
      <div className="container">
        <div className="">
          <div className="grid grid-cols-12 justify-items-center py-25">
            <div className="col-[2/-2]">
              <div className="grid max-w-7xl grid-cols-6 gap-x-8 gap-y-4.5 max-xl:grid-cols-4 max-xl:gap-y-5 max-lg:gap-x-5 max-lg:gap-y-3 max-md:grid-cols-3 max-md:gap-x-4 max-md:gap-y-2 max-md:[&>*:nth-child(1n+10)]:hidden">
                <img alt="" loading="lazy" width="172" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-cdccc1683f.svg" />
                <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-e19ee7aa7e.svg" />
                <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-68ebdf05c6.svg" />
                <img alt="" loading="lazy" width="172" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-f24c7aed92.svg" />
                <img alt="" loading="lazy" width="172" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-e968c04334.svg" />
                <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-d2ad8a2086.svg" />
                <img alt="" loading="lazy" width="172" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-386d86418c.svg" />
                <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-22fe3f65e3.svg" />
                <img alt="" loading="lazy" width="172" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-6d36ae69be.svg" />
                <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-d541d39ae5.svg" />
                <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-77102b67da.svg" />
                <img alt="" loading="lazy" width="173" height="60" decoding="async" data-nimg="1" className="size-full h-12 object-contain max-xl:h-10" style={{"color":"transparent"}} src="/img/img-5b71add25e.svg" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
