// Generated by scripts/port.ts. Hand edits are expected from here on.
export function ReportingEngineForGtm() {
  return (
    <div className="container flex flex-1 flex-col max-lg:contents">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none" id="reporting_engine">
        <header className="grid grid-cols-12 pt-40 pb-20 max-xl:pt-30 max-xl:pb-16 max-lg:pt-25 max-lg:pb-15 justify-items-center">
          <div className="max-w-[20em] text-pretty text-heading-responsive-sm text-center col-[2/-2] mix-blend-multiply dark:mix-blend-screen [&>p]:text-accent-foreground">
            <h2 className="text-pretty inline">
              {"Reporting engine for GTM teams."}
            </h2>
            {" "}
            <p className="inline text-pretty font-medium text-black-800">
              {"The answer ready the moment you need it."}
            </p>
          </div>
        </header>
        <div className="grid grid-cols-1 gap-px border-subtle-stroke border-t bg-subtle-stroke md:grid-cols-2 lg:grid-cols-8">
          <div className="grid min-w-0 grid-cols-12 bg-primary-background lg:block lg:p-8 lg:col-span-5">
            <div className="col-[2/-2] flex h-full flex-col gap-8 py-8 lg:py-0">
              <div className="relative aspect-3/2 overflow-hidden lg:aspect-auto lg:h-79">
                <img alt="" loading="lazy" width="2418" height="948" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} sizes="(min-width: 1728px) 800px, (min-width: 1024px) 60vw, (min-width: 768px) 50vw, 100vw" srcSet="/img/img-15c1fbeee9.avif 384w, /img/img-15c1fbeee9.avif 640w, /img/img-15c1fbeee9.avif 750w, /img/img-15c1fbeee9.avif 828w, /img/img-15c1fbeee9.avif 1080w, /img/img-15c1fbeee9.avif 1200w, /img/img-15c1fbeee9.avif 1920w, /img/img-15c1fbeee9.avif 2048w, /img/img-15c1fbeee9.avif 3840w" src="/img/img-15c1fbeee9.avif" />
              </div>
              <div>
                <h3 className="font-semibold text-lg text-secondary-foreground max-md:text-base">
                  {"Your business, from any angle."}
                </h3>
                <p className="mt-1.5 text-tertiary-foreground max-md:text-sm">
                  {"Group by anything you track, in the format of your choice."}
                </p>
              </div>
            </div>
          </div>
          <div className="grid min-w-0 grid-cols-12 bg-primary-background lg:block lg:p-8 lg:col-span-3">
            <div className="col-[2/-2] flex h-full flex-col gap-8 py-8 lg:py-0">
              <div className="relative aspect-3/2 overflow-hidden lg:aspect-auto lg:h-79">
                <img alt="" loading="lazy" width="1374" height="948" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} sizes="(min-width: 1728px) 450px, (min-width: 1024px) 35vw, (min-width: 768px) 50vw, 100vw" srcSet="/img/img-3a75084f27.avif 256w, /img/img-3a75084f27.avif 384w, /img/img-3a75084f27.avif 640w, /img/img-3a75084f27.avif 750w, /img/img-3a75084f27.avif 828w, /img/img-3a75084f27.avif 1080w, /img/img-3a75084f27.avif 1200w, /img/img-3a75084f27.avif 1920w, /img/img-3a75084f27.avif 2048w, /img/img-3a75084f27.avif 3840w" src="/img/img-3a75084f27.avif" />
              </div>
              <div>
                <h3 className="font-semibold text-lg text-secondary-foreground max-md:text-base">
                  {"A report type for every question."}
                </h3>
                <p className="mt-1.5 text-tertiary-foreground max-md:text-sm">
                  {"Where deals stall, how long they sit, and what changed since last quarter."}
                </p>
              </div>
            </div>
          </div>
          <div className="grid min-w-0 grid-cols-12 bg-primary-background lg:block lg:p-8 lg:col-span-3">
            <div className="col-[2/-2] flex h-full flex-col gap-8 py-8 lg:py-0">
              <div className="relative aspect-3/2 overflow-hidden lg:aspect-auto lg:h-79">
                <img alt="" loading="lazy" width="1374" height="948" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} sizes="(min-width: 1728px) 450px, (min-width: 1024px) 35vw, (min-width: 768px) 50vw, 100vw" srcSet="/img/img-53ac7a97f3.avif 256w, /img/img-53ac7a97f3.avif 384w, /img/img-53ac7a97f3.avif 640w, /img/img-53ac7a97f3.avif 750w, /img/img-53ac7a97f3.avif 828w, /img/img-53ac7a97f3.avif 1080w, /img/img-53ac7a97f3.avif 1200w, /img/img-53ac7a97f3.avif 1920w, /img/img-53ac7a97f3.avif 2048w, /img/img-53ac7a97f3.avif 3840w" src="/img/img-53ac7a97f3.avif" />
              </div>
              <div>
                <h3 className="font-semibold text-lg text-secondary-foreground max-md:text-base">
                  {"Everyone sees the same numbers."}
                </h3>
                <p className="mt-1.5 text-tertiary-foreground max-md:text-sm">
                  {"Share a dashboard with your workspace or another team."}
                </p>
              </div>
            </div>
          </div>
          <div className="grid min-w-0 grid-cols-12 bg-primary-background lg:block lg:p-8 lg:col-span-5">
            <div className="col-[2/-2] flex h-full flex-col gap-8 py-8 lg:py-0">
              <div className="relative aspect-3/2 overflow-hidden lg:aspect-auto lg:h-79">
                <img alt="" loading="lazy" width="2418" height="948" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} sizes="(min-width: 1728px) 800px, (min-width: 1024px) 60vw, (min-width: 768px) 50vw, 100vw" srcSet="/img/img-01a7f6838b.avif 384w, /img/img-01a7f6838b.avif 640w, /img/img-01a7f6838b.avif 750w, /img/img-01a7f6838b.avif 828w, /img/img-01a7f6838b.avif 1080w, /img/img-01a7f6838b.avif 1200w, /img/img-01a7f6838b.avif 1920w, /img/img-01a7f6838b.avif 2048w, /img/img-01a7f6838b.avif 3840w" src="/img/img-01a7f6838b.avif" />
              </div>
              <div>
                <h3 className="font-semibold text-lg text-secondary-foreground max-md:text-base">
                  {"Nix the weekly slide deck."}
                </h3>
                <p className="mt-1.5 text-tertiary-foreground max-md:text-sm">
                  {"A live board your whole team can see, arranged by how you actually work."}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
