// Generated by scripts/port.ts. Hand edits are expected from here on.
import { ShelfTrilogySplit, type TrilogyItem } from "./shelf-trilogy";

const ITEMS: TrilogyItem[] = [
  { title: "Rewind to any day.", description: "Compare periods, measure velocity, see exactly where you stood.", image: { src: "/img/img-0f74732563.avif", width: 2088, height: 2562 } },
  { title: "Know if you're ahead.", description: "A goal line runs across the chart to track your targets.", image: { src: "/img/img-5ca91bb16a.avif", width: 1392, height: 1708 } },
  { title: "Down to the record.", description: "Click a number to see the records behind the trend.", image: { src: "/img/img-83c73bb175.avif", width: 1392, height: 1708 } },
];

export function OpenTheNumber() {
  return (
    <div className="container flex flex-1 flex-col max-lg:contents">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none">
        <div className="h-16 lg:h-32" />
        <svg width="100%" height="1" className="text-subtle-stroke">
          <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
        </svg>
        <div className="px-8 py-12 lg:hidden [@media(max-height:700px)]:block">
          <div className="max-w-[20em] text-pretty text-start font-medium text-heading-responsive-md leading-[1.15] [&>p]:text-black-700">
            <h2 className="text-pretty inline">
              {"Open the number."}
            </h2>
            {" "}
            <p className="inline text-pretty font-medium text-black-800">
              {"See how it moved, and the deals that moved it."}
            </p>
          </div>
        </div>
        <ShelfTrilogySplit
          id="trilogy-c8235864-4dd6-451f-b007-e7d6dd687d17"
          items={ITEMS}
          header={
            <div className="text-pretty text-start hidden max-w-120 font-medium text-heading-responsive-md leading-[1.15] lg:block [&>p]:text-black-700 [@media(max-height:700px)]:hidden">
              <h2 className="text-pretty inline">
                {"Open the number."}
              </h2>
              {" "}
              <p className="inline text-pretty font-medium text-black-800">
                {"See how it moved, and the deals that moved it."}
              </p>
            </div>
          }
        />
      </div>
    </div>
  );
}
