// Generated by scripts/port.ts. Hand edits are expected from here on.
import { PromptsScroll, PromptsRow } from "../ask/prompts-scroll";
export function TheJudgmentCallsOnly() {
  return (
    <div className="container flex flex-1 flex-col max-lg:contents relative overflow-hidden">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none relative overflow-hidden">
        <div className="h-16 lg:h-32" />
        <svg width="100%" height="1" className="text-subtle-stroke">
          <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
        </svg>
        <div aria-hidden="true" className="size-full mask-t-from-20% mask-t-to-100% pointer-events-none absolute inset-0 text-weak-stroke" style={{"backgroundImage":"linear-gradient(to right, transparent calc(50% - 0.5px), currentColor calc(50% - 0.5px) calc(50% + 0.5px), transparent calc(50% + 0.5px))","backgroundPosition":"center","backgroundRepeat":"repeat","backgroundSize":"8px 100%"}} />
        <header className="grid grid-cols-12 max-xl:pt-30 max-xl:pb-16 max-lg:pt-25 max-lg:pb-15 justify-items-center relative pt-16 pb-10 lg:pt-30 lg:pb-24">
          <div className="text-pretty text-center col-[2/-2] mix-blend-multiply dark:mix-blend-screen max-w-192 font-medium text-heading-responsive-md [&>p]:text-black-700">
            <h2 className="text-pretty inline">
              {"The judgment calls only your team knows how to make."}
            </h2>
            {" "}
            <p className="inline text-pretty font-medium text-black-800">
              {"Running at a whole new scale."}
            </p>
          </div>
        </header>
        <PromptsScroll className="flex flex-col items-center overflow-hidden py-16 relative pt-0 pb-16 lg:pb-30">
          <div className="flex flex-col gap-y-5 max-lg:scale-80 max-md:scale-70">
            <div className="relative">
              <PromptsRow row={1}>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-fe5c46fd1a.avif 1x, /img/img-fe5c46fd1a.avif 2x" src="/img/img-fe5c46fd1a.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Lead Scorer Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Is this actually a fit? Scored against your own ICP."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-fd4dfc913f.avif 1x, /img/img-fd4dfc913f.avif 2x" src="/img/img-fd4dfc913f.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Overnight Digest Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Decides what deserves your morning, and says why."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-2f9c723c6c.avif 1x, /img/img-2f9c723c6c.avif 2x" src="/img/img-2f9c723c6c.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Meeting Prep Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Reads the notes, calls, and emails, then says what matters."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-d5b2ca9b7f.avif 1x, /img/img-d5b2ca9b7f.avif 2x" src="/img/img-d5b2ca9b7f.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Competitor Watch Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Spots what changed on their site, and whether it matters."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-f57ecc7fc4.avif 1x, /img/img-f57ecc7fc4.avif 2x" src="/img/img-f57ecc7fc4.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Support Triage Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Reads the ticket, decides how urgent it is, sends it on."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-fe5c46fd1a.avif 1x, /img/img-fe5c46fd1a.avif 2x" src="/img/img-fe5c46fd1a.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Lead Scorer Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Is this actually a fit? Scored against your own ICP."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-fd4dfc913f.avif 1x, /img/img-fd4dfc913f.avif 2x" src="/img/img-fd4dfc913f.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Overnight Digest Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Decides what deserves your morning, and says why."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-2f9c723c6c.avif 1x, /img/img-2f9c723c6c.avif 2x" src="/img/img-2f9c723c6c.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Meeting Prep Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Reads the notes, calls, and emails, then says what matters."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-d5b2ca9b7f.avif 1x, /img/img-d5b2ca9b7f.avif 2x" src="/img/img-d5b2ca9b7f.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Competitor Watch Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Spots what changed on their site, and whether it matters."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-f57ecc7fc4.avif 1x, /img/img-f57ecc7fc4.avif 2x" src="/img/img-f57ecc7fc4.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Support Triage Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Reads the ticket, decides how urgent it is, sends it on."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </PromptsRow>
            </div>
            <div className="relative" style={{"transform":"translateX(-128.5px)"}}>
              <PromptsRow row={2}>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-7b01149b47.avif 1x, /img/img-7b01149b47.avif 2x" src="/img/img-7b01149b47.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Deal Risk Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Notices a deal has gone quiet, and works out why."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-5f8c88e7ca.avif 1x, /img/img-5f8c88e7ca.avif 2x" src="/img/img-5f8c88e7ca.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Call Coach Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Grades the call against your own scorecard."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-bf894f2ba4.avif 1x, /img/img-bf894f2ba4.avif 2x" src="/img/img-bf894f2ba4.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Win/Loss Notes Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Works out the real reason, in your categories."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-fea456ea2a.avif 1x, /img/img-fea456ea2a.avif 2x" src="/img/img-fea456ea2a.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Onboarding Plan Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Turns a kickoff call into the tasks that actually follow."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-d0ead14533.avif 1x, /img/img-d0ead14533.avif 2x" src="/img/img-d0ead14533.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Expansion Signal Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Reads the usage, decides if it's an upsell, drafts the note."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-7b01149b47.avif 1x, /img/img-7b01149b47.avif 2x" src="/img/img-7b01149b47.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Deal Risk Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Notices a deal has gone quiet, and works out why."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-5f8c88e7ca.avif 1x, /img/img-5f8c88e7ca.avif 2x" src="/img/img-5f8c88e7ca.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Call Coach Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Grades the call against your own scorecard."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-bf894f2ba4.avif 1x, /img/img-bf894f2ba4.avif 2x" src="/img/img-bf894f2ba4.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Win/Loss Notes Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Works out the real reason, in your categories."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-fea456ea2a.avif 1x, /img/img-fea456ea2a.avif 2x" src="/img/img-fea456ea2a.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Onboarding Plan Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Turns a kickoff call into the tasks that actually follow."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-64 shrink-0 rounded-xl border border-black-100/5 backdrop-blur-xs">
                  <div className="flex flex-col overflow-hidden rounded-[calc(12px-1px)] bg-white-100 shadow-joshuattio-4">
                    <div className="flex flex-col gap-2 p-3">
                      <img alt="" loading="lazy" width="80" height="80" decoding="async" data-nimg="1" className="size-5 object-contain" style={{"color":"transparent"}} srcSet="/img/img-d0ead14533.avif 1x, /img/img-d0ead14533.avif 2x" src="/img/img-d0ead14533.avif" />
                      <div className="flex h-13 flex-col gap-0.5 pr-9">
                        <p className="truncate font-medium text-[#242629] text-sm leading-5 tracking-[-0.14px]">
                          {"Expansion Signal Agent"}
                        </p>
                        <p className="line-clamp-2 text-[rgba(0,0,0,0.4)] text-xs leading-4">
                          {"Reads the usage, decides if it's an upsell, drafts the note."}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center justify-between px-3 pb-2.5">
                      <div className="flex items-center gap-1.5">
                        <div className="relative size-4 overflow-hidden rounded-[30%] border border-[rgba(0,0,0,0.05)]">
                          <img alt="" loading="lazy" width="64" height="64" decoding="async" data-nimg="1" className="size-full object-cover" style={{"color":"transparent"}} srcSet="/img/img-92fa9cd2b7.avif 1x, /img/img-92fa9cd2b7.avif 2x" src="/img/img-92fa9cd2b7.avif" />
                        </div>
                        <span className="font-medium text-[#505155] text-xs leading-4">
                          {"Joshuattio"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </PromptsRow>
            </div>
          </div>
        </PromptsScroll>
        <svg width="100%" height="1" className="text-subtle-stroke">
          <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
        </svg>
      </div>
    </div>
  );
}
