// Generated by scripts/port.ts. Hand edits are expected from here on.
import { UcHorizontalScroll } from "../universal-context/uc-horizontal-scroll";

export function EnrichedDataThatGoes() {
  return (
    <div className="container flex flex-1 flex-col max-lg:contents">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none">
        <div className="h-16 lg:h-32" />
        <svg width="100%" height="1" className="text-subtle-stroke">
          <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
        </svg>
        <header className="grid max-xl:pt-30 max-xl:pb-16 max-lg:pt-25 max-lg:pb-15 justify-items-start grid-cols-24 pt-20 pb-15 lg:pt-30 lg:pb-32 [&>div]:col-[3/-3] [&>div]:w-full lg:[&>div]:col-[2/-2]">
          <div className="col-[2/-2]">
            <div className="flex flex-col items-start gap-6 lg:flex-row lg:items-end lg:justify-between">
              <div className="text-pretty text-start max-w-192 font-medium text-heading-responsive-md [&>p]:text-black-700">
                <h2 className="text-pretty inline">
                  {"Enriched data that goes to work."}
                </h2>
                {" "}
                <p className="inline text-pretty font-medium text-black-800">
                  {"Every detail sharpens Universal Context, and is ready to filter, sort, report on, or trigger agents."}
                </p>
              </div>
            </div>
          </div>
        </header>
        <UcHorizontalScroll>
            <div className="grid w-max min-w-full auto-cols-[280px] grid-flow-col px-[8.333%] lg:w-full lg:auto-cols-fr lg:px-[4.167%]">
              <article className="flex snap-start flex-col border-subtle-stroke border-l">
                <div className="min-h-59 grow px-4 pb-12">
                  <h3 className="text-lg text-secondary-foreground">
                    {"Route by fit."}
                  </h3>
                  <p className="mt-1 text-accent-foreground text-base">
                    {"Send accounts to the right rep the moment they arrive."}
                  </p>
                </div>
                <div aria-hidden="true" className="flex h-8 justify-evenly">
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                </div>
              </article>
              <article className="flex snap-start flex-col border-subtle-stroke border-l">
                <div className="min-h-59 grow px-4 pb-12">
                  <h3 className="text-lg text-secondary-foreground">
                    {"Let lists build themselves."}
                  </h3>
                  <p className="mt-1 text-accent-foreground text-base">
                    {"Segment by enriched fields, and the list updates when your data does."}
                  </p>
                </div>
                <div aria-hidden="true" className="flex h-8 justify-evenly">
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                </div>
              </article>
              <article className="flex snap-start flex-col border-subtle-stroke border-l">
                <div className="min-h-59 grow px-4 pb-12">
                  <h3 className="text-lg text-secondary-foreground">
                    {"Trigger on signal."}
                  </h3>
                  <p className="mt-1 text-accent-foreground text-base">
                    {"Kick off a sequence when an account crosses a milestone."}
                  </p>
                </div>
                <div aria-hidden="true" className="flex h-8 justify-evenly">
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                </div>
              </article>
              <article className="flex snap-start flex-col border-subtle-stroke border-l">
                <div className="min-h-59 grow px-4 pb-12">
                  <h3 className="text-lg text-secondary-foreground">
                    {"Report on what's real."}
                  </h3>
                  <p className="mt-1 text-accent-foreground text-base">
                    {"Slice your pipeline without any manual searching."}
                  </p>
                </div>
                <div aria-hidden="true" className="flex h-8 justify-evenly">
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                  <div className="w-0 overflow-visible">
                    <svg width="1" height="100%" className="text-subtle-stroke">
                      <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                    </svg>
                  </div>
                </div>
              </article>
            </div>
        </UcHorizontalScroll>
      </div>
    </div>
  );
}
