// Generated by scripts/port.ts. Hand edits are expected from here on.
import "./enrichment.css";

export function JoshuattioPlugsInYou() {
  return (
    <div className="container flex flex-1 flex-col max-lg:contents">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none">
        <div className="h-16 lg:h-32" />
        <svg width="100%" height="1" className="text-subtle-stroke">
          <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
        </svg>
        <div className="grid lg:grid-cols-[13fr_11fr]">
          <div className="px-[8.333%] py-16 lg:px-[7.692%] lg:py-14.5">
            <div className="text-pretty text-start max-w-130 font-medium text-heading-responsive-md [&>p]:text-black-700">
              <h2 className="text-pretty inline">
                {"Joshuattio plugs in. You take off."}
              </h2>
              {" "}
              <p className="inline text-pretty font-medium text-black-800">
                {"Work your way"}
                <span className="enrichment-tablet-hide">{", from outreach"}</span>
                {" to outcomes."}
              </p>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-px border-subtle-stroke border-t bg-subtle-stroke lg:border-t-0 lg:border-l">
            <a className="group relative flex flex-col justify-between bg-primary-background h-34 p-6 lg:p-8 max-md:h-30" href="/platform/ask">
              <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
              <p className="relative text-overline">
                {"[0"}
                {"1"}
                {"]"}
              </p>
              <div className="relative flex items-end justify-between">
                <h3 className="relative text-balance">
                  {"Ask Joshuattio"}
                </h3>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative mb-1 shrink-0 text-caption-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                  <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                </svg>
              </div>
            </a>
            <a className="group relative flex flex-col justify-between bg-primary-background h-34 p-6 lg:p-8 max-md:h-30" href="/platform/ai">
              <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
              <p className="relative text-overline">
                {"[0"}
                {"2"}
                {"]"}
              </p>
              <div className="relative flex items-end justify-between">
                <h3 className="relative text-balance">
                  {"AI"}
                </h3>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative mb-1 shrink-0 text-caption-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                  <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                </svg>
              </div>
            </a>
            <a className="group relative flex flex-col justify-between bg-primary-background h-34 p-6 lg:p-8 max-md:h-30" href="/platform/data">
              <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
              <p className="relative text-overline">
                {"[0"}
                {"3"}
                {"]"}
              </p>
              <div className="relative flex items-end justify-between">
                <h3 className="relative text-balance">
                  {"Data model"}
                </h3>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative mb-1 shrink-0 text-caption-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                  <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                </svg>
              </div>
            </a>
            <a className="group relative flex flex-col justify-between bg-primary-background h-34 p-6 lg:p-8 max-md:h-30" href="/apps">
              <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
              <p className="relative text-overline">
                {"[0"}
                {"4"}
                {"]"}
              </p>
              <div className="relative flex items-end justify-between">
                <h3 className="relative text-balance">
                  {"Apps & integrations"}
                </h3>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative mb-1 shrink-0 text-caption-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                  <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                </svg>
              </div>
            </a>
            <a className="group relative flex flex-col justify-between bg-primary-background h-34 p-6 lg:p-8 max-md:h-30" href="/platform/call-intelligence">
              <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
              <p className="relative text-overline">
                {"[0"}
                {"5"}
                {"]"}
              </p>
              <div className="relative flex items-end justify-between">
                <h3 className="relative text-balance">
                  {"Call Intelligence"}
                </h3>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative mb-1 shrink-0 text-caption-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                  <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                </svg>
              </div>
            </a>
            <a className="group relative flex flex-col justify-between bg-primary-background h-34 p-6 lg:p-8 max-md:h-30" href="/platform/automations">
              <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
              <p className="relative text-overline">
                {"[0"}
                {"6"}
                {"]"}
              </p>
              <div className="relative flex items-end justify-between">
                <h3 className="relative text-balance">
                  {"Workflows"}
                </h3>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative mb-1 shrink-0 text-caption-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                  <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                </svg>
              </div>
            </a>
            <a className="group relative flex flex-col justify-between bg-primary-background h-34 p-6 lg:p-8 max-md:h-30" href="/platform/sequences">
              <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
              <p className="relative text-overline">
                {"[0"}
                {"7"}
                {"]"}
              </p>
              <div className="relative flex items-end justify-between">
                <h3 className="relative text-balance">
                  {"Sequences"}
                </h3>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative mb-1 shrink-0 text-caption-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                  <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                </svg>
              </div>
            </a>
            <a className="group relative flex flex-col justify-between bg-primary-background h-34 p-6 lg:p-8 max-md:h-30" href="/platform/reporting">
              <div className="pointer-events-none absolute inset-0 bg-secondary-background opacity-0 transition-opacity duration-300 ease-in-out group-hover:opacity-80 group-hover:duration-50 group-active:opacity-100 group-active:duration-50" />
              <p className="relative text-overline">
                {"[0"}
                {"8"}
                {"]"}
              </p>
              <div className="relative flex items-end justify-between">
                <h3 className="relative text-balance">
                  {"Reporting"}
                </h3>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="relative mb-1 shrink-0 text-caption-foreground opacity-0 -translate-x-0.25 transition-[opacity,translate] duration-400 ease-in-out group-hover:translate-0 group-hover:opacity-100 group-hover:duration-150 group-active:translate-0 group-active:opacity-100 group-active:duration-50">
                  <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                </svg>
              </div>
            </a>
          </div>
        </div>
        <svg width="100%" height="1" className="text-subtle-stroke">
          <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
        </svg>
        <div className="h-16 lg:h-32" />
      </div>
    </div>
  );
}
