// Generated by scripts/port.ts. Hand edits are expected from here on.
import { MobileCopy } from "../story/mobile-copy";
import { StoryHeaderVideo } from "../story/header-video";
import { StoryProgressTracker } from "../story/progress-tracker";
export function HowGranolaTurnsProduct() {
  return (
    <div className="container">
      <div className="border-subtle-stroke border-x">
        <article>
          <aside className="relative grid h-28 grid-cols-12 grid-rows-1">
            <div className="relative col-span-6 col-start-2 flex h-full items-end pb-5">
              <p className="text-overline">
                <a className="transition-colors hover:text-accent-foreground active:text-tertiary-foreground active:duration-0" href="/customers">
                  {"Customers"}
                </a>
                {" "}
                {"/ "}
                <span className="text-black-800">
                  {"Granola"}
                </span>
              </p>
            </div>
            <div className="relative col-span-4 hidden h-full items-end justify-center pb-5 xl:flex">
              <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
                <defs>
                  <pattern id="_S_1_" width="10" height="10" patternUnits="userSpaceOnUse">
                    <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
                  </pattern>
                </defs>
                <rect width="100%" height="100%" fill="url(#_S_1_)" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke absolute inset-y-0 left-0 hidden lg:block">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke absolute inset-y-0 right-0">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
            <div className="relative col-span-4 flex h-full items-end justify-end pb-5 xl:col-span-1 xl:justify-center">
              <p className="text-overline">
                {"[CS "}
                {"06"}
                {"]"}
              </p>
            </div>
          </aside>
          <header className="relative flex flex-col xl:hidden">
            <div className="relative grid w-full grid-cols-12">
              <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
                <defs>
                  <pattern id="_S_2_" width="10" height="10" patternUnits="userSpaceOnUse">
                    <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
                  </pattern>
                </defs>
                <rect width="100%" height="100%" fill="url(#_S_2_)" />
              </svg>
              <svg width="100%" height="1" className="text-subtle-stroke absolute inset-x-0 top-0">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <svg width="100%" height="1" className="text-subtle-stroke absolute inset-x-0 bottom-0">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <div className="flex items-center justify-center rounded-xl border bg-white-100 p-2 relative col-span-full aspect-video w-full md:col-[2/-2]" style={{"boxShadow":"0px 6px 20px -2px #1C284014, 0px 2px 6px 0px #1C28400F"}}>
                <StoryHeaderVideo className="size-full rounded-lg object-cover" preview="/media/vid-347131dcec.mp4" video="https://vimeo.com/1143083730" />
              </div>
            </div>
            <div className="grid grid-cols-12">
              <div className="col-[2/-2] py-15">
                <div>
                  <h1 className="text-balance text-heading-responsive-lg">
                    {"How Granola turns product signals into revenue at scale"}
                  </h1>
                  <div className="mt-12">
                    <p className="text-black-800 text-overline">
                      {"A conversation with"}
                    </p>
                    <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2">
                      <div className="ml-5 flex items-center">
                        <div className="-ml-5 flex size-20 items-center justify-center">
                          <img alt="" width="288" height="288" decoding="async" data-nimg="1" className="size-full object-contain" style={{"color":"transparent"}} sizes="80px" srcSet="/img/img-769c690bb0.avif 32w, /img/img-769c690bb0.avif 48w, /img/img-769c690bb0.avif 64w, /img/img-769c690bb0.avif 96w, /img/img-769c690bb0.avif 128w, /img/img-769c690bb0.avif 256w, /img/img-769c690bb0.avif 384w, /img/img-769c690bb0.avif 640w, /img/img-769c690bb0.avif 750w, /img/img-769c690bb0.avif 828w, /img/img-769c690bb0.avif 1080w, /img/img-769c690bb0.avif 1200w, /img/img-769c690bb0.avif 1920w, /img/img-769c690bb0.avif 2048w, /img/img-769c690bb0.avif 3840w" src="/img/img-769c690bb0.avif" />
                        </div>
                      </div>
                      <div className="flex flex-col">
                        <p>
                          <span className="font-bold text-secondary-foreground">
                            {"Shreman Shrestha"}
                          </span>
                          <br />
                          <span className="font-medium text-secondary-foreground">
                            {"Head of Business"}
                          </span>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </header>
          <header className="relative hidden grid-cols-12 items-stretch xl:grid" aria-hidden="true">
            <svg width="100%" height="1" className="text-subtle-stroke absolute inset-x-0 top-0 col-span-full">
              <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
            <svg width="100%" height="1" className="text-subtle-stroke absolute inset-x-0 bottom-0 col-span-full">
              <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
            <div className="relative col-[2/8] flex items-center py-15 pr-6">
              <div>
                <h1 className="text-balance text-heading-responsive-lg">
                  {"How Granola turns product signals into revenue at scale"}
                </h1>
                <div className="mt-12">
                  <p className="text-black-800 text-overline">
                    {"A conversation with"}
                  </p>
                  <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2">
                    <div className="ml-5 flex items-center">
                      <div className="-ml-5 flex size-20 items-center justify-center">
                        <img alt="" width="288" height="288" decoding="async" data-nimg="1" className="size-full object-contain" style={{"color":"transparent"}} sizes="80px" srcSet="/img/img-769c690bb0.avif 32w, /img/img-769c690bb0.avif 48w, /img/img-769c690bb0.avif 64w, /img/img-769c690bb0.avif 96w, /img/img-769c690bb0.avif 128w, /img/img-769c690bb0.avif 256w, /img/img-769c690bb0.avif 384w, /img/img-769c690bb0.avif 640w, /img/img-769c690bb0.avif 750w, /img/img-769c690bb0.avif 828w, /img/img-769c690bb0.avif 1080w, /img/img-769c690bb0.avif 1200w, /img/img-769c690bb0.avif 1920w, /img/img-769c690bb0.avif 2048w, /img/img-769c690bb0.avif 3840w" src="/img/img-769c690bb0.avif" />
                      </div>
                    </div>
                    <div className="flex flex-col">
                      <p>
                        <span className="font-bold text-secondary-foreground">
                          {"Shreman Shrestha"}
                        </span>
                        <br />
                        <span className="font-medium text-secondary-foreground">
                          {"Head of Business"}
                        </span>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="relative col-[8/-2] flex items-center justify-center">
              <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
                <defs>
                  <pattern id="_S_3_" width="10" height="10" patternUnits="userSpaceOnUse">
                    <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
                  </pattern>
                </defs>
                <rect width="100%" height="100%" fill="url(#_S_3_)" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke absolute inset-y-0 left-0">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke absolute inset-y-0 right-0">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <div className="flex items-center justify-center rounded-xl border bg-white-100 p-2 relative aspect-5/4 size-full" style={{"boxShadow":"0px 6px 20px -2px #1C284014, 0px 2px 6px 0px #1C28400F"}}>
                <StoryHeaderVideo className="size-full rounded-lg object-cover" preview="/media/vid-347131dcec.mp4" video="https://vimeo.com/1143083730" />
              </div>
            </div>
          </header>
          <aside className="relative hidden h-15 grid-cols-12 *:relative *:flex *:h-full *:items-end xl:grid">
            <div className="col-[4/8]">
              <svg width="1" height="100%" className="text-subtle-stroke absolute inset-y-0 -left-px">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
            <div className="col-[8/12]">
              <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
                <defs>
                  <pattern id="_S_4_" width="10" height="10" patternUnits="userSpaceOnUse">
                    <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
                  </pattern>
                </defs>
                <rect width="100%" height="100%" fill="url(#_S_4_)" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke absolute inset-y-0 left-0">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke absolute inset-y-0 right-0">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
          </aside>
          <svg width="100%" height="1" className="text-subtle-stroke w-full">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
          </svg>
          <div className="relative grid grid-cols-12">
            <aside className="relative col-span-full row-start-1 border-subtle-stroke bg-secondary-background py-22 xl:col-span-3 xl:border-r">
              <div className="grid grid-cols-12 xl:px-9 sticky top-[calc(var(--site-header-height)+48px)]">
                <img alt="Granola" loading="lazy" width="124" height="27" decoding="async" data-nimg="1" className="col-[2/-2] h-7 w-auto object-contain object-left xl:col-[1/-1]" style={{"color":"transparent"}} src="/img/img-cdccc1683f.svg" />
                <div className="col-[2/-2] mt-8 grid grid-cols-2 gap-x-6 gap-y-3 lg:gap-x-12 xl:col-[1/-1] xl:grid-cols-1">
                  <div className="col-span-full max-w-full lg:max-w-[50%] xl:max-w-full">
                    <h2 className="font-semibold text-secondary-foreground">
                      {"About"}
                    </h2>
                    <span className="mt-1 inline-block text-balance text-sm text-tertiary-foreground">
                      {"Granola is the AI notepad for people in back-to-back meetings."}
                    </span>
                  </div>
                  <div className="col-span-full mt-2 max-w-full lg:max-w-[50%] xl:max-w-full">
                    <h2 className="font-semibold text-secondary-foreground">
                      {"Industry"}
                    </h2>
                    <span className="mt-1 inline-block text-sm text-tertiary-foreground">
                      {"SaaS"}
                    </span>
                  </div>
                  <div>
                    <h2 className="font-semibold text-secondary-foreground">
                      {"Company size"}
                    </h2>
                    <span className="mt-1 inline-block text-sm text-tertiary-foreground">
                      {"100-200"}
                    </span>
                  </div>
                  <div>
                    <h2 className="font-semibold text-secondary-foreground">
                      {"Headquarters"}
                    </h2>
                    <span className="mt-1 inline-block text-sm text-tertiary-foreground">
                      {"London, UK"}
                    </span>
                  </div>
                  <div>
                    <h2 className="font-semibold text-secondary-foreground">
                      {"Founded"}
                    </h2>
                    <span className="mt-1 inline-block text-sm text-tertiary-foreground">
                      {"2023"}
                    </span>
                  </div>
                  <div className="col-span-full mt-2">
                    <h2 className="font-semibold text-secondary-foreground">
                      {"Key features"}
                    </h2>
                    <div className="mt-1.5 flex flex-col gap-2">
                      <a className="group relative flex w-full items-center gap-2 text-sm text-tertiary-foreground" href="/platform/automations">
                        <img alt="Workflows" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" className="size-[14px]" style={{"color":"transparent"}} src="/img/img-a87f2e1f84.svg" />
                        <p>
                          {"Workflows"}
                        </p>
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="size-3.5 -translate-x-1 opacity-0 transition-[opacity,translate] duration-300 ease-in-out group-hover:translate-x-0 group-hover:opacity-100">
                          <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                        </svg>
                      </a>
                      <a className="group relative flex w-full items-center gap-2 text-sm text-tertiary-foreground" href="/apps">
                        <img alt="Integrations" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" className="size-[14px]" style={{"color":"transparent"}} src="/img/img-f865377ad1.svg" />
                        <p>
                          {"Integrations"}
                        </p>
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="size-3.5 -translate-x-1 opacity-0 transition-[opacity,translate] duration-300 ease-in-out group-hover:translate-x-0 group-hover:opacity-100">
                          <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                        </svg>
                      </a>
                      <a className="group relative flex w-full items-center gap-2 text-sm text-tertiary-foreground" href="/platform/data">
                        <img alt="Custom objects" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" className="size-[14px]" style={{"color":"transparent"}} src="/img/img-f737603fd3.svg" />
                        <p>
                          {"Custom objects"}
                        </p>
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="size-3.5 -translate-x-1 opacity-0 transition-[opacity,translate] duration-300 ease-in-out group-hover:translate-x-0 group-hover:opacity-100">
                          <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                        </svg>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <svg width="100%" height="1" className="text-subtle-stroke absolute inset-x-0 bottom-0 xl:hidden">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
              </svg>
            </aside>
            <div className="relative col-span-full row-start-2 grid grid-cols-12 gap-y-12 xl:col-[4/-1] xl:row-start-1 xl:grid-cols-9">
              <div className="col-[2/-2] grid gap-6 pt-22 lg:grid-cols-2 lg:gap-12">
                <div>
                  <h2 className="mb-4 font-semibold text-lg">
                    {"Challenge"}
                  </h2>
                  <p className="text-pretty font-normal text-secondary-foreground">
                    {"Granola's inbox is inundated with inbound leads weekly but there's no systematic way to prioritize them. High-potential prospects sat in the inbox, product usage data lived in BI tools, and manual triage consumed hours with no path to scale."}
                  </p>
                </div>
                <div>
                  <h2 className="mb-4 font-semibold text-lg">
                    {"Solution"}
                  </h2>
                  <p className="text-pretty font-normal text-secondary-foreground">
                    {"Use Joshuattio to build an intelligent platform to capture every lead, tier them automatically, connect product signals to customer records, and power workflows that keep AEs focused on the highest-value opportunities."}
                  </p>
                </div>
              </div>
              <svg width="100%" height="1" className="text-subtle-stroke col-span-full w-full">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <div className="col-[2/-2] grid gap-x-6 gap-y-2 lg:grid-cols-2 lg:gap-x-12">
                <h2 className="col-span-full mb-2 font-semibold text-lg">
                  {"Results"}
                </h2>
                <li className="flex items-baseline gap-x-3">
                  <div className="size-2 shrink-0 rounded-xs bg-white-600" />
                  <p className="text-pretty font-normal">
                    {"Lead triage 83% faster. "}
                  </p>
                </li>
                <li className="flex items-baseline gap-x-3">
                  <div className="size-2 shrink-0 rounded-xs bg-white-600" />
                  <p className="text-pretty font-normal">
                    {"10X faster access to customer context."}
                  </p>
                </li>
                <li className="flex items-baseline gap-x-3">
                  <div className="size-2 shrink-0 rounded-xs bg-white-600" />
                  <p className="text-pretty font-normal">
                    {"5 hours per week saved with automated deal updates."}
                  </p>
                </li>
              </div>
              <svg width="100%" height="1" className="text-subtle-stroke col-span-full">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <div className="col-[2/-2] mt-12 mb-24 max-w-prose">
                <div className="font-normal leading-6.5">
                  <div>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      {"Granola is the AI notepad for people in back-to-back meetings. Following rapid growth, $192 million raised and a team scaled to over 40 people in under a year, they needed infrastructure to match their velocity. With Joshuattio, they built a platform to connect inbound "}<MobileCopy sm="">{"sales "}</MobileCopy>{"leads, product usage, enrichment, and conversations in one place, transforming their team into a scalable revenue engine."}
                    </p>
                    <h3 id="product-led-growth-needs-a-modern-tech-stack" className="scroll-my-24 relative not-first:mt-15 not-last:mb-2 font-semibold text-lg text-secondary-foreground">
                      {"Product-led growth needs a modern tech stack "}
                    </h3>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      {"Fast-growing, inbound-driven startups face a recurring challenge: how do you turn usage signals into revenue without slowing down? "}
                    </p>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      {"Granola was drowning in inbound lead but the sales team had no way to prioritize them. High-potential prospects sat in the inbox, product usage data lived in separate tools, and manual triage consumed hours with no clear path to scale."}
                    </p>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      {"They needed a system that could capture every lead automatically, connect product usage to customer records, and surface the highest-value opportunities without manual work. Joshuattio gave them that"}<MobileCopy sm=".">{" system."}</MobileCopy>
                    </p>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      <b className="in-[p]:font-semibold">
                        {"“The moment we started setting Joshuattio up, everything became clear. For the first time, we could "}<MobileCopy sm="">{"actually "}</MobileCopy>{"see all of our deals in one place.\""}
                      </b>
                    </p>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      {"With Joshuattio, Granola has built the complete GTM platform: inbound leads flowing in automatically, product signals synced to every customer record, and workflows routing prospects straight to AEs."}
                    </p>
                    <h3 id="triaging-inbound-at-scale-with-automated-workflows" className="scroll-my-24 relative not-first:mt-15 not-last:mb-2 font-semibold text-lg text-secondary-foreground">
                      {"Triaging inbound at scale with automated workflows"}
                    </h3>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      {"At Granola, every prospect comes through a Tally form on their website. The team uses a custom ‘Inbound Leads’ object to capture every response automatically in separate records. A Zapier integration then pipes that data straight into Joshuattio, where each lead lands in a structured view. "}
                    </p>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      <b className="in-[p]:font-semibold">
                        {"“Now, we have this one place where we can see existing deals and new companies that are interested in chatting to us. It felt like when you can see for the first time.” "}
                      </b>
                    </p>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      {"The GTM team reviews new entries daily, tiering them 1-3 by potential, and uses workflows to promote high-value leads directly into the Deals object pipeline. "}
                    </p>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      <b className="in-[p]:font-semibold">
                        {"“The Deals object is especially top of mind for our account executives, and having the workflow automatically qualifying and surfacing leads is a huge unlock for our sales team. It saves so much time.”"}
                      </b>
                    </p>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      {"The impact on Granola is tangible:"}
                    </p>
                    <ul className="not-first:mt-1.5 list-[square] pl-3.5 marker:text-white-600">
                      <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          {"Zero missed leads and 10X faster access to customer context "}
                        </p>
                      </li>
                      <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          {"Lead review down from 2 hours to 20 minutes daily with tiered workflows"}
                        </p>
                      </li>
                      <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          {"100% GTM team adoption with daily usage"}
                        </p>
                      </li>
                    </ul>
                    <h3 id="connecting-product-signals-to-sales-conversations" className="scroll-my-24 relative not-first:mt-15 not-last:mb-2 font-semibold text-lg text-secondary-foreground">
                      {"Connecting product signals to sales conversations"}
                    </h3>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      {"For Granola, understanding how customers use the product is critical. With Joshuattio, they use the Polytomic app to tap directly into their product usage data. Combined with Clay for enrichment, this setup transformed how their team operates."}
                    </p>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      <b className="in-[p]:font-semibold">
                        {"“Connecting our whole stack was a real lightbulb moment. Suddenly, we could see the right people, the right context, at the right time. That’s when Joshuattio felt magical.”"}
                      </b>
                    </p>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      {"Now, when anyone on the team views a company in Joshuattio, they instantly see: "}
                    </p>
                    <ul className="not-first:mt-1.5 list-[square] pl-3.5 marker:text-white-600">
                      <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          {"Active users"}
                        </p>
                      </li>
                      <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          {"Engagement levels"}
                        </p>
                      </li>
                      <li className="pt-1 pl-1.5 first:pt-1.5 [&:not(:has(ul,li))]:pb-1.5">
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          {"Usage patterns"}
                        </p>
                      </li>
                    </ul>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      <b className="in-[p]:font-semibold">
                        {"\"The first time I saw usage data sync in Joshuattio, I was like, damn. I felt like I had everything I needed to be able to understand what users I should be reaching out to.\""}
                      </b>
                    </p>
                    <h3 id="consolidating-customer-intelligence-in-one-platform" className="scroll-my-24 relative not-first:mt-15 not-last:mb-2 font-semibold text-lg text-secondary-foreground">
                      {"Consolidating customer intelligence in one platform"}
                    </h3>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      {"With total team adoption, automated lead workflows, and product usage data connected to every deal, Granola is ready to triple their GTM team while maintaining visibility across the entire pipeline. "}
                    </p>
                    <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                      <b className="in-[p]:font-semibold">
                        {"“When I think of revenue, I think of Joshuattio. It's become an indispensable "}<MobileCopy sm="tool">{"platform"}</MobileCopy>{" for understanding our users as we scale.\""}
                      </b>
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <StoryProgressTracker className="col-start-12 row-start-2 xl:row-start-1" />
          </div>
        </article>
      </div>
    </div>
  );
}
