// Generated by scripts/port.ts. Hand edits are expected from here on.
export function YouCanAlwaysCheck() {
  return (
    <div className="container flex flex-1 flex-col max-lg:contents">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none">
        <div className="h-16 lg:h-32" />
        <svg width="100%" height="1" className="text-subtle-stroke">
          <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
        </svg>
        <div className="px-8 pt-20 pb-10 lg:px-[4.167%] lg:pt-30">
          <div className="text-pretty text-start max-w-192 font-medium text-heading-responsive-md leading-[1.15] [&>p]:text-black-700">
            <h2 className="text-pretty inline">
              {"You can always check."}
            </h2>
            {" "}
            <p className="inline text-pretty font-medium text-black-800">
              {"Every answer arrives with its confidence, reasoning, and sources for you to review or rerun."}
            </p>
          </div>
        </div>
        <div className="grid border-subtle-stroke lg:grid-cols-3 border-t">
          <article className="flex min-w-0 flex-col gap-8 p-8 lg:border-t-0">
            <div className="relative aspect-400/316 overflow-hidden max-lg:mx-auto max-lg:w-full max-lg:max-w-100">
              <img alt="" loading="eager" width="1200" height="948" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-d3476291d0.avif 1x, /img/img-d3476291d0.avif 2x" src="/img/img-d3476291d0.avif" />
            </div>
            <div>
              <h3 className="text-lg text-secondary-foreground">
                {"It tells you when it's unsure."}
              </h3>
              <p className="mt-1 text-base text-black-800">
                {"A confidence rating on every answer, so nothing looks more certain than it is."}
              </p>
            </div>
          </article>
          <article className="flex min-w-0 flex-col gap-8 p-8 border-subtle-stroke border-t lg:border-l lg:border-t-0">
            <div className="relative aspect-400/316 overflow-hidden max-lg:mx-auto max-lg:w-full max-lg:max-w-100">
              <img alt="" loading="eager" width="1200" height="948" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-9ea0335575.avif 1x, /img/img-9ea0335575.avif 2x" src="/img/img-9ea0335575.avif" />
            </div>
            <div>
              <h3 className="text-lg text-secondary-foreground">
                {"It shows you where it looked."}
              </h3>
              <p className="mt-1 text-base text-black-800">
                {"Open the reasoning and the sources behind any result in one click."}
              </p>
            </div>
          </article>
          <article className="flex min-w-0 flex-col gap-8 p-8 border-subtle-stroke border-t lg:border-l lg:border-t-0">
            <div className="relative aspect-400/316 overflow-hidden max-lg:mx-auto max-lg:w-full max-lg:max-w-100">
              <img alt="" loading="eager" width="1200" height="948" decoding="async" data-nimg="1" className="absolute inset-0 size-full object-contain" style={{"color":"transparent"}} srcSet="/img/img-10ec251d2c.avif 1x, /img/img-10ec251d2c.avif 2x" src="/img/img-10ec251d2c.avif" />
            </div>
            <div>
              <h3 className="text-lg text-secondary-foreground">
                {"You decide when it runs."}
              </h3>
              <p className="mt-1 text-base text-black-800">
                {"One record, a whole column, or on a trigger inside a workflow."}
              </p>
            </div>
          </article>
        </div>
      </div>
    </div>
  );
}
