// Generated by scripts/port.ts. Hand edits are expected from here on.
export function EveryAccountSameStandard() {
  return (
    <div className="container flex flex-1 flex-col max-lg:contents">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none">
        <div className="h-16 lg:h-32" />
        <svg width="100%" height="1" className="text-subtle-stroke">
          <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
        </svg>
        <div className="grid grid-cols-12 lg:grid-cols-[13fr_11fr]">
          <div className="col-[2/-2] pt-25 pb-15 lg:col-start-1 lg:col-end-2 lg:px-[7.692%] lg:py-14.5">
            <div className="text-pretty text-start max-w-130 font-medium text-heading-responsive-md leading-[1.15] [&>p]:text-black-700">
              <h2 className="text-pretty inline">
                {"Every account, same standard."}
              </h2>
              {" "}
              <p className="inline text-pretty font-medium text-black-800">
                {"Not just the ten someone had time for."}
              </p>
            </div>
          </div>
          <div className="col-[1/-1] grid border-subtle-stroke border-t md:grid-cols-2 lg:col-start-2 lg:col-end-3 lg:border-t-0 lg:border-l">
            <article className="grid grid-cols-12 border-subtle-stroke py-8 md:min-h-64 md:p-8 lg:min-h-79.75 lg:max-xl:p-6">
              <div className="col-[2/-2] flex flex-col justify-between gap-6 md:col-[1/-1] md:gap-12">
                <p className="text-overline">
                  {"[ "}
                  {"Sales"}
                  {" ]"}
                </p>
                <div className="mt-auto flex flex-col gap-1">
                  <h3 className="text-lg">
                    {"Before the call."}
                  </h3>
                  <p className="text-accent-foreground text-base">
                    {"The news, round, and new exec, already on the record."}
                  </p>
                </div>
              </div>
            </article>
            <article className="grid grid-cols-12 border-subtle-stroke py-8 md:min-h-64 md:p-8 lg:min-h-79.75 lg:max-xl:p-6 border-t md:border-t-0 md:border-l">
              <div className="col-[2/-2] flex flex-col justify-between gap-6 md:col-[1/-1] md:gap-12">
                <p className="text-overline">
                  {"[ "}
                  {"Marketing"}
                  {" ]"}
                </p>
                <div className="mt-auto flex flex-col gap-1">
                  <h3 className="text-lg">
                    {"Before the list."}
                  </h3>
                  <p className="text-accent-foreground text-base">
                    {"Build lists on live signals instead of stale fields."}
                  </p>
                </div>
              </div>
            </article>
            <article className="grid grid-cols-12 border-subtle-stroke py-8 md:min-h-64 md:p-8 lg:min-h-79.75 lg:max-xl:p-6 border-t md:border-t">
              <div className="col-[2/-2] flex flex-col justify-between gap-6 md:col-[1/-1] md:gap-12">
                <p className="text-overline">
                  {"[ "}
                  {"Customer Success"}
                  {" ]"}
                </p>
                <div className="mt-auto flex flex-col gap-1">
                  <h3 className="text-lg">
                    {"Before the renewal."}
                  </h3>
                  <p className="text-accent-foreground text-base">
                    {"Company changes surfaced while you can still act."}
                  </p>
                </div>
              </div>
            </article>
            <article className="grid grid-cols-12 border-subtle-stroke py-8 md:min-h-64 md:p-8 lg:min-h-79.75 lg:max-xl:p-6 border-t md:border-l md:border-t">
              <div className="col-[2/-2] flex flex-col justify-between gap-6 md:col-[1/-1] md:gap-12">
                <p className="text-overline">
                  {"[ "}
                  {"RevOps"}
                  {" ]"}
                </p>
                <div className="mt-auto flex flex-col gap-1">
                  <h3 className="text-lg">
                    {"Before the forecast."}
                  </h3>
                  <p className="text-accent-foreground text-base">
                    {"The same rules applied to every record in the system."}
                  </p>
                </div>
              </div>
            </article>
          </div>
        </div>
        <svg width="100%" height="1" className="text-subtle-stroke">
          <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeLinecap="round" />
        </svg>
        <div className="h-16 lg:h-32" />
      </div>
    </div>
  );
}
