// Generated by scripts/port.ts. Hand edits are expected from here on.
import { QuoteWordReveal } from "@/components/pages/customers/quote-reveal";
import { QuoteWordRevealSm } from "./quote-reveal-sm";

// Brand copy: the separator dash in the quote is a comma here.
const QUOTE =
  "Joshuattio’s developer experience is a breath of fresh air. The team is outstanding to work with, we’re thrilled for Sequence to be part of the Joshuattio App Store.";

export function Block() {
  return (
    <div className="container">
      <div className="border-subtle-stroke border-x">
        <div className="relative grid grid-cols-12">
          <div className="col-[2/-2] border-subtle-stroke border-x max-lg:hidden">
            <div className="relative grid grid-cols-10 grid-rows-[36px_300px_56px] items-center pt-15 max-xl:grid-rows-[14px_300px_12px]">
              <p className="col-[4/-1] text-overline">
                {"Joshuattio App Partners"}
              </p>
              <img alt="Riya Grover" loading="lazy" width="900" height="1100" decoding="async" data-nimg="1" className="col-[1/4] row-2 size-60 max-w-none justify-self-center object-contain max-xl:size-50" style={{"color":"transparent"}} srcSet="/img/img-f912474121.png 1x, /img/img-f912474121.png 2x" src="/img/img-f912474121.png" />
              <div className="col-[4/-2] row-2 flex flex-col gap-7">
                <QuoteWordReveal quote={QUOTE} />
                <p className="font-medium text-secondary-foreground text-sm">
                  <span className="font-bold">
                    {"Riya Grover"}
                  </span>
                  {" · "}
                  {"Co-founder & CEO, Sequence"}
                </p>
              </div>
              <svg width="100%" height="1" className="text-subtle-stroke absolute top-0 row-3 max-xl:hidden">
                <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <div className="col-[1/4] flex items-center justify-evenly overflow-hidden max-xl:hidden">
                <svg width="1" height="100%" className="text-subtle-stroke invisible">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeLinecap="round" />
                </svg>
                <p className="whitespace-nowrap text-center font-semibold text-black-800 text-sm">
                  {"Riya’s favorite features"}
                </p>
                <svg width="1" height="100%" className="text-subtle-stroke h-14">
                  <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
                </svg>
              </div>
              <div className="col-[4/-1] row-3 flex items-center gap-8 max-xl:hidden">
                <div className="flex shrink-0 items-center gap-1.5">
                  <img alt="Deals" loading="lazy" width="18" height="18" decoding="async" data-nimg="1" className="size-4.5" style={{"color":"transparent"}} src="/img/img-51131e414e.svg" />
                  <p className="truncate text-black-800 text-sm">
                    {"Deals"}
                  </p>
                </div>
                <div className="flex shrink-0 items-center gap-1.5">
                  <img alt="Workflows" loading="lazy" width="18" height="18" decoding="async" data-nimg="1" className="size-4.5" style={{"color":"transparent"}} src="/img/img-389465f763.svg" />
                  <p className="truncate text-black-800 text-sm">
                    {"Workflows"}
                  </p>
                </div>
                <div className="flex shrink-0 items-center gap-1.5">
                  <img alt="Notes" loading="lazy" width="18" height="18" decoding="async" data-nimg="1" className="size-4.5" style={{"color":"transparent"}} src="/img/img-81b440a874.svg" />
                  <p className="truncate text-black-800 text-sm">
                    {"Notes"}
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="col-[2/-2] lg:hidden">
            <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
              <div className="col-[2/-2] flex justify-between" />
            </div>
            <div className="flex flex-col">
              <img alt="Riya Grover" loading="lazy" width="900" height="1100" decoding="async" data-nimg="1" className="mb-7 h-auto w-30 object-contain" style={{"color":"transparent"}} srcSet="/img/img-f912474121.png 1x, /img/img-f912474121.png 2x" src="/img/img-f912474121.png" />
              <QuoteWordRevealSm quote={QUOTE} smHide={[26]} />
              <p className="mt-6 font-medium text-secondary-foreground text-sm">
                <span className="font-bold">
                  {"Riya Grover"}
                </span>
                {" · "}
                {"Co-founder & CEO, Sequence"}
              </p>
            </div>
            <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
              <div className="col-[2/-2] flex justify-between" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
