// Generated by scripts/port.ts. Hand edits are expected from here on.
import { FaqItem, FaqRoot } from "@/components/pages/pricing/faq-accordion";

const FAQ_IDS = ["how-do-i-get-started", "what-makes-someone-an-ideal-joshuattio-app-partner", "can-i-monetize-my-app"];

export function FrequentlyAskedQuestions() {
  return (
    <section className="container">
      <div className="border-subtle-stroke border-x">
        <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
          <div className="col-[2/-2] flex justify-between" />
        </div>
        <div className="grid grid-cols-12">
          <div className="space-y-4 lg:space-y-6 col-[2/-2] lg:col-[3/-3] xl:col-[4/-4]">
            <h2 id="faq" className="pr-6 text-heading-responsive-md text-secondary-foreground">
              {"Frequently asked questions"}
            </h2>
            <div>
              <FaqRoot questions={FAQ_IDS}>
                <FaqItem id="how-do-i-get-started" index={0} triggerId="base-ui-_R_1baqnpfiv9f9k7ivbH2_" panelId="base-ui-_R_1baqnpfiv9f9k7ivbH1_" question={"How do I get started?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"To get started, we recommend creating a "}
                        <a href="/" target="_blank" rel="noopener noreferrer" className="-mx-px rounded-sm px-px underline transition-colors duration-400 hover:duration-150 active:duration-50 text-link-foreground decoration-transparent hover:text-link-strong-foreground hover:decoration-link-strong-foreground active:text-link-strong-foreground">
                          {"developer account"}
                        </a>
                        {" and familiarizing yourself with our "}
                        <a href="/" target="_blank" rel="noopener noreferrer" className="-mx-px rounded-sm px-px underline transition-colors duration-400 hover:duration-150 active:duration-50 text-link-foreground decoration-transparent hover:text-link-strong-foreground hover:decoration-link-strong-foreground active:text-link-strong-foreground">
                          {"API documentation"}
                        </a>
                        {"."}
                      </p>
                    </div>
                  </div>
                </FaqItem>
                <FaqItem id="what-makes-someone-an-ideal-joshuattio-app-partner" index={1} triggerId="base-ui-_R_2baqnpfiv9f9k7ivbH2_" panelId="base-ui-_R_2baqnpfiv9f9k7ivbH1_" question={"What makes someone an ideal Joshuattio App Partner?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"The app partner program is open to all developers, although we’re especially interested in working with teams who have mutual customers with Joshuattio and are looking to build an integration between our products."}
                      </p>
                    </div>
                  </div>
                </FaqItem>
                <FaqItem id="can-i-monetize-my-app" index={2} triggerId="base-ui-_R_3baqnpfiv9f9k7ivbH2_" panelId="base-ui-_R_3baqnpfiv9f9k7ivbH1_" question={"Can I monetize my app?"}>
                  <div className="font-normal pt-3 text-base text-tertiary-foreground">
                    <div>
                      <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                        {"We don’t offer native monetization as part of the App Store, but you are free to charge users of your app how you see fit."}
                      </p>
                    </div>
                  </div>
                </FaqItem>
              </FaqRoot>
            </div>
          </div>
        </div>
        <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
          <div className="col-[2/-2] flex justify-between" />
        </div>
      </div>
    </section>
  );
}
