// Generated by scripts/port.ts. Hand edits are expected from here on.
import { TabsFullScreen, type ShowcaseTab } from "@/components/pages/solutions/shared/tabs-full-screen";

const TABS: ShowcaseTab[] = [
  {
    title: "Contacts",
    desktop: { src: "/img/img-15f881ee3c.avif", width: 10320, height: 5816 },
    mobile: { src: "/img/img-6526fe0fc8.avif", width: 3200, height: 6938 },
  },
  {
    title: "Pipelines",
    desktop: { src: "/img/img-4a2a2593fd.png", width: 10320, height: 5816 },
    mobile: { src: "/img/img-24b345d186.png", width: 3200, height: 6938 },
  },
  {
    title: "Activity",
    desktop: { src: "/img/img-6cc4fb89ff.png", width: 12082, height: 9065 },
    mobile: { src: "/img/img-58ce7d59f2.png", width: 3200, height: 6938 },
  },
  {
    title: "Reporting",
    desktop: { src: "/img/img-1c535ac9dd.png", width: 12082, height: 9065 },
  },
];
export function Block3() {
  return (
    <section className="">
      <div className="w-full">
        <div className="border-subtle-stroke pb-10 lg:pb-16 xl:pb-24">
          <div className="col-span-12 xl:col-start-2 xl:col-end-12">
            <TabsFullScreen tabs={TABS} />
          </div>
        </div>
      </div>
    </section>
  );
}
