// Generated by scripts/port.ts. Hand edits are expected from here on.
export function Block6() {
  return (
    <section className="">
      <div className="container">
        <div className="border-subtle-stroke grid grid-cols-12 gap-x-6 pt-10 lg:pt-16 xl:pt-24 pb-10 lg:pb-16 xl:pb-24">
          <div className="col-span-12 xl:col-start-2 xl:col-end-12">
            <div className="container">
              <div className="m-auto flex max-w-2xl flex-col items-start gap-y-6 text-secondary-foreground sm:items-center">
                <img alt="" loading="lazy" width="800" height="800" decoding="async" data-nimg="1" className="size-11 rounded-full [filter:drop-shadow(0px_0px_1.46667px_rgba(0,_0,_0,_0.1))_drop-shadow(0px_1.46667px_2.93333px_rgba(0,_0,_0,_0.1))]" style={{"color":"transparent"}} srcSet="/img/img-25608fc1dd.avif 1x, /img/img-25608fc1dd.avif 2x" src="/img/img-25608fc1dd.avif" />
                <div className="font-normal text-xl sm:text-center lg:font-normal lg:text-2xl">
                  {"Joshuattio is the most flexible CRM we’ve ever come across. We’ve been able to build a world-class go-to-market engine, from our sales pipelines to customer onboarding processes to customer success. There’s nothing like it in the market."}
                </div>
                <div className="flex flex-col items-start gap-y-0.5 text-sm sm:items-center">
                  <p>
                    {"Taimur Abdaal"}
                  </p>
                  <p className="text-tertiary-foreground">
                    {"Co-Founder & CTO"}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
