// Generated by scripts/port.ts. Hand edits are expected from here on.
import { PlainQuote } from "./ci-plain-quote";

export function Block4() {
  return (
    <div className="container flex flex-1 flex-col max-lg:contents">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x max-lg:border-none">
        <div className="relative flex min-h-[62svh] flex-col justify-center">
          <svg width="100%" height="100%" className="text-muted-strong-background absolute inset-0">
            <defs>
              <pattern id="_S_4_" width="10" height="10" patternUnits="userSpaceOnUse">
                <rect x="5.5" y="5.5" width="1" height="1" fill="currentColor" />
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#_S_4_)" />
          </svg>
          <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
            <div className="col-[2/-2] flex justify-between" />
          </div>
          <div className="relative grid flex-1 grid-cols-12 items-center">
            <div className="col-[2/-2] flex flex-col items-center">
              <PlainQuote className="max-w-[20em] text-pretty text-center text-heading-responsive-md-serif" quote={"Call Intelligence has been a game changer, both for our leads and customers – it just works."} />
              <p className="mt-12 text-center font-semibold text-secondary-foreground text-sm">
                {"Youmna Sirgi "}
              </p>
              <p className="mt-0.5 text-center text-secondary-foreground text-sm">
                {"Head of Operations · Plain"}
              </p>
            </div>
          </div>
          <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
            <div className="col-[2/-2] flex justify-between" />
          </div>
        </div>
      </div>
    </div>
  );
}
