// Generated by scripts/port.ts. Hand edits are expected from here on.
import { ProcedureItems, type ProcedureItem } from "./procedure-items";

// Brand copy wraps one line longer below xl; "unique" drops there to keep the rows at their height.
const ITEMS: ProcedureItem[] = [
  {
    id: "application-form",
    title: "Application form",
    description: (
      <>
        {"Share what excites you about working with Joshuattio, your "}
        <span className="max-xl:hidden">{"unique "}</span>
        {"experience, and your skills."}
      </>
    ),
  },
  {
    id: "skills-presentation",
    title: "Skills presentation",
    description: "Walk through your Joshuattio customer work or complete our case study project.",
  },
  {
    id: "onboarding-call",
    title: "Onboarding call",
    description: "Meet the team and learn how to succeed as an Joshuattio Expert.",
  },
  {
    id: "experts-directory",
    title: "Experts Directory",
    description: "Get listed in our Directory and be discovered by customers.",
  },
];

export function YourPathToThe() {
  return (
    <div className="container flex flex-1 flex-col">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x">
        <header className="grid grid-cols-12 pt-40 pb-20 max-xl:pt-30 max-xl:pb-16 max-lg:pt-25 max-lg:pb-15 justify-items-start">
          <div className="max-w-[20em] text-pretty text-heading-responsive-sm text-start col-[2/-2] mix-blend-multiply dark:mix-blend-screen">
            <h2 className="text-pretty inline">
              {"Your path to the Experts Directory."}
            </h2>
            {" "}
            <p className="inline text-pretty font-medium text-black-800">
              {"Four steps to join the "}
              <span className="max-md:hidden">{"Joshuattio "}</span>
              {"Experts community."}
            </p>
          </div>
        </header>
        <div className="relative grid grid-cols-12">
          <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25 absolute -top-5 h-5! max-lg:hidden">
            <div className="col-[2/-2] flex justify-between">
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
              <svg width="1" height="100%" className="text-subtle-stroke">
                <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
              </svg>
            </div>
          </div>
          <svg width="100%" height="1" className="text-subtle-stroke absolute top-0 max-lg:hidden">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
          </svg>
          <svg width="100%" height="1" className="text-subtle-stroke absolute bottom-0 max-lg:hidden">
            <line x1="0" y1="0.5" x2="100%" y2="0.5" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
          </svg>
          <div className="size-full text-surface-subtle absolute inset-0 max-lg:hidden" style={{"backgroundImage":"repeating-linear-gradient(125deg, transparent, transparent 6px, currentColor 6px, currentColor 7px)"}} />
          <div className="relative col-span-full flex flex-col border-subtle-stroke border-t bg-primary-background lg:col-[2/-2] lg:border">
            <ProcedureItems items={ITEMS} />
            <a href="#expert-partners-form" className="group relative grid cursor-pointer grid-cols-12 items-baseline border-subtle-stroke border-t py-5 lg:grid-cols-20 max-lg:border-y">
              <div className="absolute inset-0 bg-white-200 opacity-0 transition-opacity duration-400 ease-in-out group-hover:opacity-70 group-hover:duration-150 group-active:opacity-100 group-active:duration-50" />
              <div className="relative col-[2/-2] flex items-center gap-2 mix-blend-multiply">
                <p className="font-medium text-base text-tertiary-foreground">
                  {"Apply now"}
                </p>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="transition-[translate] duration-400 ease-in-out group-hover:translate-x-px group-hover:duration-150 group-active:translate-x-px group-active:duration-50">
                  <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.1" d="M2.25 7h9.5m0 0L8.357 3.5M11.75 7l-3.393 3.5" />
                </svg>
              </div>
            </a>
          </div>
        </div>
        <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25 max-lg:*:hidden">
          <div className="col-[2/-2] flex justify-between">
            <svg width="1" height="100%" className="text-subtle-stroke">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
            <svg width="1" height="100%" className="text-subtle-stroke">
              <line x1="0.5" y1="0" x2="0.5" y2="100%" stroke="currentColor" strokeDasharray="4 6" strokeLinecap="round" />
            </svg>
          </div>
        </div>
      </div>
    </div>
  );
}
