// Generated by scripts/port.ts. Hand edits are expected from here on.
import { FaqItem, FaqRoot } from "@/components/pages/pricing/faq-accordion";

const FAQ_IDS = ["what-is-the-referral-program", "are-there-any-terms-and-conditions-i-should-be-aware-of", "what-counts-as-a-valid-referral", "what-do-i-get", "can-referral-rewards-be-combined-with-other-offers", "ive-referred-someone-but-havent-got-my-gift-card-why"];

export function FrequentlyAskedQuestions() {
  return (
    <div className="container flex flex-1 flex-col">
      <div className="flex w-full flex-1 flex-col border-subtle-stroke border-x">
        <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
          <div className="col-[2/-2] flex justify-between" />
        </div>
        <div className="grid grid-cols-12">
          <div className="space-y-4 lg:space-y-6 col-[2/-2] lg:col-[3/-3] xl:col-[4/-4]">
            <h2 id="faq" className="pr-6 text-heading-responsive-md text-secondary-foreground">
              {"Frequently asked questions"}
            </h2>
            <div>
              <FaqRoot questions={FAQ_IDS}>
                <FaqItem id="what-is-the-referral-program" index={0} triggerId="base-ui-_R_2mjlfiv9f9k7ivbH2_" panelId="base-ui-_R_2mjlfiv9f9k7ivbH1_" question={"What is the Referral Program?"}>
                    <div className="font-normal pt-3 text-base text-tertiary-foreground">
                      <div>
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          <span>
                            {"Refer your friend to Joshuattio Pro / Enterprise and you’ll get a $200 gift card for every valid referral. Your referral gets 10% off their first year on a paid plan."}
                          </span>
                        </p>
                      </div>
                    </div>
                </FaqItem>
                <FaqItem id="are-there-any-terms-and-conditions-i-should-be-aware-of" index={1} triggerId="base-ui-_R_4mjlfiv9f9k7ivbH2_" panelId="base-ui-_R_4mjlfiv9f9k7ivbH1_" question={"Are there any terms and conditions I should be aware of?"}>
                    <div className="font-normal pt-3 text-base text-tertiary-foreground">
                      <div>
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          <span>
                            {"Please refer to our "}
                          </span>
                          <a target="_self" className="-mx-px rounded-sm px-px underline transition-colors duration-400 hover:duration-150 active:duration-50 text-link-foreground decoration-transparent hover:text-link-strong-foreground hover:decoration-link-strong-foreground active:text-link-strong-foreground" href="/legal/referral-gift-card-reward-policy">
                            {"Referral Gift Card Policy"}
                          </a>
                          <span>
                            {" for more detail."}
                          </span>
                        </p>
                      </div>
                    </div>
                </FaqItem>
                <FaqItem id="what-counts-as-a-valid-referral" index={2} triggerId="base-ui-_R_6mjlfiv9f9k7ivbH2_" panelId="base-ui-_R_6mjlfiv9f9k7ivbH1_" question={"What counts as a valid referral?"}>
                    <div className="font-normal pt-3 text-base text-tertiary-foreground">
                      <div>
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          <span>
                            {"Your referral is valid when a new workspace signs up with your referral link and converts to Pro / Enterprise plan within 60 days of signing up to Joshuattio and remains on the plan for 3 consecutive months after their two-week trial."}
                          </span>
                          <br />
                          <br />
                          <span>
                            {"The workspace you refer through your link can convert to Pro / Enterprise at any point during the 3 months Promo Window, but any cancellation, downgrade, or deletion after their first paid date, will disqualify them as a valid referral."}
                          </span>
                        </p>
                      </div>
                    </div>
                </FaqItem>
                <FaqItem id="what-do-i-get" index={3} triggerId="base-ui-_R_8mjlfiv9f9k7ivbH2_" panelId="base-ui-_R_8mjlfiv9f9k7ivbH1_" question={"What do I get?"}>
                    <div className="font-normal pt-3 text-base text-tertiary-foreground">
                      <div>
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          <span>
                            {"For every valid referral,"}
                          </span>
                          <b className="in-[p]:font-semibold">
                            <span>
                              {" "}
                            </span>
                          </b>
                          <span>
                            {"you’ll receive a $200 digital gift card, delivered via email to the address associated with your Joshuattio account. We’ll send it to you within 30 days of your referral completing the 3-month qualifying period."}
                          </span>
                        </p>
                      </div>
                    </div>
                </FaqItem>
                <FaqItem id="can-referral-rewards-be-combined-with-other-offers" index={4} triggerId="base-ui-_R_amjlfiv9f9k7ivbH2_" panelId="base-ui-_R_amjlfiv9f9k7ivbH1_" question={"Can referral rewards be combined with other offers?"}>
                    <div className="font-normal pt-3 text-base text-tertiary-foreground">
                      <div>
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          <span>
                            {"No. Referral rewards - both the gift card and the 10% discount - cannot be combined with any other promotional or incentive offers, including but not limited to: startup program discount, sales offers, and any other special promos. The reward applies only to new workspaces that sign up using your link."}
                          </span>
                        </p>
                      </div>
                    </div>
                </FaqItem>
                <FaqItem id="ive-referred-someone-but-havent-got-my-gift-card-why" index={5} triggerId="base-ui-_R_cmjlfiv9f9k7ivbH2_" panelId="base-ui-_R_cmjlfiv9f9k7ivbH1_" question={"I've referred someone but haven't got my gift card - why?"}>
                    <div className="font-normal pt-3 text-base text-tertiary-foreground">
                      <div>
                        <p className="not-first:mt-5 text-pretty [h4+&:not(:first-child)]:mt-2.5 [p+&:not(:first-child)]:mt-5">
                          <span>
                            {"The most common reasons why you haven’t received a gift-card are: the 3-month qualifying period hasn’t elapsed yet, your referral didn’t sign up using your unique link, the referral didn't convert to Pro/Enterprise within 60 days of signing up, or the referred workspace has cancelled, deleted, or downgraded to the Free or Plus plan after their first paid date."}
                          </span>
                        </p>
                      </div>
                    </div>
                </FaqItem>
              </FaqRoot>
            </div>
          </div>
        </div>
        <div aria-hidden="true" className="grid h-40 w-full grid-cols-12 overflow-hidden max-xl:h-30 max-lg:h-25">
          <div className="col-[2/-2] flex justify-between" />
        </div>
      </div>
    </div>
  );
}
